= Restore a cluster from cloud storage with Platform Operator
:github-directory: https://github.com/hazelcast-guides/hazelcast-platform-operator-external-backup-restore
:description: Learn how to back up data in Hazelcast maps to cloud storage and restore a cluster from that backup data.

{description}

== Overview

In this tutorial, you'll do the following:

- Deploy Hazelcast with persistence enabled

- Create a Hazelcast map that has persistence enabled

- Back up all map entries to external storage in the Cloud

- Restart the Hazelcast cluster and restore the backup map entries from the Cloud

The tutorial should take approximately 20 minutes to complete. 

== Prerequisites

Before you begin, make sure that you have:

* An up and running https://kubernetes.io/[Kubernetes] cluster
* Kubernetes command-line tool, https://kubernetes.io/docs/tasks/tools/#kubectl[kubectl]
* Deployed xref:operator:ROOT:get-started.adoc[Hazelcast Platform Operator]
* Created blob storage and access credentials in one of the Cloud providers: https://aws.amazon.com/s3/[AWS] - https://cloud.google.com/storage/[GCP] - https://azure.microsoft.com/en-us/services/storage/blobs/[Azure]
* The Hazelcast Code Samples repository https://github.com/hazelcast/hazelcast-code-samples cloned to your local machine

== Start the Hazelcast cluster

. Create a license secret
+
Create a secret with your link:http://trialrequest.hazelcast.com/[Hazelcast Enterprise License].
+
[source, shell]
----
kubectl create secret generic hazelcast-license-key --from-literal=license-key=<hz-license-key>
----

. Create the Hazelcast cluster
+
Create the Hazelcast cluster with Persistence enabled:
+
[source, shell]
----
kubectl apply -f - <<EOF
include::templates:ROOT:example$/platform-operator/hazelcast-platform-operator-external-backup-restore/docs/modules/ROOT/examples/operator-external-backup/hazelcast-persistence.yaml[]
EOF
----
+

. Check the cluster status
+
Run the following commands to see the cluster status:
+
[source, shell]
----
$ kubectl get hazelcast my-hazelcast
NAME           STATUS    MEMBERS
my-hazelcast   Running   3/3
----
+
[source, shell]
----
$ kubectl get pods -l app.kubernetes.io/instance=my-hazelcast
NAME             READY   STATUS    RESTARTS   AGE
my-hazelcast-0   2/2     Running   0          3m43s
my-hazelcast-1   2/2     Running   0          3m16s
my-hazelcast-2   2/2     Running   0          2m50s
----
+
As you can see from the pod states, the agent container will be deployed with the Hazelcast container in the same Pod. The agent is responsible for backing data up into the external storage.

. Get the address of the Hazelcast cluster
+
After verifying that the cluster is `Running` and all the members are ready, find the discovery address:

+
[source, shell]
----
$ kubectl get hazelcastendpoint my-hazelcast
NAME               TYPE        ADDRESS
my-hazelcast       Discovery   34.30.60.128:5701
----
+
The `ADDRESS` column displays the external address of your Hazelcast cluster.

== Create persistent map and put data

. Create persistent map
+
Create the Map resource with Persistence enabled:
+
[source, shell]
----
kubectl apply -f - <<EOF
include::templates:ROOT:example$/platform-operator/hazelcast-platform-operator-external-backup-restore/docs/modules/ROOT/examples/operator-external-backup/map-persistence.yaml[]
EOF
----


. Check the status of the backup
+
Check the status of the map configuration:
+
[source,bash]
----
kubectl get map persistent-map
----
+
The status of the map is displayed in the output.
+
[source,bash]
----
NAME             STATUS
persistent-map   Success
----

. Configure the Hazelcast client to connect to the cluster. [[Configure-Client]]

+
Open the examples folder to access all sample clients:
+
[source, shell]
----
cd hazelcast-platform-operator-external-backup-restore
----
+
The sample code (excluding CLC) for this tutorial is in the link:https://github.com/hazelcast/hazelcast-code-samples/tree/master/platform-operator/hazelcast-platform-operator-external-backup-restore/docs/modules/ROOT/examples/operator-external-backup[`docs/modules/ROOT/examples/operator-external-backup`] directory.

+
[tabs]
====

CLC::
+
--
NOTE: CLC must be installed in your system. See the https://docs.hazelcast.com/clc/5.5.0/install-clc[CLC installation instructions].

Add the cluster config to the CLC:

[source, bash]
----
clc config add hz cluster.name=dev cluster.address=<EXTERNAL-IP>
----
--

Java::
+
--
[source, java]
----
include::templates:ROOT:example$/platform-operator/hazelcast-platform-operator-external-backup-restore/docs/modules/ROOT/examples/operator-external-backup/java/src/main/java/com/hazelcast/Main.java[]
----
--

NodeJS::
+
--
[source, javascript]
----
include::templates:ROOT:example$/platform-operator/hazelcast-platform-operator-external-backup-restore/docs/modules/ROOT/examples/operator-external-backup/nodejs/client.js[]
----
--

Go::
+
--
[source, go]
----
include::templates:ROOT:example$/platform-operator/hazelcast-platform-operator-external-backup-restore/docs/modules/ROOT/examples/operator-external-backup/go/main.go[]
----
--

Python::
+
--
[source, python]
----
include::templates:ROOT:example$/platform-operator/hazelcast-platform-operator-external-backup-restore/docs/modules/ROOT/examples/operator-external-backup/python/main.py[]
----
--
.NET::
+
--
[source, cs]
----
include::templates:ROOT:example$/platform-operator/hazelcast-platform-operator-external-backup-restore/docs/modules/ROOT/examples/operator-external-backup/dotnet/Program.cs[]
----
--


====
+
. Start the client to fill the map.

+
[tabs]
====

CLC::
+
--
Fill a map:

[source, bash]
----
for i in {1..10};
do
   clc -c hz map set --name persistent-map key-$i value-$i;
done
----

Check the map size:

[source, bash]
----
clc -c hz map size --name persistent-map
----
--

Java::
+
--
[source, bash]
----
cd java
mvn package
java -jar target/*jar-with-dependencies*.jar fill
----

You should see the following output:

[source, shell]
----
Successful connection!
Starting to fill the map with random entries.
Current map size: 2
Current map size: 3
Current map size: 4
....
....
----
--

NodeJS::
+
--
[source, bash]
----
cd nodejs
npm install
npm start fill
----

You should see the following output:

[source, shell]
----
Successful connection!
Starting to fill the map with random entries.
Current map size: 2
Current map size: 3
Current map size: 4
....
....
----
--

Go::
+
--
[source, bash]
----
cd go
go run main.go fill
----

You should see the following output:

[source, shell]
----
Successful connection!
Starting to fill the map with random entries.
Current map size: 2
Current map size: 3
Current map size: 4
....
....
----
--

Python::
+
--
[source, bash]
----
cd python
pip install -r requirements.txt
python main.py fill
----

You should see the following output:

[source, shell]
----
Successful connection!
Starting to fill the map with random entries.
Current map size: 2
Current map size: 3
Current map size: 4
....
....
----
--
.NET::
+
--
[source, bash]
----
cd dotnet
dotnet build
dotnet run fill
----
[source, shell]
----
Successful connection!
Starting to fill the map with random entries.
Current map size: 2
Current map size: 3
Current map size: 4
....
....
----
--

====

== Trigger external backup

For triggering backup, you need `bucketURI` where backup data will be stored in, and a `secret` with credentials for accessing the given Bucket URI.

. Create Secret
+
Run one of the following commands to create the secret according to the Cloud provider you want to backup:

+
[tabs]
====

AWS::
+
--
[source,bash]
----
kubectl create secret generic <external-bucket-secret-name> --from-literal=region=<region> \
	--from-literal=access-key-id=<access-key-id> \
	--from-literal=secret-access-key=<secret-access-key>
----
--

GCP::
+
--
[source,bash]
----
kubectl create secret generic <external-bucket-secret-name> --from-file=google-credentials-path=<service_account_json_file>
----
--

Azure::
+
--
[source,bash]
----
kubectl create secret generic <external-bucket-secret-name> \
	--from-literal=storage-account=<storage-account> \
	--from-literal=storage-key=<storage-key>
----
--

NOTE: If you want to learn more about other authentication methods, check the xref:operator:ROOT:authorization.adoc[Authorization Methods to Access Cloud Storage] documentation.

====

. Trigger backup
+
Run the following command to trigger backup:
+
[source, shell]
----
kubectl apply -f - <<EOF
include::templates:ROOT:example$/platform-operator/hazelcast-platform-operator-external-backup-restore/docs/modules/ROOT/examples/operator-external-backup/hot-backup.yaml[]
EOF
----
+
*Example URI -> "s3://operator-backup?prefix=hazelcast/2022-06-08-17-01-20/"*

+
. Check the status of the backup
+
Run the following command to check the status of the backup:
+
[source,bash]
----
kubectl get hotbackup hot-backup
----
+
The status of the backup is displayed in the output.
+
[source,bash]
----
NAME         STATUS
hot-backup   Success
----

== Restore from external backup

. Delete the Hazelcast cluster
+
Run the following command to delete the Hazelcast cluster:
+
[source,bash]
----
kubectl delete hazelcast my-hazelcast
----

. Delete the PersistentVolumeClaims
+
The data is restored from external buckets, so you don't keep persistent volumes during a restore operation.
+
List PVCs which were created for the Hazelcast cluster:
+
[source,bash]
----
$ kubectl get pvc -l "app.kubernetes.io/managed-by=hazelcast-platform-operator"
NAME                         STATUS   VOLUME                                     CAPACITY
persistence-my-hazelcast-0   Bound    pvc-a77fcd6e-e64d-4aeb-9708-835d66b4c5b9   8Gi
persistence-my-hazelcast-1   Bound    pvc-8548a4a5-fa8e-45bd-9909-8e6bb6a6c3e8   8Gi
persistence-my-hazelcast-2   Bound    pvc-c94edb25-5a72-482a-bf4e-84a99319d509   8Gi
----

+
Delete the PVCs:
+
[source,bash]
----
kubectl delete pvc -l "app.kubernetes.io/managed-by=hazelcast-platform-operator"
----

. Create new Hazelcast cluster
+
For restoring, you will use the `HotBackup` resource you have created.
+
Create the Hazelcast cluster. Before the Hazelcast cluster is started,
the Operator starts the agent (as InitContainer) which restores the backup data from the external bucket.
+
[source, shell]
----
kubectl apply -f - <<EOF
include::templates:ROOT:example$/platform-operator/hazelcast-platform-operator-external-backup-restore/docs/modules/ROOT/examples/operator-external-backup/hazelcast-persistence-restore.yaml[]
EOF
----
+
As you may see, the agent configuration is not set. Thus, the Operator directly uses the latest stable version of the agent.

. Check the cluster status
+
Run the following commands to see the cluster status:
+
[source, shell]
----
$ kubectl get hazelcast my-hazelcast
NAME           STATUS    MEMBERS
my-hazelcast   Running   3/3
----
+
After verifying that the cluster is `Running` and all the members are ready, find the discovery address:
+
[source, shell]
----
$ kubectl get hazelcastendpoint my-hazelcast
NAME           TYPE        ADDRESS
my-hazelcast   Discovery   34.28.159.226:5701
----
+
Since we recreate the Hazelcast cluster, services are also recreated. The `ADDRESS` may change.

. Check the map size
+
Configure the Hazelcast client to connect to the cluster external address as you did in <<Configure-Client, Configure the Hazelcast Client>>.
+
Start the client to check the map size and see if the restore is successful.
+
[tabs]
====

CLC::
+
--
[source, bash]
----
clc -c hz map size --name persistent-map
----
--

Java::
+
--
[source, bash]
----
cd java
mvn package
java -jar target/*jar-with-dependencies*.jar size
----

You should see the following output:

[source, shell]
----
Successful connection!
Current map size: 12
----
--

NodeJS::
+
--
[source, bash]
----
cd nodejs
npm install
npm start size
----

You should see the following output:

[source, shell]
----
Successful connection!
Current map size: 12
----
--

Go::
+
--
[source, bash]
----
cd go
go run main.go size
----

You should see the following output:

[source, shell]
----
Successful connection!
Current map size: 12
----
--

Python::
+
--
[source, bash]
----
cd python
pip install -r requirements.txt
python main.py size
----

You should see the following output:

[source, shell]
----
Successful connection!
Current map size: 12
----
--
.NET::
+
--
[source, bash]
----
cd dotnet
dotnet run size
----

You should see the following output:

[source, shell]
----
Successful connection!
Current map size: 12
----
--

====

== Clean up

To clean up the created resources, remove all Custom Resources and PVCs.

[source, shell]
----
kubectl delete secret <external-bucket-secret-name>
kubectl delete secret hazelcast-license-key
kubectl delete $(kubectl get hazelcast,hotbackup -o name)
kubectl delete pvc -l "app.kubernetes.io/managed-by=hazelcast-platform-operator"
----

== Summary

In this tutorial, you've learned how to:

- Deploy Hazelcast with persistence enabled

- Create a Hazelcast map that has persistence enabled

- Back up all map entries to external storage in the Cloud

- Restart the Hazelcast cluster and restore the backup map entries from the Cloud

== Next steps

See also:

- xref:operator:ROOT:backup-restore.adoc[]
- xref:operator-tutorial-expose-externally.adoc[]
