apiVersion: hazelcast.com/v1alpha1
kind: Flow
metadata:
  labels:
    app.kubernetes.io/name: hazelcast-platform-operator
  name: flow
spec:
  size: 3
  licenseKeySecretName: hazelcast-license-key
  externalConnectivity:
    ingress:
      hostname: ""
      ingressClassName: nginx
      path: "/"
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/enable-opentelemetry: "true"
  database:
    host: "flow-database"
    secretName: flow-db-secret
  env:
  - name: OPTIONS
    value: |
      --flow.analytics.persistRemoteCallResponses=true
      --flow.analytics.persistResults=false
      --flow.config.custom.managementCenterUrl=http://233.252.0.158/mc
