apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  clusterSize: 3
  repository: 'docker.io/hazelcast/hazelcast-enterprise'
  licenseKeySecretName: hazelcast-license-key
  cpSubsystem:
    groupSize: 3
    sessionTTLSeconds: 30
    pvc:
      accessModes: ["ReadWriteOnce"]
      requestStorage: 8Gi
