apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  clusterSize: 3
  repository: 'docker.io/hazelcast/hazelcast-enterprise'
  licenseKeySecretName: hazelcast-license-key
  userCodeNamespaces:
    pvc:
      accessModes: ["ReadWriteOnce"]
      requestStorage: 1Gi
