apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  clusterSize: 3
  repository: 'docker.io/hazelcast/hazelcast-enterprise'
  version: '{page-latest-supported-hazelcast}-slim'
  licenseKeySecret: hazelcast-license-key
  persistence:
    backupType: "External" <1>
    baseDir: "/data/hot-restart/"
    clusterDataRecoveryPolicy: "FullRecoveryOnly"
    pvc:
      accessModes: ["ReadWriteOnce"]
      requestStorage: 20Gi
  agent: <2>
    repository: hazelcast/platform-operator-agent
    version: 0.1.0
