apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast-sample
spec:
  clusterSize: 3
  clusterName: mycluster
  repository: 'docker.io/hazelcast/hazelcast-enterprise'
  version: '{page-latest-supported-hazelcast}-slim'
  licenseKeySecretName: hazelcast-license-key
