apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  licenseKeySecretName: hazelcast-license-key
  moduleDeployment:
    bucketConfig:
      secretName: map-store-bucket-secret <1>
      bucketURI: gs://map-store-bucket/path/to/jars <2>
    configMaps:
    - domain-classes-cm
    - entryprocessor-cm
    remoteURLs:
    - https://example.com/entry-processor.jar
    triggerSequence: "001"
