apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  repository: 'docker.io/hazelcast/hazelcast-enterprise'
  licenseKeySecretName: hazelcast-license-key
  clusterSize: 3
  liteMember:
    count: 2
    scheduling:
      nodeSelector:
        topology.kubernetes.io/region: us-west1