apiVersion: hazelcast.com/v1alpha1
kind: Map
metadata:
  name: map-sample
spec:
  hazelcastResourceName: hazelcast-sample
  inMemoryFormat: NATIVE
  tieredStore:
    memoryCapacity: 128M
    diskDeviceName: device-sample