apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  serialization:
    javaSerializationFilter:
      whitelist:
        classes:
        - example.Foo
        packages:
        - com.acme.app
        prefixes:
        - com.hazelcast.
        - java.
        - javax.
        - \[
      blacklist:
        classes:
        - com.acme.app.BeanComparator
