apiVersion: hazelcast.com/v1alpha1
kind: UserCodeNamespace
metadata:
  name: ucn-sample
spec:
  hazelcastResourceName: hazelcast
  bucketConfig:
    secretName: cloud-storage-bucket-secret <1>
    bucketURI: gs://map-store-bucket/path/to/jars <2>
