apiVersion: hazelcast.com/v1alpha1
kind: UserCodeNamespace
metadata:
  name: ucn-sample
spec:
  hazelcastResourceName: hazelcast
  bucketConfig:
    secretName: s3-bucket-secret <1>
    bucketURI: s3://map-store-bucket/path/to/jars <2>
