apiVersion: hazelcast.com/v1alpha1
kind: WanSync
metadata:
  name: wansync-sample
spec:
  config:
    resources:
    - name: map-1
      kind: Map
    - name: map-2
      kind: Map
    targetClusterName: dev
    endpoints: "35.195.246.196"
