apiVersion: hazelcast.com/v1alpha1
kind: WanReplication
metadata:
  name: wanreplication-sample
spec:
  resources:
    - name: map-sample
      kind: Map
    - name: hz-sample
      kind: Hazelcast
  targetClusterName: dev
  endpoints: "198.51.100.252,198.51.100.255"
  queue:
    capacity: 10000
    fullBehavior: DISCARD_AFTER_MUTATION
  batch:
    size: 500
    maximumDelay: 1000
  acknowledgement:
    type: ACK_ON_OPERATION_COMPLETE
    timeout: 60000
