= Advanced Network Configuration
:description: With the default configuration, Hazelcast members use a single server socket for connections. With advanced network configuration, you can configure the use of separate server sockets. Hazelcast Operator enables advanced network by default with pre-configured networks for client, member, REST, and WAN protocols. 

{description}

When you configure Hazelcast members with separate server sockets, you can apply distinct network configurations for various protocols through the advanced network. For further information on the advanced network, refer to xref:hazelcast:clusters:network-configuration.adoc#advanced-network-configuration[Advanced Network Configuration,window=_blank] in the Platform documentation.

Hazelcast Operator enables the advanced network by default, and pre-configures the following protocol properties:

- Client protocol. Pre-configures the port number to `5701`.
- Member protocol. Pre-configures the port number to `5702`.
- REST. Pre-configures the following:

** The port number to `8081`.
** Enables the `Persistence` endpoint group.
** Enables the `HealthCheck` endpoint group.
** Enables the `ClusterWrite` endpoint group.

- WAN. Pre-configures the port number to `5710`.

You can configure Member and Client Protocol interfaces as well as WAN Protocol socket ports using Hazelcast Operator as shown below.

== Configure Member and Client Protocol Interfaces

This example configures member and client server socket endpoints for the WAN protocol.

The configuration is as follows:

.Example Configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/advanced-networking-interfaces.yaml[]
----

== Configuring WAN Protocol Sockets

This example configures WAN sockets.

The configuration is as follows:

.Example Configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/advanced-networking-wan.yaml[]
----

The valid values for the `serviceType` field are as follows: 

* `ClusterIP`
* `LoadBalancer`. If you don't provide a `serviceType`, this is set by default.

After this configuration has been applied, a single service is created with a type of `LoadBalancer`. This service exposes the following ports: 

* `5710`. If you don't provide WAN Replication configuration in the `advancedNetwork` configuration, port number `5710` is set by default.
* `5711`
* `5712`
* `5713`
* `5714`

To list the external addresses of the WAN endpoints of the cluster, use the following command:

[source,shell]
----
kubectl get hazelcastendpoint --selector="app.kubernetes.io/instance=hazelcast-sample"
----

The result is similar to the following:

```
NAME                          TYPE   ADDRESS
hazelcast-sample-istanbul-0   WAN    34.72.248.220:5710
hazelcast-sample-istanbul-1   WAN    34.72.248.220:5711
hazelcast-sample-istanbul-2   WAN    34.72.248.220:5712
hazelcast-sample-istanbul-3   WAN    34.72.248.220:5713
hazelcast-sample-istanbul-4   WAN    34.72.248.220:5714
```
