
= Hazelcast Platform Operator API Docs

A reference guide to the Hazelcast Platform Operator CRD types.

== Hazelcast Platform Operator API Docs

This is a reference for the Hazelcast Platform Operator API types.
These are all the types and fields that are used in the Hazelcast Platform Operator CRDs. 

TIP: This document was generated from comments in the Go code in the api/ directory.

=== Table of Contents
* <<BackupAgentConfiguration,BackupAgentConfiguration>>
* <<DataRecoveryPolicyType,DataRecoveryPolicyType>>
* <<ExposeExternallyConfiguration,ExposeExternallyConfiguration>>
* <<ExposeExternallyType,ExposeExternallyType>>
* <<Hazelcast,Hazelcast>>
* <<HazelcastClusterStatus,HazelcastClusterStatus>>
* <<HazelcastList,HazelcastList>>
* <<HazelcastMemberStatus,HazelcastMemberStatus>>
* <<HazelcastPersistenceConfiguration,HazelcastPersistenceConfiguration>>
* <<HazelcastSpec,HazelcastSpec>>
* <<HazelcastStatus,HazelcastStatus>>
* <<MemberAccess,MemberAccess>>
* <<PersistencePvcConfiguration,PersistencePvcConfiguration>>
* <<Phase,Phase>>
* <<RestoreState,RestoreState>>
* <<RestoreStatus,RestoreStatus>>
* <<SchedulingConfiguration,SchedulingConfiguration>>
* <<ExternalConnectivityConfiguration,ExternalConnectivityConfiguration>>
* <<ExternalConnectivityType,ExternalConnectivityType>>
* <<HazelcastClusterConfig,HazelcastClusterConfig>>
* <<ManagementCenter,ManagementCenter>>
* <<ManagementCenterList,ManagementCenterList>>
* <<ManagementCenterSpec,ManagementCenterSpec>>
* <<ManagementCenterStatus,ManagementCenterStatus>>
* <<PersistenceConfiguration,PersistenceConfiguration>>
* <<HotBackup,HotBackup>>
* <<HotBackupList,HotBackupList>>
* <<HotBackupSpec,HotBackupSpec>>
* <<HotBackupState,HotBackupState>>
* <<HotBackupStatus,HotBackupStatus>>
* <<BitmapIndexOptionsConfig,BitmapIndexOptionsConfig>>
* <<EvictionConfig,EvictionConfig>>
* <<IndexConfig,IndexConfig>>
* <<IndexType,IndexType>>
* <<Map,Map>>
* <<MapConfigState,MapConfigState>>
* <<MapList,MapList>>
* <<MapSpec,MapSpec>>
* <<MapStatus,MapStatus>>
* <<UniqueKeyTransition,UniqueKeyTransition>>

=== BackupAgentConfiguration



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| agentRepository | Repository to pull Hazelcast Platform Operator Agent(https://github.com/hazelcast/platform-operator-agent) m| string | false | "docker.io/hazelcast/platform-operator-agent"
m| agentVersion | Version of Hazelcast Platform Operator Agent. m| string | false | "1.0.0"
m| bucketSecret | Name of the secret with credentials for cloud providers. m| string | false | -
|===

<<Table of Contents,Back to TOC>>

=== ExposeExternallyConfiguration

ExposeExternallyConfiguration defines how to expose Hazelcast cluster to external clients

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| type | Specifies how members are exposed. Valid values are: - "Smart" (default): each member pod is exposed with a separate external address - "Unisocket": all member pods are exposed with one external address m| <<ExposeExternallyType,ExposeExternallyType>> | false | "Smart"
m| discoveryServiceType | Type of the service used to discover Hazelcast cluster. m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#servicetype-v1-core[corev1.ServiceType] | false | "LoadBalancer"
m| memberAccess | How each member is accessed from the external client. Only available for "Smart" client and valid values are: - "NodePortExternalIP" (default): each member is accessed by the NodePort service and the node external IP/hostname - "NodePortNodeName": each member is accessed by the NodePort service and the node name - "LoadBalancer": each member is accessed by the LoadBalancer service external address m| <<MemberAccess,MemberAccess>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== Hazelcast

Hazelcast is the Schema for the hazelcasts API

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#objectmeta-v1-meta[metav1.ObjectMeta] | false | -
m| spec | &#160; m| <<HazelcastSpec,HazelcastSpec>> | false | {"repository" : "docker.io/hazelcast/hazelcast"}
m| status | &#160; m| <<HazelcastStatus,HazelcastStatus>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== HazelcastClusterStatus

HazelcastClusterStatus defines the status of the Hazelcast cluster

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| readyMembers | ReadyMembers represents the number of members that are connected to cluster from the desired number of members in the format <ready>/<desired> m| string | true | -
|===

<<Table of Contents,Back to TOC>>

=== HazelcastList

HazelcastList contains a list of Hazelcast

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#listmeta-v1-meta[metav1.ListMeta] | false | -
m| items | &#160; m| []<<Hazelcast,Hazelcast>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== HazelcastMemberStatus

HazelcastMemberStatus defines the observed state of the individual Hazelcast member.

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| podName | PodName is the name of the Hazelcast member pod. m| string | false | -
m| uid | Uid is the unique member identifier within the cluster. m| string | false | -
m| ip | Ip is the IP address of the member within the cluster. m| string | false | -
m| version | Version represents the Hazelcast version of the member. m| string | false | -
m| state | State represents the observed state of the member. m| string | false | -
m| master | Master flag is set to true if the member is master. m| bool | false | -
m| lite | Lite is the flag that is true when the member is lite-member. m| bool | false | -
m| ownedPartitions | OwnedPartitions represents the partitions count on the member. m| int32 | false | -
m| connected | Ready is the flag that is set to true when the member is successfully started, connected to cluster and ready to accept connections. m| bool | true | -
m| message | Message contains the optional message with the details of the cluster state. m| string | false | -
m| reason | Reason contains the optional reason of member crash or restart. m| string | false | -
m| restartCount | RestartCount is the number of times the member has been restarted. m| int32 | true | -
|===

<<Table of Contents,Back to TOC>>

=== HazelcastPersistenceConfiguration

HazelcastPersistenceConfiguration contains the configuration for Hazelcast Persistence and K8s storage.

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| baseDir | Persistence base directory. m| string | true | -
m| clusterDataRecoveryPolicy | Configuration of the cluster recovery strategy. m| <<DataRecoveryPolicyType,DataRecoveryPolicyType>> | false | "FullRecoveryOnly"
m| autoForceStart | AutoForceStart enables the detection of constantly failing cluster and trigger the Force Start action. m| bool | false | false
m| dataRecoveryTimeout | DataRecoveryTimeout is timeout for each step of data recovery in seconds. Maximum timeout is equal to DataRecoveryTimeout*2 (for each step: validation and data-load). m| int32 | false | -
m| pvc | Configuration of PersistenceVolumeClaim. m| <<PersistencePvcConfiguration,PersistencePvcConfiguration>> | false | -
m| hostPath | Host Path directory. m| string | false | -
|===

<<Table of Contents,Back to TOC>>

=== HazelcastSpec

HazelcastSpec defines the desired state of Hazelcast

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| clusterSize | Number of Hazelcast members in the cluster. m| &#42;int32 | false | 3
m| repository | Repository to pull the Hazelcast Platform image from. m| string | false | "docker.io/hazelcast/hazelcast"
m| version | Version of Hazelcast Platform. m| string | false | "5.1"
m| imagePullPolicy | Pull policy for the Hazelcast Platform image m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#pullpolicy-v1-core[corev1.PullPolicy] | false | "IfNotPresent"
m| imagePullSecrets | Image pull secrets for the Hazelcast Platform image m| []https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#localobjectreference-v1-core[corev1.LocalObjectReference] | false | -
m| licenseKeySecret | Name of the secret with Hazelcast Enterprise License Key. m| string | false | -
m| exposeExternally | Configuration to expose Hazelcast cluster to external clients. m| &#42;<<ExposeExternallyConfiguration,ExposeExternallyConfiguration>> | false | {}
m| clusterName | Name of the Hazelcast cluster. m| string | false | "dev"
m| scheduling | Scheduling details m| &#42;<<SchedulingConfiguration,SchedulingConfiguration>> | false | {}
m| resources | Compute Resources required by the Hazelcast container. m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#resourcerequirements-v1-core[corev1.ResourceRequirements] | false | {}
m| persistence | Persistence configuration m| &#42;<<HazelcastPersistenceConfiguration,HazelcastPersistenceConfiguration>> | false | {}
m| backup | Backup Agent configuration m| &#42;<<BackupAgentConfiguration,BackupAgentConfiguration>> | false | {}
|===

<<Table of Contents,Back to TOC>>

=== HazelcastStatus

HazelcastStatus defines the observed state of Hazelcast

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| phase | Phase of the Hazelcast cluster m| <<Phase,Phase>> | false | -
m| hazelcastClusterStatus | Status of the Hazelcast cluster m| <<HazelcastClusterStatus,HazelcastClusterStatus>> | false | -
m| message | Message about the Hazelcast cluster state m| string | false | -
m| externalAddresses | External addresses of the Hazelcast cluster members m| string | false | -
m| members | Status of Hazelcast members m| []<<HazelcastMemberStatus,HazelcastMemberStatus>> | false | -
m| restore | Status of restore process of the Hazelcast cluster m| &#42;<<RestoreStatus,RestoreStatus>> | false | {}
|===

<<Table of Contents,Back to TOC>>

=== PersistencePvcConfiguration



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| accessModes | AccessModes contains the actual access modes of the volume backing the PVC has. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1 m| []https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#persistentvolumeaccessmode-v1-core[corev1.PersistentVolumeAccessMode] | false | -
m| requestStorage | A description of the PVC request capacity. m| &#42;resource.Quantity | false | -
m| storageClassName | Name of StorageClass which this persistent volume belongs to. m| &#42;string | false | -
|===

<<Table of Contents,Back to TOC>>

=== RestoreStatus



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| state | State shows the current phase of the restore process of the cluster. m| <<RestoreState,RestoreState>> | true | -
m| remainingValidationTime | RemainingValidationTime show the time in seconds remained for the restore validation step. m| int64 | true | -
m| remainingDataLoadTime | RemainingDataLoadTime show the time in seconds remained for the restore data load step. m| int64 | true | -
|===

<<Table of Contents,Back to TOC>>

=== SchedulingConfiguration

SchedulingConfiguration defines the pods scheduling details

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| affinity | Affinity m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#affinity-v1-core[corev1.Affinity] | false | -
m| tolerations | Tolerations m| []https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#toleration-v1-core[corev1.Toleration] | false | -
m| nodeSelector | NodeSelector m| map[string]string | false | -
m| topologySpreadConstraints | TopologySpreadConstraints m| []https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#topologyspreadconstraint-v1-core[corev1.TopologySpreadConstraint] | false | -
|===

<<Table of Contents,Back to TOC>>

=== ExternalConnectivityConfiguration

ExternalConnectivityConfiguration defines how to expose Management Center pod.

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| type | How Management Center is exposed. Valid values are: - "ClusterIP" - "NodePort" - "LoadBalancer" (default) m| <<ExternalConnectivityType,ExternalConnectivityType>> | false | "LoadBalancer"
|===

<<Table of Contents,Back to TOC>>

=== HazelcastClusterConfig



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| name | Name of the Hazelcast cluster that Management Center will connect to, default is dev. m| string | false | "dev"
m| address | IP address or DNS name of the Hazelcast cluster. If the cluster is exposed with a service name in a different namespace, use the following syntax "<service-name>.<service-namespace>". m| string | true | -
|===

<<Table of Contents,Back to TOC>>

=== ManagementCenter

ManagementCenter is the Schema for the managementcenters API

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#objectmeta-v1-meta[metav1.ObjectMeta] | false | -
m| spec | &#160; m| <<ManagementCenterSpec,ManagementCenterSpec>> | false | {"repository" : "docker.io/hazelcast/management-center"}
m| status | &#160; m| <<ManagementCenterStatus,ManagementCenterStatus>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== ManagementCenterList

ManagementCenterList contains a list of ManagementCenter

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#listmeta-v1-meta[metav1.ListMeta] | false | -
m| items | &#160; m| []<<ManagementCenter,ManagementCenter>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== ManagementCenterSpec

ManagementCenterSpec defines the desired state of ManagementCenter.

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| repository | Repository to pull the Management Center image from. m| string | false | "docker.io/hazelcast/management-center"
m| version | Version of Management Center. m| string | false | "5.1.1"
m| imagePullPolicy | Pull policy for the Management Center image m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#pullpolicy-v1-core[corev1.PullPolicy] | false | "IfNotPresent"
m| imagePullSecrets | Image pull secrets for the Management Center image m| []https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#localobjectreference-v1-core[corev1.LocalObjectReference] | false | -
m| licenseKeySecret | Name of the secret with Hazelcast Enterprise License Key. m| string | false | -
m| hazelcastClusters | Connection configuration for the Hazelcast clusters that Management Center will monitor. m| []<<HazelcastClusterConfig,HazelcastClusterConfig>> | false | -
m| externalConnectivity | Configuration to expose Management Center to outside. m| &#42;<<ExternalConnectivityConfiguration,ExternalConnectivityConfiguration>> | false | {type: "LoadBalancer"}
m| persistence | Configuration for Management Center persistence. m| &#42;<<PersistenceConfiguration,PersistenceConfiguration>> | false | {enabled: true, size: "10Gi"}
m| scheduling | Scheduling details m| &#42;<<SchedulingConfiguration,SchedulingConfiguration>> | false | -
m| resources | Compute Resources required by the MC container. m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#resourcerequirements-v1-core[corev1.ResourceRequirements] | false | {}
|===

<<Table of Contents,Back to TOC>>

=== ManagementCenterStatus

ManagementCenterStatus defines the observed state of ManagementCenter.

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| phase | Phase of the Management Center m| <<Phase,Phase>> | false | -
m| message | Message about the Management Center state m| string | false | -
m| externalAddresses | External addresses of the Management Center instance m| string | false | -
|===

<<Table of Contents,Back to TOC>>

=== PersistenceConfiguration



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| enabled | When true, MC will use a PersistentVolumeClaim to store data. m| bool | false | true
m| existingVolumeClaimName | Name of the PersistentVolumeClaim MC will use for persistence. If not empty, MC will use the existing claim instead of creating a new one. m| string | false | -
m| storageClass | StorageClass from which PersistentVolumeClaim will be created. m| &#42;string | false | -
m| size | Size of the created PersistentVolumeClaim. m| &#42;resource.Quantity | false | "10Gi"
|===

<<Table of Contents,Back to TOC>>

=== HotBackup

HotBackup is the Schema for the hot backup API

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#objectmeta-v1-meta[metav1.ObjectMeta] | false | -
m| status | &#160; m| <<HotBackupStatus,HotBackupStatus>> | false | -
m| spec | &#160; m| <<HotBackupSpec,HotBackupSpec>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== HotBackupList

HotBackupList contains a list of HotBackup

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#listmeta-v1-meta[metav1.ListMeta] | false | -
m| items | &#160; m| []<<HotBackup,HotBackup>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== HotBackupSpec

HotBackupSpec defines the Spec of HotBackup

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| hazelcastResourceName | HazelcastResourceName defines the name of the Hazelcast resource m| string | true | -
m| schedule | Schedule contains a crontab-like expression that defines the schedule in which HotBackup will be started. If the Schedule is empty the HotBackup will start only once when applied. m| string | false | -
m| bucket | URL of the bucket to download HotBackup folders. m| string | false | -
|===

<<Table of Contents,Back to TOC>>

=== HotBackupStatus

HotBackupStatus defines the observed state of HotBackup

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| state | &#160; m| <<HotBackupState,HotBackupState>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== BitmapIndexOptionsConfig



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| uniqueKey | &#160; m| string | true | -
m| uniqueKeyTransition | &#160; m| <<UniqueKeyTransition,UniqueKeyTransition>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== EvictionConfig



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| evictionPolicy | Eviction policy to be applied when map reaches its max size according to the max size policy. m| types.EvictionPolicyType | false | "NONE"
m| maxSize | Max size of the map. m| &#42;int32 | false | 0
m| maxSizePolicy | Policy for deciding if the maxSize is reached. m| types.MaxSizePolicyType | false | "PER_NODE"
|===

<<Table of Contents,Back to TOC>>

=== IndexConfig



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| name | Name of the index config. m| string | false | -
m| type | Type of the index. m| <<IndexType,IndexType>> | true | -
m| attributes | Attributes of the index. m| []string | true | -
m| bitMapIndexOptions | Options for "BITMAP" index type. m| &#42;<<BitmapIndexOptionsConfig,BitmapIndexOptionsConfig>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== Map

Map is the Schema for the maps API

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#objectmeta-v1-meta[metav1.ObjectMeta] | false | -
m| spec | &#160; m| <<MapSpec,MapSpec>> | true | -
m| status | &#160; m| <<MapStatus,MapStatus>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== MapList

MapList contains a list of Map

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#listmeta-v1-meta[metav1.ListMeta] | false | -
m| items | &#160; m| []<<Map,Map>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== MapSpec

MapSpec defines the desired state of Hazelcast Map Config

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| name | Name of the map config to be created. If empty, CR name will be used. It cannot be updated after map config is created successfully. m| string | false | -
m| backupCount | Count of synchronous backups. It cannot be updated after map config is created successfully. m| &#42;int32 | false | 1
m| timeToLiveSeconds | Maximum time in seconds for each entry to stay in the map. If it is not 0, entries that are older than this time and not updated for this time are evicted automatically. It can be updated. m| &#42;int32 | false | 0
m| maxIdleSeconds | Maximum time in seconds for each entry to stay idle in the map. Entries that are idle for more than this time are evicted automatically. It can be updated. m| &#42;int32 | false | 0
m| eviction | Configuration for removing data from the map when it reaches its max size. It can be updated. m| &#42;<<EvictionConfig,EvictionConfig>> | false | {maxSize: 0}
m| indexes | Indexes to be created for the map data. You can learn more at https://docs.hazelcast.com/hazelcast/latest/query/indexing-maps. It cannot be updated after map config is created successfully. m| []<<IndexConfig,IndexConfig>> | false | -
m| persistenceEnabled | When enabled, map data will be persisted. It cannot be updated after map config is created successfully. m| bool | false | false
m| hazelcastResourceName | HazelcastResourceName defines the name of the Hazelcast resource. It cannot be updated after map config is created successfully. m| string | true | -
|===

<<Table of Contents,Back to TOC>>

=== MapStatus

MapStatus defines the observed state of Map

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| state | &#160; m| <<MapConfigState,MapConfigState>> | false | -
m| message | &#160; m| string | false | -
m| memberStatuses | &#160; m| map[string]<<MapConfigState,MapConfigState>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== DataRecoveryPolicyType

DataRecoveryPolicyType represents the options for data recovery policy when the whole cluster restarts.

[cols="5,10"options="header"]
|===
| Value | Description
m| "FullRecoveryOnly" | FullRecovery does not allow partial start of the cluster and corresponds to "cluster-data-recovery-policy.FULL_RECOVERY_ONLY" configuration option.
m| "PartialRecoveryMostRecent" | MostRecent allow partial start with the members that have most up-to-date partition table and corresponds to "cluster-data-recovery-policy.PARTIAL_RECOVERY_MOST_RECENT" configuration option.
m| "PartialRecoveryMostComplete" | MostComplete allow partial start with the members that have most complete partition table and corresponds to "cluster-data-recovery-policy.PARTIAL_RECOVERY_MOST_COMPLETE" configuration option.
|===

<<Table of Contents,Back to TOC>>

=== ExposeExternallyType

ExposeExternallyType describes how Hazelcast members are exposed.

[cols="5,10"options="header"]
|===
| Value | Description
m| "Smart" | ExposeExternallyTypeSmart exposes each Hazelcast member with a separate external address.
m| "Unisocket" | ExposeExternallyTypeUnisocket exposes all Hazelcast members with one external address.
|===

<<Table of Contents,Back to TOC>>

=== MemberAccess

MemberAccess describes how each Hazelcast member is accessed from the external client.

[cols="5,10"options="header"]
|===
| Value | Description
m| "NodePortExternalIP" | MemberAccessNodePortExternalIP lets the client access Hazelcast member with the NodePort service and the node external IP/hostname
m| "NodePortNodeName" | MemberAccessNodePortNodeName lets the client access Hazelcast member with the NodePort service and the node name
m| "LoadBalancer" | MemberAccessLoadBalancer lets the client access Hazelcast member with the LoadBalancer service
|===

<<Table of Contents,Back to TOC>>

=== Phase

Phase represents the current state of the cluster

[cols="5,10"options="header"]
|===
| Value | Description
m| "Running" | Running phase is the state when all the members of the cluster are successfully started
m| "Failed" | Failed phase is the state of error during the cluster startup
m| "Pending" | Pending phase is the state of starting the cluster when not all the members are started yet
|===

<<Table of Contents,Back to TOC>>

=== RestoreState



[cols="5,10"options="header"]
|===
| Value | Description
m| "Unknown" | &#160;
m| "Failed" | &#160;
m| "InProgress" | &#160;
m| "Succeeded" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== ExternalConnectivityType

ExternalConnectivityType describes how Management Center is exposed.

[cols="5,10"options="header"]
|===
| Value | Description
m| "ClusterIP" | ExternalConnectivityTypeClusterIP exposes Management Center with ClusterIP service.
m| "NodePort" | ExternalConnectivityTypeNodePort exposes Management Center with NodePort service.
m| "LoadBalancer" | ExternalConnectivityTypeLoadBalancer exposes Management Center with LoadBalancer service.
|===

<<Table of Contents,Back to TOC>>

=== HotBackupState



[cols="5,10"options="header"]
|===
| Value | Description
m| "Unknown" | &#160;
m| "Pending" | &#160;
m| "NotStarted" | &#160;
m| "InProgress" | &#160;
m| "Failure" | &#160;
m| "Success" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== IndexType



[cols="5,10"options="header"]
|===
| Value | Description
m| "SORTED" | &#160;
m| "HASH" | &#160;
m| "BITMAP" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== MapConfigState



[cols="5,10"options="header"]
|===
| Value | Description
m| "Failed" | &#160;
m| "Success" | &#160;
m| "Pending" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== UniqueKeyTransition



[cols="5,10"options="header"]
|===
| Value | Description
m| "OBJECT" | &#160;
m| "LONG" | &#160;
m| "RAW" | &#160;
|===

<<Table of Contents,Back to TOC>>
