
= Hazelcast Platform Operator API Docs

A reference guide to the Hazelcast Platform Operator CRD types.

== Hazelcast Platform Operator API Docs

This is a reference for the Hazelcast Platform Operator API types.
These are all the types and fields that are used in the Hazelcast Platform Operator CRDs. 

TIP: This document was generated from comments in the Go code in the api/ directory.

=== Table of Contents
* <<AcknowledgementSetting,AcknowledgementSetting>>
* <<AcknowledgementType,AcknowledgementType>>
* <<AdvancedNetwork,AdvancedNetwork>>
* <<AgentConfiguration,AgentConfiguration>>
* <<BatchSetting,BatchSetting>>
* <<BitmapIndexOptionsConfig,BitmapIndexOptionsConfig>>
* <<BucketConfiguration,BucketConfiguration>>
* <<ByteOrder,ByteOrder>>
* <<CRLister,CRLister>>
* <<Cache,Cache>>
* <<CacheList,CacheList>>
* <<CacheSpec,CacheSpec>>
* <<CacheStatus,CacheStatus>>
* <<CapacityPolicyType,CapacityPolicyType>>
* <<ClientServerSocketEndpointConfig,ClientServerSocketEndpointConfig>>
* <<CollectionType,CollectionType>>
* <<CompactSerializationConfig,CompactSerializationConfig>>
* <<CronHotBackup,CronHotBackup>>
* <<CronHotBackupList,CronHotBackupList>>
* <<CronHotBackupSpec,CronHotBackupSpec>>
* <<CronHotBackupStatus,CronHotBackupStatus>>
* <<DataRecoveryPolicyType,DataRecoveryPolicyType>>
* <<DataStructure,DataStructure>>
* <<DataStructureConfigState,DataStructureConfigState>>
* <<DataStructureSpec,DataStructureSpec>>
* <<DataStructureStatus,DataStructureStatus>>
* <<DurableExecutorServiceConfiguration,DurableExecutorServiceConfiguration>>
* <<EntryListenerConfiguration,EntryListenerConfiguration>>
* <<EventJournal,EventJournal>>
* <<EvictionConfig,EvictionConfig>>
* <<EvictionPolicyType,EvictionPolicyType>>
* <<ExecutorServiceConfiguration,ExecutorServiceConfiguration>>
* <<ExposeExternallyConfiguration,ExposeExternallyConfiguration>>
* <<ExposeExternallyType,ExposeExternallyType>>
* <<ExternalConnectivityConfiguration,ExternalConnectivityConfiguration>>
* <<ExternalConnectivityIngress,ExternalConnectivityIngress>>
* <<ExternalConnectivityRoute,ExternalConnectivityRoute>>
* <<ExternalConnectivityType,ExternalConnectivityType>>
* <<FullBehaviorSetting,FullBehaviorSetting>>
* <<GCType,GCType>>
* <<GlobalSerializer,GlobalSerializer>>
* <<Hazelcast,Hazelcast>>
* <<HazelcastClusterConfig,HazelcastClusterConfig>>
* <<HazelcastClusterStatus,HazelcastClusterStatus>>
* <<HazelcastList,HazelcastList>>
* <<HazelcastMemberStatus,HazelcastMemberStatus>>
* <<HazelcastPersistenceConfiguration,HazelcastPersistenceConfiguration>>
* <<HazelcastSpec,HazelcastSpec>>
* <<HazelcastStatus,HazelcastStatus>>
* <<HighAvailabilityMode,HighAvailabilityMode>>
* <<HotBackup,HotBackup>>
* <<HotBackupList,HotBackupList>>
* <<HotBackupSpec,HotBackupSpec>>
* <<HotBackupState,HotBackupState>>
* <<HotBackupStatus,HotBackupStatus>>
* <<HotBackupTemplateSpec,HotBackupTemplateSpec>>
* <<InMemoryFormatType,InMemoryFormatType>>
* <<IndexConfig,IndexConfig>>
* <<IndexType,IndexType>>
* <<InitialModeType,InitialModeType>>
* <<JVMConfiguration,JVMConfiguration>>
* <<JVMGCConfiguration,JVMGCConfiguration>>
* <<JVMMemoryConfiguration,JVMMemoryConfiguration>>
* <<JavaSerializationFilter,JavaSerializationFilter>>
* <<JetEdgeDefaults,JetEdgeDefaults>>
* <<JetEngineConfiguration,JetEngineConfiguration>>
* <<JetInstance,JetInstance>>
* <<JetJob,JetJob>>
* <<JetJobList,JetJobList>>
* <<JetJobSnapshot,JetJobSnapshot>>
* <<JetJobSnapshotList,JetJobSnapshotList>>
* <<JetJobSnapshotSpec,JetJobSnapshotSpec>>
* <<JetJobSnapshotState,JetJobSnapshotState>>
* <<JetJobSnapshotStatus,JetJobSnapshotStatus>>
* <<JetJobSpec,JetJobSpec>>
* <<JetJobState,JetJobState>>
* <<JetJobStatus,JetJobStatus>>
* <<JetJobStatusPhase,JetJobStatusPhase>>
* <<JetRemoteFileConfiguration,JetRemoteFileConfiguration>>
* <<LoggingLevel,LoggingLevel>>
* <<MCPersistenceConfiguration,MCPersistenceConfiguration>>
* <<ManagementCenter,ManagementCenter>>
* <<ManagementCenterConfig,ManagementCenterConfig>>
* <<ManagementCenterList,ManagementCenterList>>
* <<ManagementCenterSpec,ManagementCenterSpec>>
* <<ManagementCenterStatus,ManagementCenterStatus>>
* <<Map,Map>>
* <<MapConfigState,MapConfigState>>
* <<MapList,MapList>>
* <<MapSpec,MapSpec>>
* <<MapStatus,MapStatus>>
* <<MapStoreConfig,MapStoreConfig>>
* <<MaxSizePolicyType,MaxSizePolicyType>>
* <<MemberAccess,MemberAccess>>
* <<MemberServerSocketEndpointConfig,MemberServerSocketEndpointConfig>>
* <<MultiMap,MultiMap>>
* <<MultiMapList,MultiMapList>>
* <<MultiMapSpec,MultiMapSpec>>
* <<MultiMapStatus,MultiMapStatus>>
* <<MutualAuthentication,MutualAuthentication>>
* <<NativeMemoryAllocatorType,NativeMemoryAllocatorType>>
* <<NativeMemoryConfiguration,NativeMemoryConfiguration>>
* <<NearCache,NearCache>>
* <<NearCacheEviction,NearCacheEviction>>
* <<NodeState,NodeState>>
* <<PersistencePvcConfiguration,PersistencePvcConfiguration>>
* <<PersistenceStartupAction,PersistenceStartupAction>>
* <<Phase,Phase>>
* <<Queue,Queue>>
* <<QueueList,QueueList>>
* <<QueueSetting,QueueSetting>>
* <<QueueSpec,QueueSpec>>
* <<QueueStatus,QueueStatus>>
* <<RMInMemoryFormatType,RMInMemoryFormatType>>
* <<RemoteFileConfiguration,RemoteFileConfiguration>>
* <<ReplicatedMap,ReplicatedMap>>
* <<ReplicatedMapList,ReplicatedMapList>>
* <<ReplicatedMapSpec,ReplicatedMapSpec>>
* <<ReplicatedMapStatus,ReplicatedMapStatus>>
* <<ResourceKind,ResourceKind>>
* <<ResourceSpec,ResourceSpec>>
* <<RestoreConfiguration,RestoreConfiguration>>
* <<RestoreState,RestoreState>>
* <<RestoreStatus,RestoreStatus>>
* <<ScheduledExecutorServiceConfiguration,ScheduledExecutorServiceConfiguration>>
* <<SchedulingConfiguration,SchedulingConfiguration>>
* <<SerializationConfig,SerializationConfig>>
* <<SerializationFilterList,SerializationFilterList>>
* <<Serializer,Serializer>>
* <<TLS,TLS>>
* <<Topic,Topic>>
* <<TopicList,TopicList>>
* <<TopicSpec,TopicSpec>>
* <<TopicStatus,TopicStatus>>
* <<UniqueKeyTransition,UniqueKeyTransition>>
* <<UserCodeDeploymentConfig,UserCodeDeploymentConfig>>
* <<WANConfig,WANConfig>>
* <<WanReplication,WanReplication>>
* <<WanReplicationList,WanReplicationList>>
* <<WanReplicationMapStatus,WanReplicationMapStatus>>
* <<WanReplicationSpec,WanReplicationSpec>>
* <<WanReplicationStatus,WanReplicationStatus>>
* <<WanStatus,WanStatus>>

=== AcknowledgementSetting



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| type | Type represents how a batch of replication events is considered successfully replicated. m| <<AcknowledgementType,AcknowledgementType>> | false | ACK_ON_OPERATION_COMPLETE
m| timeout | Timeout represents the time in milliseconds the source cluster waits for the acknowledgement. After timeout, the events will be resent. m| int32 | false | 60000
|===

<<Table of Contents,Back to TOC>>

=== AdvancedNetwork



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| memberServerSocketEndpointConfig | &#160; m| <<MemberServerSocketEndpointConfig,MemberServerSocketEndpointConfig>> | false | -
m| wan | &#160; m| []<<WANConfig,WANConfig>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== AgentConfiguration



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| repository | Repository to pull Hazelcast Platform Operator Agent(https://github.com/hazelcast/platform-operator-agent) m| string | false | "docker.io/hazelcast/platform-operator-agent"
m| version | Version of Hazelcast Platform Operator Agent. m| string | false | "0.1.20"
|===

<<Table of Contents,Back to TOC>>

=== BatchSetting



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| size | Size represents the maximum batch size. m| int32 | false | 500
m| maximumDelay | MaximumDelay represents the maximum delay in milliseconds. If the batch size is not reached, the events will be sent after the maximum delay. m| int32 | false | 1000
|===

<<Table of Contents,Back to TOC>>

=== BitmapIndexOptionsConfig



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| uniqueKey | &#160; m| string | true | -
m| uniqueKeyTransition | &#160; m| <<UniqueKeyTransition,UniqueKeyTransition>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== BucketConfiguration



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| secretName | Name of the secret with credentials for cloud providers. m| string | false | -
m| bucketURI | URL of the bucket to download HotBackup folders. AWS S3, GCP Bucket and Azure Blob storage buckets are supported. Example bucket URIs: - AWS S3     -> s3://bucket-name/path/to/folder - GCP Bucket -> gs://bucket-name/path/to/folder - Azure Blob -> azblob://bucket-name/path/to/folder m| string | true | -
|===
==== Deprecated
[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| secret | secret is a deprecated alias for secretName. m| string | false | -
|===

<<Table of Contents,Back to TOC>>

=== Cache

Cache is the Schema for the caches API

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#objectmeta-v1-meta[metav1.ObjectMeta] | false | -
m| spec | &#160; m| <<CacheSpec,CacheSpec>> | true | -
m| status | &#160; m| <<CacheStatus,CacheStatus>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== CacheList

CacheList contains a list of Cache

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#listmeta-v1-meta[metav1.ListMeta] | false | -
m| items | &#160; m| []<<Cache,Cache>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== CacheSpec

CacheSpec defines the desired state of Cache It cannot be updated after the Cache is created

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| name | Name of the data structure config to be created. If empty, CR name will be used. It cannot be updated after the config is created successfully. m| string | false | -
m| hazelcastResourceName | HazelcastResourceName defines the name of the Hazelcast resource that this resource is created for. m| string | true | -
m| backupCount | Number of synchronous backups. m| &#42;int32 | false | 1
m| asyncBackupCount | Number of asynchronous backups. m| int32 | false | 0
m| keyType | Class name of the key type m| string | false | -
m| valueType | Class name of the value type m| string | false | -
m| persistenceEnabled | When enabled, cache data will be persisted. m| bool | false | false
m| inMemoryFormat | InMemoryFormat specifies in which format data will be stored in your cache m| <<InMemoryFormatType,InMemoryFormatType>> | false | BINARY
m| eventJournal | EventJournal specifies event journal configuration of the Cache m| &#42;<<EventJournal,EventJournal>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== CacheStatus

CacheStatus defines the observed state of Cache

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| state | State of the data structure m| <<DataStructureConfigState,DataStructureConfigState>> | false | -
m| message | Message explaining the current state m| string | false | -
m| memberStatuses | Holds status of data structure for each Hazelcast member m| map[string]<<DataStructureConfigState,DataStructureConfigState>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== ClientServerSocketEndpointConfig



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| port | &#160; m| uint | false | -
m| interfaces | &#160; m| []string | false | -
|===

<<Table of Contents,Back to TOC>>

=== CompactSerializationConfig

CompactSerializationConfig is the configuration for the Hazelcast Compact serialization.

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| serializers | Serializers is the list of explicit serializers to be registered. m| []string | false | -
m| classes | Classes is the list of class names for which a zero-config serializer will be registered, without implementing an explicit serializer. m| []string | false | -
|===

<<Table of Contents,Back to TOC>>

=== CronHotBackup

CronHotBackup is the Schema for the cronhotbackups API

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#objectmeta-v1-meta[metav1.ObjectMeta] | false | -
m| spec | &#160; m| <<CronHotBackupSpec,CronHotBackupSpec>> | true | -
m| status | &#160; m| <<CronHotBackupStatus,CronHotBackupStatus>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== CronHotBackupList

CronHotBackupList contains a list of CronHotBackup

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#listmeta-v1-meta[metav1.ListMeta] | false | -
m| items | &#160; m| []<<CronHotBackup,CronHotBackup>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== CronHotBackupSpec

CronHotBackupSpec defines the desired state of CronHotBackup

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| schedule | Schedule contains a crontab-like expression that defines the schedule in which HotBackup will be started. If the Schedule is empty the HotBackup will start only once when applied. m| string | true | -
m| hotBackupTemplate | Specifies the hot backup that will be created when executing a CronHotBackup. m| <<HotBackupTemplateSpec,HotBackupTemplateSpec>> | true | -
m| successfulHotBackupsHistoryLimit | The number of successful finished hot backups to retain. m| &#42;int32 | false | 5
m| failedHotBackupsHistoryLimit | The number of failed finished hot backups to retain. m| &#42;int32 | false | 3
m| suspend | When true, CronHotBackup will stop creating HotBackup CRs until it is disabled m| bool | false | false
|===

<<Table of Contents,Back to TOC>>

=== AcknowledgementType



[cols="5,10"options="header"]
|===
| Value | Description
m| "ACK_ON_RECEIPT" | Replication event is considered successful as soon as it is received by target cluster.
m| "ACK_ON_OPERATION_COMPLETE" | Replication event is considered successful when it is received and applied by the target cluster.
|===

<<Table of Contents,Back to TOC>>

=== ByteOrder



[cols="5,10"options="header"]
|===
| Value | Description
m| "Native" | NativeByteOrder uses the native byte order of the underlying platform.
m| "BigEndian" | BigEndian uses the big-endian byte order.
m| "LittleEndian" | LittleEndian uses the kittle-endian byte order.
|===

<<Table of Contents,Back to TOC>>

=== CapacityPolicyType

CapacityPolicyType represents the active policy types for the capacity setting

[cols="5,10"options="header"]
|===
| Value | Description
m| "PER_NODE" | CapacityPolicyPerNode is the policy for limiting the maximum number of tasks in each Hazelcast instance
m| "PER_PARTITION" | CapacityPolicyPerPartition is the policy for limiting the maximum number of tasks within each partition.
|===

<<Table of Contents,Back to TOC>>

=== CollectionType

CollectionType represents the value collection options for storing the data in the multiMap.

[cols="5,10"options="header"]
|===
| Value | Description
m| "SET" | &#160;
m| "LIST" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== DataRecoveryPolicyType

DataRecoveryPolicyType represents the options for data recovery policy when the whole cluster restarts.

[cols="5,10"options="header"]
|===
| Value | Description
m| "FullRecoveryOnly" | FullRecovery does not allow partial start of the cluster and corresponds to "cluster-data-recovery-policy.FULL_RECOVERY_ONLY" configuration option.
m| "PartialRecoveryMostRecent" | MostRecent allow partial start with the members that have most up-to-date partition table and corresponds to "cluster-data-recovery-policy.PARTIAL_RECOVERY_MOST_RECENT" configuration option.
m| "PartialRecoveryMostComplete" | MostComplete allow partial start with the members that have most complete partition table and corresponds to "cluster-data-recovery-policy.PARTIAL_RECOVERY_MOST_COMPLETE" configuration option.
|===

<<Table of Contents,Back to TOC>>

=== DataStructureConfigState



[cols="5,10"options="header"]
|===
| Value | Description
m| "Failed" | Data structure is not successfully applied.
m| "Success" | Data structure configuration is applied successfully.
m| "Pending" | Data structure configuration is being applied
m| "Persisting" | The config is added into all members but waiting for the config to be persisted into ConfigMap
m| "Terminating" | Data structure is marked to be deleted,
|===

<<Table of Contents,Back to TOC>>

=== EvictionPolicyType



[cols="5,10"options="header"]
|===
| Value | Description
m| "LRU" | Least recently used entries will be removed.
m| "LFU" | Least frequently used entries will be removed.
m| "NONE" | No eviction.
m| "RANDOM" | Randomly selected entries will be removed.
|===

<<Table of Contents,Back to TOC>>

=== ExposeExternallyType

ExposeExternallyType describes how Hazelcast members are exposed.

[cols="5,10"options="header"]
|===
| Value | Description
m| "Smart" | ExposeExternallyTypeSmart exposes each Hazelcast member with a separate external address.
m| "Unisocket" | ExposeExternallyTypeUnisocket exposes all Hazelcast members with one external address.
|===

<<Table of Contents,Back to TOC>>

=== ExternalConnectivityType

ExternalConnectivityType describes how Management Center is exposed.

[cols="5,10"options="header"]
|===
| Value | Description
m| "ClusterIP" | ExternalConnectivityTypeClusterIP exposes Management Center with ClusterIP service.
m| "NodePort" | ExternalConnectivityTypeNodePort exposes Management Center with NodePort service.
m| "LoadBalancer" | ExternalConnectivityTypeLoadBalancer exposes Management Center with LoadBalancer service.
|===

<<Table of Contents,Back to TOC>>

=== FullBehaviorSetting



[cols="5,10"options="header"]
|===
| Value | Description
m| "DISCARD_AFTER_MUTATION" | &#160;
m| "THROW_EXCEPTION" | &#160;
m| "THROW_EXCEPTION_ONLY_IF_REPLICATION_ACTIVE" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== GCType

GCType is Garbage Collector type

[cols="5,10"options="header"]
|===
| Value | Description
m| "Serial" | &#160;
m| "Parallel" | &#160;
m| "G1" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== HighAvailabilityMode



[cols="5,10"options="header"]
|===
| Value | Description
m| "NODE" | &#160;
m| "ZONE" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== HotBackupState



[cols="5,10"options="header"]
|===
| Value | Description
m| "Unknown" | &#160;
m| "Pending" | &#160;
m| "NotStarted" | &#160;
m| "InProgress" | &#160;
m| "Failure" | &#160;
m| "Success" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== InMemoryFormatType

InMemoryFormatType represents the format options for storing the data in the map/cache.

[cols="5,10"options="header"]
|===
| Value | Description
m| "BINARY" | InMemoryFormatBinary Data will be stored in serialized binary format.
m| "OBJECT" | InMemoryFormatObject Data will be stored in deserialized form.
m| "NATIVE" | InMemoryFormatNative Data will be stored in the map that uses Hazelcast's High-Density Memory Store feature.
|===

<<Table of Contents,Back to TOC>>

=== IndexType



[cols="5,10"options="header"]
|===
| Value | Description
m| "SORTED" | &#160;
m| "HASH" | &#160;
m| "BITMAP" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== InitialModeType



[cols="5,10"options="header"]
|===
| Value | Description
m| "LAZY" | Loading is asynchronous. It is the default mode.
m| "EAGER" | Loading is blocked until all partitions are loaded.
|===

<<Table of Contents,Back to TOC>>

=== JetJobSnapshotState



[cols="5,10"options="header"]
|===
| Value | Description
m| "Waiting" | &#160;
m| "Exporting" | &#160;
m| "Exported" | &#160;
m| "Failed" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== JetJobState



[cols="5,10"options="header"]
|===
| Value | Description
m| "Running" | &#160;
m| "Suspended" | &#160;
m| "Canceled" | &#160;
m| "Restarted" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== JetJobStatusPhase



[cols="5,10"options="header"]
|===
| Value | Description
m| "Failed" | &#160;
m| "NotRunning" | &#160;
m| "Starting" | &#160;
m| "Running" | &#160;
m| "Suspended" | &#160;
m| "SuspendedExportingSnapshot" | &#160;
m| "Completing" | &#160;
m| "ExecutionFailed" | &#160;
m| "Completed" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== LoggingLevel

LoggingLevel controls log verbosity for Hazelcast.

[cols="5,10"options="header"]
|===
| Value | Description
m| "OFF" | &#160;
m| "FATAL" | &#160;
m| "ERROR" | &#160;
m| "WARN" | &#160;
m| "INFO" | &#160;
m| "DEBUG" | &#160;
m| "TRACE" | &#160;
m| "ALL" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== MapConfigState



[cols="5,10"options="header"]
|===
| Value | Description
m| "Failed" | &#160;
m| "Success" | &#160;
m| "Pending" | &#160;
m| "Persisting" | Map config is added into all members but waiting for map to be persistent into ConfigMap
m| "Terminating" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== MaxSizePolicyType



[cols="5,10"options="header"]
|===
| Value | Description
m| "PER_NODE" | Maximum number of map entries in each cluster member. You cannot set the max-size to a value lower than the partition count (which is 271 by default).
m| "PER_PARTITION" | Maximum number of map entries within each partition.
m| "USED_HEAP_PERCENTAGE" | Maximum used heap size percentage per map for each Hazelcast instance. If, for example, JVM is configured to have 1000 MB and this value is 10, then the map entries will be evicted when used heap size exceeds 100 MB. It does not work when "in-memory-format" is set to OBJECT.
m| "USED_HEAP_SIZE" | Maximum used heap size in megabytes per map for each Hazelcast instance. It does not work when "in-memory-format" is set to OBJECT.
m| "FREE_HEAP_PERCENTAGE" | Minimum free heap size percentage for each Hazelcast instance. If, for example, JVM is configured to have 1000 MB and this value is 10, then the map entries will be evicted when free heap size is below 100 MB.
m| "FREE_HEAP_SIZE" | Minimum free heap size in megabytes for each Hazelcast instance.
m| "USED_NATIVE_MEMORY_SIZE" | Maximum used native memory size in megabytes per map for each Hazelcast instance. It is available only in Hazelcast Enterprise HD.
m| "USED_NATIVE_MEMORY_PERCENTAGE" | Maximum used native memory size percentage per map for each Hazelcast instance. It is available only in Hazelcast Enterprise HD.
m| "FREE_NATIVE_MEMORY_SIZE" | Minimum free native memory size in megabytes for each Hazelcast instance. It is available only in Hazelcast Enterprise HD.
m| "FREE_NATIVE_MEMORY_PERCENTAGE" | Minimum free native memory size percentage for each Hazelcast instance. It is available only in Hazelcast Enterprise HD.
m| "ENTRY_COUNT" | Maximum size based on the entry count in the Near Cache Warning: This policy is specific to near cache.
|===

<<Table of Contents,Back to TOC>>

=== MemberAccess

MemberAccess describes how each Hazelcast member is accessed from the external client.

[cols="5,10"options="header"]
|===
| Value | Description
m| "NodePortExternalIP" | MemberAccessNodePortExternalIP lets the client access Hazelcast member with the NodePort service and the node external IP/hostname
m| "NodePortNodeName" | MemberAccessNodePortNodeName lets the client access Hazelcast member with the NodePort service and the node name
m| "LoadBalancer" | MemberAccessLoadBalancer lets the client access Hazelcast member with the LoadBalancer service
|===

<<Table of Contents,Back to TOC>>

=== MutualAuthentication



[cols="5,10"options="header"]
|===
| Value | Description
m| "None" | Client side of connection is not authenticated.
m| "Required" | Server asks for client certificate. If the client does not provide a keystore or the provided keystore is not verified against member’s truststore, the client is not authenticated.
m| "Optional" | Server asks for client certificate, but client is not required to provide any valid certificate.
|===

<<Table of Contents,Back to TOC>>

=== NativeMemoryAllocatorType

NativeMemoryAllocatorType is one of 2 types of mechanism for allocating HD Memory

[cols="5,10"options="header"]
|===
| Value | Description
m| "STANDARD" | NativeMemoryStandard allocate memory using default OS memory manager
m| "POOLED" | NativeMemoryPooled is Hazelcast own pooling memory allocator
|===

<<Table of Contents,Back to TOC>>

=== NodeState



[cols="5,10"options="header"]
|===
| Value | Description
m| "PASSIVE" | &#160;
m| "ACTIVE" | &#160;
m| "SHUT_DOWN" | &#160;
m| "STARTING" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== PersistenceStartupAction

PersistenceStartupAction represents the action triggered on the cluster startup to force the cluster startup.

[cols="5,10"options="header"]
|===
| Value | Description
m| "ForceStart" | ForceStart will trigger the force start action on the startup
m| "PartialStart" | PartialStart will trigger the partial start action on the startup. Can be used only with the MostComplete or MostRecent DataRecoveryPolicyType type.
|===

<<Table of Contents,Back to TOC>>

=== Phase

Phase represents the current state of the cluster

[cols="5,10"options="header"]
|===
| Value | Description
m| "Running" | Running phase is the state when all the members of the cluster are successfully started
m| "Failed" | Failed phase is the state of error during the cluster startup
m| "Pending" | Pending phase is the state of starting the cluster when not all the members are started yet
m| "Terminating" | Terminating phase is the state where deletion of cluster scoped resources and Hazelcast dependent resources happen
|===

<<Table of Contents,Back to TOC>>

=== RMInMemoryFormatType

RMInMemoryFormatType represents the format options for storing the data in the ReplicatedMap.

[cols="5,10"options="header"]
|===
| Value | Description
m| "BINARY" | RMInMemoryFormatBinary Data will be stored in serialized binary format.
m| "OBJECT" | RMInMemoryFormatObject Data will be stored in deserialized form.
|===

<<Table of Contents,Back to TOC>>

=== ResourceKind



[cols="5,10"options="header"]
|===
| Value | Description
m| "Map" | &#160;
m| "Hazelcast" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== RestoreState



[cols="5,10"options="header"]
|===
| Value | Description
m| "Unknown" | &#160;
m| "Failed" | &#160;
m| "InProgress" | &#160;
m| "Succeeded" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== UniqueKeyTransition



[cols="5,10"options="header"]
|===
| Value | Description
m| "OBJECT" | &#160;
m| "LONG" | &#160;
m| "RAW" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== WanStatus



[cols="5,10"options="header"]
|===
| Value | Description
m| "Failed" | &#160;
m| "Pending" | &#160;
m| "Success" | &#160;
m| "Persisting" | The config is added into all members but waiting for the config to be persisted into ConfigMap
m| "Terminating" | &#160;
|===

<<Table of Contents,Back to TOC>>
