
= Hazelcast Platform Operator API Docs

A reference guide to the Hazelcast Platform Operator CRD types.

== Hazelcast Platform Operator API Docs

This is a reference for the Hazelcast Platform Operator API types.
These are all the types and fields that are used in the Hazelcast Platform Operator CRDs. 

TIP: This document was generated from comments in the Go code in the api/ directory.

=== Table of Contents
* <<AcknowledgementSetting,AcknowledgementSetting>>
* <<AcknowledgementType,AcknowledgementType>>
* <<AgentConfiguration,AgentConfiguration>>
* <<BackupType,BackupType>>
* <<BatchSetting,BatchSetting>>
* <<BitmapIndexOptionsConfig,BitmapIndexOptionsConfig>>
* <<BucketConfiguration,BucketConfiguration>>
* <<Cache,Cache>>
* <<CacheList,CacheList>>
* <<CacheSpec,CacheSpec>>
* <<CacheStatus,CacheStatus>>
* <<CapacityPolicyType,CapacityPolicyType>>
* <<CollectionType,CollectionType>>
* <<CronHotBackup,CronHotBackup>>
* <<CronHotBackupList,CronHotBackupList>>
* <<CronHotBackupSpec,CronHotBackupSpec>>
* <<CronHotBackupStatus,CronHotBackupStatus>>
* <<DataRecoveryPolicyType,DataRecoveryPolicyType>>
* <<DataStructureConfigState,DataStructureConfigState>>
* <<DataStructureSpec,DataStructureSpec>>
* <<DataStructureStatus,DataStructureStatus>>
* <<DurableExecutorServiceConfiguration,DurableExecutorServiceConfiguration>>
* <<EntryListenerConfiguration,EntryListenerConfiguration>>
* <<EvictionConfig,EvictionConfig>>
* <<EvictionPolicyType,EvictionPolicyType>>
* <<ExecutorServiceConfiguration,ExecutorServiceConfiguration>>
* <<ExposeExternallyConfiguration,ExposeExternallyConfiguration>>
* <<ExposeExternallyType,ExposeExternallyType>>
* <<ExternalConnectivityConfiguration,ExternalConnectivityConfiguration>>
* <<ExternalConnectivityType,ExternalConnectivityType>>
* <<FullBehaviorSetting,FullBehaviorSetting>>
* <<Hazelcast,Hazelcast>>
* <<HazelcastClusterConfig,HazelcastClusterConfig>>
* <<HazelcastClusterStatus,HazelcastClusterStatus>>
* <<HazelcastList,HazelcastList>>
* <<HazelcastMemberStatus,HazelcastMemberStatus>>
* <<HazelcastPersistenceConfiguration,HazelcastPersistenceConfiguration>>
* <<HazelcastSpec,HazelcastSpec>>
* <<HazelcastStatus,HazelcastStatus>>
* <<HotBackup,HotBackup>>
* <<HotBackupList,HotBackupList>>
* <<HotBackupSpec,HotBackupSpec>>
* <<HotBackupState,HotBackupState>>
* <<HotBackupStatus,HotBackupStatus>>
* <<HotBackupTemplateSpec,HotBackupTemplateSpec>>
* <<InMemoryFormatType,InMemoryFormatType>>
* <<IndexConfig,IndexConfig>>
* <<IndexType,IndexType>>
* <<InitialModeType,InitialModeType>>
* <<JetEngineConfiguration,JetEngineConfiguration>>
* <<LoggingLevel,LoggingLevel>>
* <<ManagementCenter,ManagementCenter>>
* <<ManagementCenterList,ManagementCenterList>>
* <<ManagementCenterSpec,ManagementCenterSpec>>
* <<ManagementCenterStatus,ManagementCenterStatus>>
* <<Map,Map>>
* <<MapConfigState,MapConfigState>>
* <<MapList,MapList>>
* <<MapSpec,MapSpec>>
* <<MapStatus,MapStatus>>
* <<MapStoreConfig,MapStoreConfig>>
* <<MaxSizePolicyType,MaxSizePolicyType>>
* <<MemberAccess,MemberAccess>>
* <<MultiMap,MultiMap>>
* <<MultiMapList,MultiMapList>>
* <<MultiMapSpec,MultiMapSpec>>
* <<MultiMapStatus,MultiMapStatus>>
* <<NodeState,NodeState>>
* <<PersistenceConfiguration,PersistenceConfiguration>>
* <<PersistencePvcConfiguration,PersistencePvcConfiguration>>
* <<Phase,Phase>>
* <<Queue,Queue>>
* <<QueueList,QueueList>>
* <<QueueSetting,QueueSetting>>
* <<QueueSpec,QueueSpec>>
* <<QueueStatus,QueueStatus>>
* <<ReplicatedMap,ReplicatedMap>>
* <<ReplicatedMapList,ReplicatedMapList>>
* <<ReplicatedMapSpec,ReplicatedMapSpec>>
* <<ReplicatedMapStatus,ReplicatedMapStatus>>
* <<ResourceKind,ResourceKind>>
* <<ResourceSpec,ResourceSpec>>
* <<RestoreConfiguration,RestoreConfiguration>>
* <<RestoreState,RestoreState>>
* <<RestoreStatus,RestoreStatus>>
* <<ScheduledExecutorServiceConfiguration,ScheduledExecutorServiceConfiguration>>
* <<SchedulingConfiguration,SchedulingConfiguration>>
* <<Topic,Topic>>
* <<TopicList,TopicList>>
* <<TopicSpec,TopicSpec>>
* <<TopicStatus,TopicStatus>>
* <<UniqueKeyTransition,UniqueKeyTransition>>
* <<UserCodeDeploymentConfig,UserCodeDeploymentConfig>>
* <<WanReplication,WanReplication>>
* <<WanReplicationList,WanReplicationList>>
* <<WanReplicationMapStatus,WanReplicationMapStatus>>
* <<WanReplicationSpec,WanReplicationSpec>>
* <<WanReplicationStatus,WanReplicationStatus>>
* <<WanStatus,WanStatus>>

=== AcknowledgementSetting



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| type | Type represents how a batch of replication events is considered successfully replicated. m| <<AcknowledgementType,AcknowledgementType>> | false | ACK_ON_OPERATION_COMPLETE
m| timeout | Timeout represents the time the source cluster waits for the acknowledgement. After timeout, the events will be resent. m| int32 | false | 60000
|===

<<Table of Contents,Back to TOC>>

=== AgentConfiguration



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| repository | Repository to pull Hazelcast Platform Operator Agent(https://github.com/hazelcast/platform-operator-agent) m| string | false | "docker.io/hazelcast/platform-operator-agent"
m| version | Version of Hazelcast Platform Operator Agent. m| string | false | "0.1.10"
|===

<<Table of Contents,Back to TOC>>

=== BatchSetting



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| size | Size represents the maximum batch size. m| int32 | false | 500
m| maximumDelay | MaximumDelay represents the maximum delay in milliseconds. If the batch size is not reached, the events will be sent after the maximum delay. m| int32 | false | 1000
|===

<<Table of Contents,Back to TOC>>

=== BitmapIndexOptionsConfig



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| uniqueKey | &#160; m| string | true | -
m| uniqueKeyTransition | &#160; m| <<UniqueKeyTransition,UniqueKeyTransition>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== BucketConfiguration



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| secret | Name of the secret with credentials for cloud providers. m| string | true | -
m| bucketURI | Full path to blob storage bucket. m| string | true | -
|===

<<Table of Contents,Back to TOC>>

=== Cache

Cache is the Schema for the caches API

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#objectmeta-v1-meta[metav1.ObjectMeta] | false | -
m| spec | &#160; m| <<CacheSpec,CacheSpec>> | false | -
m| status | &#160; m| <<CacheStatus,CacheStatus>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== CacheList

CacheList contains a list of Cache

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#listmeta-v1-meta[metav1.ListMeta] | false | -
m| items | &#160; m| []<<Cache,Cache>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== CacheSpec

CacheSpec defines the desired state of Cache It cannot be updated after the Cache is created

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| name | Name of the data structure config to be created. If empty, CR name will be used. It cannot be updated after the config is created successfully. m| string | false | -
m| hazelcastResourceName | HazelcastResourceName defines the name of the Hazelcast resource. m| string | true | -
m| backupCount | Number of synchronous backups. m| &#42;int32 | false | 1
m| asyncBackupCount | Number of asynchronous backups. m| &#42;int32 | false | 0
m| keyType | Class name of the key type m| string | false | -
m| valueType | Class name of the value type m| string | false | -
m| persistenceEnabled | When enabled, cache data will be persisted. m| bool | false | false
|===

<<Table of Contents,Back to TOC>>

=== CacheStatus

CacheStatus defines the observed state of Cache

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| state | &#160; m| <<DataStructureConfigState,DataStructureConfigState>> | false | -
m| message | &#160; m| string | false | -
m| memberStatuses | &#160; m| map[string]<<DataStructureConfigState,DataStructureConfigState>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== CronHotBackup

CronHotBackup is the Schema for the cronhotbackups API

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#objectmeta-v1-meta[metav1.ObjectMeta] | false | -
m| spec | &#160; m| <<CronHotBackupSpec,CronHotBackupSpec>> | true | -
m| status | &#160; m| <<CronHotBackupStatus,CronHotBackupStatus>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== CronHotBackupList

CronHotBackupList contains a list of CronHotBackup

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#listmeta-v1-meta[metav1.ListMeta] | false | -
m| items | &#160; m| []<<CronHotBackup,CronHotBackup>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== CronHotBackupSpec

CronHotBackupSpec defines the desired state of CronHotBackup

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| schedule | Schedule contains a crontab-like expression that defines the schedule in which HotBackup will be started. If the Schedule is empty the HotBackup will start only once when applied. m| string | true | -
m| hotBackupTemplate | Specifies the hot backup that will be created when executing a CronHotBackup. m| <<HotBackupTemplateSpec,HotBackupTemplateSpec>> | true | -
m| successfulHotBackupsHistoryLimit | The number of successful finished hot backups to retain. This is a pointer to distinguish between explicit zero and not specified. m| &#42;int32 | false | 5
m| failedHotBackupsHistoryLimit | The number of failed finished hot backups to retain. This is a pointer to distinguish between explicit zero and not specified. m| &#42;int32 | false | 3
m| suspend | When true, CronHotBackup will stop creating HotBackup CRs until it is disabled m| bool | false | false
|===

<<Table of Contents,Back to TOC>>

=== DataStructureSpec



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| name | Name of the data structure config to be created. If empty, CR name will be used. It cannot be updated after the config is created successfully. m| string | false | -
m| hazelcastResourceName | HazelcastResourceName defines the name of the Hazelcast resource. m| string | true | -
m| backupCount | Number of synchronous backups. m| &#42;int32 | false | 1
m| asyncBackupCount | Number of asynchronous backups. m| &#42;int32 | false | 0
|===

<<Table of Contents,Back to TOC>>

=== DataStructureStatus



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| state | &#160; m| <<DataStructureConfigState,DataStructureConfigState>> | false | -
m| message | &#160; m| string | false | -
m| memberStatuses | &#160; m| map[string]<<DataStructureConfigState,DataStructureConfigState>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== DurableExecutorServiceConfiguration



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| name | The name of the executor service m| string | false | "default"
m| poolSize | The number of executor threads per member. m| int32 | false | 16
m| durability | Durability of the executor. m| int32 | false | 1
m| capacity | Capacity of the executor task per partition. m| int32 | false | 100
|===

<<Table of Contents,Back to TOC>>

=== EntryListenerConfiguration



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| className | ClassName is the fully qualified name of the class that implements any of the Listener interface. m| string | true | -
m| includeValues | IncludeValues is an optional attribute that indicates whether the event will contain the map value. Defaults to true. m| &#42;bool | false | true
m| local | Local is an optional attribute that indicates whether the map on the local member can be listened to. Defaults to false. m| bool | false | false
|===

<<Table of Contents,Back to TOC>>

=== EvictionConfig



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| evictionPolicy | Eviction policy to be applied when map reaches its max size according to the max size policy. m| <<EvictionPolicyType,EvictionPolicyType>> | false | "NONE"
m| maxSize | Max size of the map. m| &#42;int32 | false | 0
m| maxSizePolicy | Policy for deciding if the maxSize is reached. m| <<MaxSizePolicyType,MaxSizePolicyType>> | false | "PER_NODE"
|===

<<Table of Contents,Back to TOC>>

=== ExecutorServiceConfiguration



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| name | The name of the executor service m| string | false | "default"
m| poolSize | The number of executor threads per member. m| int32 | false | 8
m| queueCapacity | Task queue capacity of the executor. m| int32 | false | 0
|===

<<Table of Contents,Back to TOC>>

=== ExposeExternallyConfiguration

ExposeExternallyConfiguration defines how to expose Hazelcast cluster to external clients

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| type | Specifies how members are exposed. Valid values are: - "Smart" (default): each member pod is exposed with a separate external address - "Unisocket": all member pods are exposed with one external address m| <<ExposeExternallyType,ExposeExternallyType>> | false | "Smart"
m| discoveryServiceType | Type of the service used to discover Hazelcast cluster. m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#servicetype-v1-core[corev1.ServiceType] | false | "LoadBalancer"
m| memberAccess | How each member is accessed from the external client. Only available for "Smart" client and valid values are: - "NodePortExternalIP" (default): each member is accessed by the NodePort service and the node external IP/hostname - "NodePortNodeName": each member is accessed by the NodePort service and the node name - "LoadBalancer": each member is accessed by the LoadBalancer service external address m| <<MemberAccess,MemberAccess>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== ExternalConnectivityConfiguration

ExternalConnectivityConfiguration defines how to expose Management Center pod.

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| type | How Management Center is exposed. Valid values are: - "ClusterIP" - "NodePort" - "LoadBalancer" (default) m| <<ExternalConnectivityType,ExternalConnectivityType>> | false | "LoadBalancer"
|===

<<Table of Contents,Back to TOC>>

=== Hazelcast

Hazelcast is the Schema for the hazelcasts API

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#objectmeta-v1-meta[metav1.ObjectMeta] | false | -
m| spec | &#160; m| <<HazelcastSpec,HazelcastSpec>> | false | {"repository" : "docker.io/hazelcast/hazelcast"}
m| status | &#160; m| <<HazelcastStatus,HazelcastStatus>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== HazelcastClusterConfig



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| name | Name of the Hazelcast cluster that Management Center will connect to, default is dev. m| string | false | "dev"
m| address | IP address or DNS name of the Hazelcast cluster. If the cluster is exposed with a service name in a different namespace, use the following syntax "<service-name>.<service-namespace>". m| string | true | -
|===

<<Table of Contents,Back to TOC>>

=== HazelcastClusterStatus

HazelcastClusterStatus defines the status of the Hazelcast cluster

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| readyMembers | ReadyMembers represents the number of members that are connected to cluster from the desired number of members in the format <ready>/<desired> m| string | true | -
|===

<<Table of Contents,Back to TOC>>

=== HazelcastList

HazelcastList contains a list of Hazelcast

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#listmeta-v1-meta[metav1.ListMeta] | false | -
m| items | &#160; m| []<<Hazelcast,Hazelcast>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== HazelcastMemberStatus

HazelcastMemberStatus defines the observed state of the individual Hazelcast member.

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| podName | PodName is the name of the Hazelcast member pod. m| string | false | -
m| uid | Uid is the unique member identifier within the cluster. m| string | false | -
m| ip | Ip is the IP address of the member within the cluster. m| string | false | -
m| version | Version represents the Hazelcast version of the member. m| string | false | -
m| state | State represents the observed state of the member. m| <<NodeState,NodeState>> | false | -
m| master | Master flag is set to true if the member is master. m| bool | false | -
m| lite | Lite is the flag that is true when the member is lite-member. m| bool | false | -
m| ownedPartitions | OwnedPartitions represents the partitions count on the member. m| int32 | false | -
m| connected | Ready is the flag that is set to true when the member is successfully started, connected to cluster and ready to accept connections. m| bool | true | -
m| message | Message contains the optional message with the details of the cluster state. m| string | false | -
m| reason | Reason contains the optional reason of member crash or restart. m| string | false | -
m| restartCount | RestartCount is the number of times the member has been restarted. m| int32 | true | -
|===

<<Table of Contents,Back to TOC>>

=== HazelcastPersistenceConfiguration

HazelcastPersistenceConfiguration contains the configuration for Hazelcast Persistence and K8s storage.

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| baseDir | Persistence base directory. m| string | true | -
m| clusterDataRecoveryPolicy | Configuration of the cluster recovery strategy. m| <<DataRecoveryPolicyType,DataRecoveryPolicyType>> | false | "FullRecoveryOnly"
m| autoForceStart | AutoForceStart enables the detection of constantly failing cluster and trigger the Force Start action. m| bool | false | false
m| dataRecoveryTimeout | DataRecoveryTimeout is timeout for each step of data recovery in seconds. Maximum timeout is equal to DataRecoveryTimeout*2 (for each step: validation and data-load). m| int32 | false | -
m| pvc | Configuration of PersistenceVolumeClaim. m| <<PersistencePvcConfiguration,PersistencePvcConfiguration>> | false | -
m| hostPath | Host Path directory. m| string | false | -
m| restore | Restore configuration m| &#42;<<RestoreConfiguration,RestoreConfiguration>> | false | {}
|===

<<Table of Contents,Back to TOC>>

=== HazelcastSpec

HazelcastSpec defines the desired state of Hazelcast

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| clusterSize | Number of Hazelcast members in the cluster. m| &#42;int32 | false | 3
m| repository | Repository to pull the Hazelcast Platform image from. m| string | false | "docker.io/hazelcast/hazelcast"
m| version | Version of Hazelcast Platform. m| string | false | "5.2.1"
m| imagePullPolicy | Pull policy for the Hazelcast Platform image m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#pullpolicy-v1-core[corev1.PullPolicy] | false | "IfNotPresent"
m| imagePullSecrets | Image pull secrets for the Hazelcast Platform image m| []https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#localobjectreference-v1-core[corev1.LocalObjectReference] | false | -
m| licenseKeySecret | Name of the secret with Hazelcast Enterprise License Key. m| string | false | -
m| exposeExternally | Configuration to expose Hazelcast cluster to external clients. m| &#42;<<ExposeExternallyConfiguration,ExposeExternallyConfiguration>> | false | {}
m| clusterName | Name of the Hazelcast cluster. m| string | false | "dev"
m| scheduling | Scheduling details m| &#42;<<SchedulingConfiguration,SchedulingConfiguration>> | false | {}
m| resources | Compute Resources required by the Hazelcast container. m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#resourcerequirements-v1-core[corev1.ResourceRequirements] | false | {}
m| persistence | Persistence configuration m| &#42;<<HazelcastPersistenceConfiguration,HazelcastPersistenceConfiguration>> | false | {}
m| agent | B&R Agent configurations m| &#42;<<AgentConfiguration,AgentConfiguration>> | false | {repository: "docker.io/hazelcast/platform-operator-agent", version: "0.1.11"}
m| jet | Jet Engine configuration m| &#42;<<JetEngineConfiguration,JetEngineConfiguration>> | false | {enabled: true}
m| userCodeDeployment | User Codes to Download into CLASSPATH m| &#42;<<UserCodeDeploymentConfig,UserCodeDeploymentConfig>> | false | -
m| executorServices | &#160; m| []<<ExecutorServiceConfiguration,ExecutorServiceConfiguration>> | false | -
m| durableExecutorServices | &#160; m| []<<DurableExecutorServiceConfiguration,DurableExecutorServiceConfiguration>> | false | -
m| scheduledExecutorServices | &#160; m| []<<ScheduledExecutorServiceConfiguration,ScheduledExecutorServiceConfiguration>> | false | -
m| properties | &#160; m| map[string]string | false | -
m| loggingLevel | &#160; m| <<LoggingLevel,LoggingLevel>> | false | "INFO"
|===

<<Table of Contents,Back to TOC>>

=== HazelcastStatus

HazelcastStatus defines the observed state of Hazelcast

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| phase | Phase of the Hazelcast cluster m| <<Phase,Phase>> | false | -
m| hazelcastClusterStatus | Status of the Hazelcast cluster m| <<HazelcastClusterStatus,HazelcastClusterStatus>> | false | -
m| message | Message about the Hazelcast cluster state m| string | false | -
m| externalAddresses | External addresses of the Hazelcast cluster members m| string | false | -
m| members | Status of Hazelcast members m| []<<HazelcastMemberStatus,HazelcastMemberStatus>> | false | -
m| restore | Status of restore process of the Hazelcast cluster m| &#42;<<RestoreStatus,RestoreStatus>> | false | {}
|===

<<Table of Contents,Back to TOC>>

=== HotBackup

HotBackup is the Schema for the hot backup API

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#objectmeta-v1-meta[metav1.ObjectMeta] | false | -
m| status | &#160; m| <<HotBackupStatus,HotBackupStatus>> | false | -
m| spec | &#160; m| <<HotBackupSpec,HotBackupSpec>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== HotBackupList

HotBackupList contains a list of HotBackup

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#listmeta-v1-meta[metav1.ListMeta] | false | -
m| items | &#160; m| []<<HotBackup,HotBackup>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== HotBackupSpec

HotBackupSpec defines the Spec of HotBackup

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| hazelcastResourceName | HazelcastResourceName defines the name of the Hazelcast resource m| string | true | -
m| bucketURI | URL of the bucket to download HotBackup folders. m| string | false | -
m| secret | Name of the secret with credentials for cloud providers. m| string | false | -
|===

<<Table of Contents,Back to TOC>>

=== HotBackupStatus

HotBackupStatus defines the observed state of HotBackup

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| state | &#160; m| <<HotBackupState,HotBackupState>> | true | -
m| message | &#160; m| string | true | -
m| backupUUIDs | &#160; m| []string | false | -
|===

<<Table of Contents,Back to TOC>>

=== HotBackupTemplateSpec



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | Standard object's metadata of the hot backups created from this template. m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#objectmeta-v1-meta[metav1.ObjectMeta] | false | -
m| spec | Specification of the desired behavior of the hot backup. m| <<HotBackupSpec,HotBackupSpec>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== IndexConfig



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| name | Name of the index config. m| string | false | -
m| type | Type of the index. m| <<IndexType,IndexType>> | true | -
m| attributes | Attributes of the index. m| []string | true | -
m| bitMapIndexOptions | Options for "BITMAP" index type. m| &#42;<<BitmapIndexOptionsConfig,BitmapIndexOptionsConfig>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== JetEngineConfiguration



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| enabled | When false, disables Jet Engine. m| &#42;bool | false | true
m| resourceUploadEnabled | When true, enables resource uploading for Jet jobs. m| bool | false | false
|===

<<Table of Contents,Back to TOC>>

=== ManagementCenter

ManagementCenter is the Schema for the managementcenters API

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#objectmeta-v1-meta[metav1.ObjectMeta] | false | -
m| spec | &#160; m| <<ManagementCenterSpec,ManagementCenterSpec>> | false | {"repository" : "docker.io/hazelcast/management-center"}
m| status | &#160; m| <<ManagementCenterStatus,ManagementCenterStatus>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== ManagementCenterList

ManagementCenterList contains a list of ManagementCenter

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#listmeta-v1-meta[metav1.ListMeta] | false | -
m| items | &#160; m| []<<ManagementCenter,ManagementCenter>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== ManagementCenterSpec

ManagementCenterSpec defines the desired state of ManagementCenter.

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| repository | Repository to pull the Management Center image from. m| string | false | "docker.io/hazelcast/management-center"
m| version | Version of Management Center. m| string | false | "5.2.0"
m| imagePullPolicy | Pull policy for the Management Center image m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#pullpolicy-v1-core[corev1.PullPolicy] | false | "IfNotPresent"
m| imagePullSecrets | Image pull secrets for the Management Center image m| []https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#localobjectreference-v1-core[corev1.LocalObjectReference] | false | -
m| licenseKeySecret | Name of the secret with Hazelcast Enterprise License Key. m| string | false | -
m| hazelcastClusters | Connection configuration for the Hazelcast clusters that Management Center will monitor. m| []<<HazelcastClusterConfig,HazelcastClusterConfig>> | false | -
m| externalConnectivity | Configuration to expose Management Center to outside. m| &#42;<<ExternalConnectivityConfiguration,ExternalConnectivityConfiguration>> | false | {type: "LoadBalancer"}
m| persistence | Configuration for Management Center persistence. m| &#42;<<PersistenceConfiguration,PersistenceConfiguration>> | false | {enabled: true, size: "10Gi"}
m| scheduling | Scheduling details m| &#42;<<SchedulingConfiguration,SchedulingConfiguration>> | false | -
m| resources | Compute Resources required by the MC container. m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#resourcerequirements-v1-core[corev1.ResourceRequirements] | false | {}
|===

<<Table of Contents,Back to TOC>>

=== ManagementCenterStatus

ManagementCenterStatus defines the observed state of ManagementCenter.

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| phase | Phase of the Management Center m| <<Phase,Phase>> | false | -
m| message | Message about the Management Center state m| string | false | -
m| externalAddresses | External addresses of the Management Center instance m| string | false | -
|===

<<Table of Contents,Back to TOC>>

=== Map

Map is the Schema for the maps API

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#objectmeta-v1-meta[metav1.ObjectMeta] | false | -
m| spec | &#160; m| <<MapSpec,MapSpec>> | true | -
m| status | &#160; m| <<MapStatus,MapStatus>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== MapList

MapList contains a list of Map

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#listmeta-v1-meta[metav1.ListMeta] | false | -
m| items | &#160; m| []<<Map,Map>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== MapSpec

MapSpec defines the desired state of Hazelcast Map Config

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| name | Name of the data structure config to be created. If empty, CR name will be used. It cannot be updated after the config is created successfully. m| string | false | -
m| hazelcastResourceName | HazelcastResourceName defines the name of the Hazelcast resource. m| string | true | -
m| backupCount | Number of synchronous backups. m| &#42;int32 | false | 1
m| asyncBackupCount | Number of asynchronous backups. m| &#42;int32 | false | 0
m| timeToLiveSeconds | Maximum time in seconds for each entry to stay in the map. If it is not 0, entries that are older than this time and not updated for this time are evicted automatically. It can be updated. m| &#42;int32 | false | 0
m| maxIdleSeconds | Maximum time in seconds for each entry to stay idle in the map. Entries that are idle for more than this time are evicted automatically. It can be updated. m| &#42;int32 | false | 0
m| eviction | Configuration for removing data from the map when it reaches its max size. It can be updated. m| &#42;<<EvictionConfig,EvictionConfig>> | false | {maxSize: 0}
m| indexes | Indexes to be created for the map data. You can learn more at https://docs.hazelcast.com/hazelcast/latest/query/indexing-maps. It cannot be updated after map config is created successfully. m| []<<IndexConfig,IndexConfig>> | false | -
m| persistenceEnabled | When enabled, map data will be persisted. It cannot be updated after map config is created successfully. m| bool | false | false
m| mapStore | Configuration options when you want to load/store the map entries from/to a persistent data store such as a relational database You can learn more at https://docs.hazelcast.com/hazelcast/latest/data-structures/working-with-external-data m| &#42;<<MapStoreConfig,MapStoreConfig>> | false | -
m| inMemoryFormat | InMemoryFormat specifies in which format data will be stored in your map m| <<InMemoryFormatType,InMemoryFormatType>> | false | BINARY
m| entryListeners | EntryListeners contains the configuration for the map-level or entry-based events listeners provided by the Hazelcast’s eventing framework. You can learn more at https://docs.hazelcast.com/hazelcast/latest/events/object-events. m| []<<EntryListenerConfiguration,EntryListenerConfiguration>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== MapStatus

MapStatus defines the observed state of Map

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| state | &#160; m| <<MapConfigState,MapConfigState>> | false | -
m| message | &#160; m| string | false | -
m| memberStatuses | &#160; m| map[string]<<MapConfigState,MapConfigState>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== MapStoreConfig



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| initialMode | Sets the initial entry loading mode. m| <<InitialModeType,InitialModeType>> | false | LAZY
m| className | Name of your class implementing MapLoader and/or MapStore interface. m| string | true | -
m| writeDelaySeconds | Number of seconds to delay the storing of entries. m| int32 | false | -
m| writeBatchSize | Used to create batches when writing to map store. m| int32 | false | 1
m| writeCoealescing | It is meaningful if you are using write behind in MapStore. When it is set to true, only the latest store operation on a key during the write-delay-seconds will be reflected to MapStore. m| &#42;bool | false | true
m| propertiesSecretName | Properties can be used for giving information to the MapStore implementation m| string | false | -
|===

<<Table of Contents,Back to TOC>>

=== MultiMap

MultiMap is the Schema for the multimaps API

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#objectmeta-v1-meta[metav1.ObjectMeta] | false | -
m| spec | &#160; m| <<MultiMapSpec,MultiMapSpec>> | false | -
m| status | &#160; m| <<MultiMapStatus,MultiMapStatus>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== MultiMapList

MultiMapList contains a list of MultiMap

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#listmeta-v1-meta[metav1.ListMeta] | false | -
m| items | &#160; m| []<<MultiMap,MultiMap>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== MultiMapSpec

MultiMapSpec defines the desired state of MultiMap

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| name | Name of the data structure config to be created. If empty, CR name will be used. It cannot be updated after the config is created successfully. m| string | false | -
m| hazelcastResourceName | HazelcastResourceName defines the name of the Hazelcast resource. m| string | true | -
m| backupCount | Number of synchronous backups. m| &#42;int32 | false | 1
m| asyncBackupCount | Number of asynchronous backups. m| &#42;int32 | false | 0
m| binary | Specifies in which format data will be stored in your multiMap. false: OBJECT true: BINARY m| bool | false | false
m| collectionType | Type of the value collection m| <<CollectionType,CollectionType>> | false | SET
|===

<<Table of Contents,Back to TOC>>

=== MultiMapStatus

MultiMapStatus defines the observed state of MultiMap

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| state | &#160; m| <<DataStructureConfigState,DataStructureConfigState>> | false | -
m| message | &#160; m| string | false | -
m| memberStatuses | &#160; m| map[string]<<DataStructureConfigState,DataStructureConfigState>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== PersistenceConfiguration



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| enabled | When true, MC will use a PersistentVolumeClaim to store data. m| bool | false | true
m| existingVolumeClaimName | Name of the PersistentVolumeClaim MC will use for persistence. If not empty, MC will use the existing claim instead of creating a new one. m| string | false | -
m| storageClass | StorageClass from which PersistentVolumeClaim will be created. m| &#42;string | false | -
m| size | Size of the created PersistentVolumeClaim. m| &#42;resource.Quantity | false | "10Gi"
|===

<<Table of Contents,Back to TOC>>

=== PersistencePvcConfiguration



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| accessModes | AccessModes contains the actual access modes of the volume backing the PVC has. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1 m| []https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#persistentvolumeaccessmode-v1-core[corev1.PersistentVolumeAccessMode] | false | -
m| requestStorage | A description of the PVC request capacity. m| &#42;resource.Quantity | false | -
m| storageClassName | Name of StorageClass which this persistent volume belongs to. m| &#42;string | false | -
|===

<<Table of Contents,Back to TOC>>

=== Queue

Queue is the Schema for the queues API

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#objectmeta-v1-meta[metav1.ObjectMeta] | false | -
m| spec | &#160; m| <<QueueSpec,QueueSpec>> | false | -
m| status | &#160; m| <<QueueStatus,QueueStatus>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== QueueList

QueueList contains a list of Queue

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#listmeta-v1-meta[metav1.ListMeta] | false | -
m| items | &#160; m| []<<Queue,Queue>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== QueueSetting

QueueSetting defines the configuration for Hazelcast WAN queue

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| capacity | Capacity is the total capacity of WAN queue. m| int32 | false | 10000
m| fullBehavior | FullBehavior represents the behavior of the new arrival when the queue is full. m| <<FullBehaviorSetting,FullBehaviorSetting>> | false | DISCARD_AFTER_MUTATION
|===

<<Table of Contents,Back to TOC>>

=== QueueSpec

QueueSpec defines the desired state of Queue It cannot be updated after the Queue is created

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| name | Name of the data structure config to be created. If empty, CR name will be used. It cannot be updated after the config is created successfully. m| string | false | -
m| hazelcastResourceName | HazelcastResourceName defines the name of the Hazelcast resource. m| string | true | -
m| backupCount | Number of synchronous backups. m| &#42;int32 | false | 1
m| asyncBackupCount | Number of asynchronous backups. m| &#42;int32 | false | 0
m| maxSize | Max size of the queue. m| &#42;int32 | false | 0
m| emptyQueueTTLSeconds | Time in seconds after which the Queue will be destroyed if it stays empty or unused. If the values is not provided the Queue will never be destroyed. m| &#42;int32 | false | -1
m| priorityComparatorClassName | The name of the comparator class. If the class name is provided, the Queue becomes Priority Queue. You can learn more at https://docs.hazelcast.com/hazelcast/latest/data-structures/priority-queue. m| string | false | -
|===

<<Table of Contents,Back to TOC>>

=== QueueStatus

QueueStatus defines the observed state of Queue

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| state | &#160; m| <<DataStructureConfigState,DataStructureConfigState>> | false | -
m| message | &#160; m| string | false | -
m| memberStatuses | &#160; m| map[string]<<DataStructureConfigState,DataStructureConfigState>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== ReplicatedMap

ReplicatedMap is the Schema for the replicatedmaps API

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#objectmeta-v1-meta[metav1.ObjectMeta] | false | -
m| spec | &#160; m| <<ReplicatedMapSpec,ReplicatedMapSpec>> | false | -
m| status | &#160; m| <<ReplicatedMapStatus,ReplicatedMapStatus>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== ReplicatedMapList

ReplicatedMapList contains a list of ReplicatedMap

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#listmeta-v1-meta[metav1.ListMeta] | false | -
m| items | &#160; m| []<<ReplicatedMap,ReplicatedMap>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== ReplicatedMapSpec

ReplicatedMapSpec defines the desired state of ReplicatedMap

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| name | Name of the ReplicatedMap config to be created. If empty, CR name will be used. m| string | false | -
m| asyncFillup | AsyncFillup specifies whether the ReplicatedMap is available for reads before the initial replication is completed m| bool | false | true
m| inMemoryFormat | InMemoryFormat specifies in which format data will be stored in the ReplicatedMap m| <<InMemoryFormatType,InMemoryFormatType>> | false | OBJECT
m| hazelcastResourceName | HazelcastResourceName defines the name of the Hazelcast resource. m| string | true | -
|===

<<Table of Contents,Back to TOC>>

=== ReplicatedMapStatus

ReplicatedMapStatus defines the observed state of ReplicatedMap

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| state | &#160; m| <<DataStructureConfigState,DataStructureConfigState>> | false | -
m| message | &#160; m| string | false | -
m| memberStatuses | &#160; m| map[string]<<DataStructureConfigState,DataStructureConfigState>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== ResourceSpec



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| name | Name is the name of custom resource to which WAN replication applies. m| string | true | -
m| kind | Kind is the kind of custom resource to which WAN replication applies. m| <<ResourceKind,ResourceKind>> | true | Map
|===

<<Table of Contents,Back to TOC>>

=== RestoreConfiguration

RestoreConfiguration contains the configuration for Restore operation

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| bucketConfig | Bucket Configuration from which the backup will be downloaded. m| &#42;<<BucketConfiguration,BucketConfiguration>> | false | -
m| hotBackupResourceName | Name of the HotBackup resource from which backup will be fetched. m| string | false | -
|===

<<Table of Contents,Back to TOC>>

=== RestoreStatus



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| state | State shows the current phase of the restore process of the cluster. m| <<RestoreState,RestoreState>> | true | -
m| remainingValidationTime | RemainingValidationTime show the time in seconds remained for the restore validation step. m| int64 | true | -
m| remainingDataLoadTime | RemainingDataLoadTime show the time in seconds remained for the restore data load step. m| int64 | true | -
|===

<<Table of Contents,Back to TOC>>

=== ScheduledExecutorServiceConfiguration



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| name | The name of the executor service m| string | false | "default"
m| poolSize | The number of executor threads per member. m| int32 | false | 16
m| durability | Durability of the executor. m| int32 | false | 1
m| capacity | Capacity of the executor task per partition. m| int32 | false | 100
m| capacityPolicy | The active policy for the capacity setting. m| string | false | PER_NODE
|===

<<Table of Contents,Back to TOC>>

=== SchedulingConfiguration

SchedulingConfiguration defines the pods scheduling details

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| affinity | Affinity m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#affinity-v1-core[corev1.Affinity] | false | -
m| tolerations | Tolerations m| []https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#toleration-v1-core[corev1.Toleration] | false | -
m| nodeSelector | NodeSelector m| map[string]string | false | -
m| topologySpreadConstraints | TopologySpreadConstraints m| []https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#topologyspreadconstraint-v1-core[corev1.TopologySpreadConstraint] | false | -
|===

<<Table of Contents,Back to TOC>>

=== Topic

Topic is the Schema for the topics API

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#objectmeta-v1-meta[metav1.ObjectMeta] | false | -
m| spec | &#160; m| <<TopicSpec,TopicSpec>> | true | -
m| status | &#160; m| <<TopicStatus,TopicStatus>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== TopicList

TopicList contains a list of Topic

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#listmeta-v1-meta[metav1.ListMeta] | false | -
m| items | &#160; m| []<<Topic,Topic>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== TopicSpec

TopicSpec defines the desired state of Topic

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| name | Name of the topic config to be created. If empty, CR name will be used. m| string | false | -
m| globalOrderingEnabled | When true all nodes listening to the same topic get their messages in the same order m| bool | false | false
m| multiThreadingEnabled | When true enables multi-threaded processing of incoming messages, otherwise a single thread will handle all topic messages m| bool | false | false
m| hazelcastResourceName | HazelcastResourceName defines the name of the Hazelcast resource for which topic config will be created m| string | true | -
|===

<<Table of Contents,Back to TOC>>

=== TopicStatus

TopicStatus defines the observed state of Topic

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| state | &#160; m| <<DataStructureConfigState,DataStructureConfigState>> | false | -
m| message | &#160; m| string | false | -
m| memberStatuses | &#160; m| map[string]<<DataStructureConfigState,DataStructureConfigState>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== UserCodeDeploymentConfig

UserCodeDeploymentConfig contains the configuration for User Code download operation

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| clientEnabled | When true, allows user code deployment from clients. m| bool | false | -
m| bucketConfig | Jar files in the bucket will be put under CLASSPATH. m| &#42;<<BucketConfiguration,BucketConfiguration>> | false | -
m| triggerSequence | A string for triggering a rolling restart for re-downloading the user code. m| string | false | -
m| configMaps | Files in the ConfigMaps will be put under CLASSPATH. m| []string | false | -
|===

<<Table of Contents,Back to TOC>>

=== WanReplication

WanReplication is the Schema for the wanreplications API

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#objectmeta-v1-meta[metav1.ObjectMeta] | false | -
m| spec | &#160; m| <<WanReplicationSpec,WanReplicationSpec>> | false | -
m| status | &#160; m| <<WanReplicationStatus,WanReplicationStatus>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== WanReplicationList

WanReplicationList contains a list of WanReplication

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#listmeta-v1-meta[metav1.ListMeta] | false | -
m| items | &#160; m| []<<WanReplication,WanReplication>> | true | -
|===

<<Table of Contents,Back to TOC>>

=== WanReplicationMapStatus



[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| publisherId | PublisherId is the ID used for WAN publisher ID m| string | false | -
m| status | Status is the status of WAN replication m| <<WanStatus,WanStatus>> | false | -
m| message | Message is the field to show detail information or error m| string | false | -
|===

<<Table of Contents,Back to TOC>>

=== WanReplicationSpec

WanReplicationSpec defines the desired state of WanReplication

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| resources | Resources is the list of custom resources to which WAN replication applies. m| []<<ResourceSpec,ResourceSpec>> | true | -
m| targetClusterName | ClusterName is the clusterName field of the target Hazelcast resource. m| string | true | -
m| endpoints | Endpoints is the target cluster endpoints. m| string | true | -
m| queue | Queue is the configuration for WAN events queue. m| <<QueueSetting,QueueSetting>> | false | -
m| batch | Batch is the configuration for WAN events batch. m| <<BatchSetting,BatchSetting>> | false | -
m| acknowledgement | Acknowledgement is the configuration for the condition when the next batch of WAN events are sent. m| <<AcknowledgementSetting,AcknowledgementSetting>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== WanReplicationStatus

WanReplicationStatus defines the observed state of WanReplication

[cols="4,8,4,2,4"options="header"]
|===
| Field | Description | Type | Required | Default
m| status | Status is the status of WAN replication m| <<WanStatus,WanStatus>> | false | -
m| message | Message is the field to show detail information or error m| string | false | -
m| wanReplicationMapsStatus | &#160; m| map[string]<<WanReplicationMapStatus,WanReplicationMapStatus>> | false | -
|===

<<Table of Contents,Back to TOC>>

=== AcknowledgementType



[cols="5,10"options="header"]
|===
| Value | Description
m| "ACK_ON_RECEIPT" | &#160;
m| "ACK_ON_OPERATION_COMPLETE" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== BackupType

BackupType represents the storage options for the HotBackup

[cols="5,10"options="header"]
|===
| Value | Description
m| "External" | External backups to the provided cloud provider storage
m| "Local" | Local backups to local storage inside the cluster
|===

<<Table of Contents,Back to TOC>>

=== CapacityPolicyType

CapacityPolicyType represents the active policy types for the capacity setting

[cols="5,10"options="header"]
|===
| Value | Description
m| "PER_NODE" | CapacityPolicyPerNode is the policy for limiting the maximum number of tasks in each Hazelcast instance
m| "PER_PARTITION" | CapacityPolicyPerPartition is the policy for limiting the maximum number of tasks within each partition.
|===

<<Table of Contents,Back to TOC>>

=== CollectionType

CollectionType represents the value collection options for storing the data in the multiMap.

[cols="5,10"options="header"]
|===
| Value | Description
m| "SET" | &#160;
m| "LIST" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== DataRecoveryPolicyType

DataRecoveryPolicyType represents the options for data recovery policy when the whole cluster restarts.

[cols="5,10"options="header"]
|===
| Value | Description
m| "FullRecoveryOnly" | FullRecovery does not allow partial start of the cluster and corresponds to "cluster-data-recovery-policy.FULL_RECOVERY_ONLY" configuration option.
m| "PartialRecoveryMostRecent" | MostRecent allow partial start with the members that have most up-to-date partition table and corresponds to "cluster-data-recovery-policy.PARTIAL_RECOVERY_MOST_RECENT" configuration option.
m| "PartialRecoveryMostComplete" | MostComplete allow partial start with the members that have most complete partition table and corresponds to "cluster-data-recovery-policy.PARTIAL_RECOVERY_MOST_COMPLETE" configuration option.
|===

<<Table of Contents,Back to TOC>>

=== DataStructureConfigState



[cols="5,10"options="header"]
|===
| Value | Description
m| "Failed" | &#160;
m| "Success" | &#160;
m| "Pending" | &#160;
m| "Persisting" | The config is added into all members but waiting for the config to be persisten into ConfigMap
m| "Terminating" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== EvictionPolicyType



[cols="5,10"options="header"]
|===
| Value | Description
m| "LRU" | Least recently used entries will be removed.
m| "LFU" | Least frequently used entries will be removed.
m| "NONE" | No eviction.
m| "RANDOM" | Randomly selected entries will be removed.
|===

<<Table of Contents,Back to TOC>>

=== ExposeExternallyType

ExposeExternallyType describes how Hazelcast members are exposed.

[cols="5,10"options="header"]
|===
| Value | Description
m| "Smart" | ExposeExternallyTypeSmart exposes each Hazelcast member with a separate external address.
m| "Unisocket" | ExposeExternallyTypeUnisocket exposes all Hazelcast members with one external address.
|===

<<Table of Contents,Back to TOC>>

=== ExternalConnectivityType

ExternalConnectivityType describes how Management Center is exposed.

[cols="5,10"options="header"]
|===
| Value | Description
m| "ClusterIP" | ExternalConnectivityTypeClusterIP exposes Management Center with ClusterIP service.
m| "NodePort" | ExternalConnectivityTypeNodePort exposes Management Center with NodePort service.
m| "LoadBalancer" | ExternalConnectivityTypeLoadBalancer exposes Management Center with LoadBalancer service.
|===

<<Table of Contents,Back to TOC>>

=== FullBehaviorSetting



[cols="5,10"options="header"]
|===
| Value | Description
m| "DISCARD_AFTER_MUTATION" | &#160;
m| "THROW_EXCEPTION" | &#160;
m| "THROW_EXCEPTION_ONLY_IF_REPLICATION_ACTIVE" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== HotBackupState



[cols="5,10"options="header"]
|===
| Value | Description
m| "Unknown" | &#160;
m| "Pending" | &#160;
m| "NotStarted" | &#160;
m| "InProgress" | &#160;
m| "Failure" | &#160;
m| "Success" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== InMemoryFormatType

InMemoryFormatType represents the format options for storing the data in the map. For now, we are not exposing NATIVE format type since currently there is no support for High-Density Memory Store feature in the operator.

[cols="5,10"options="header"]
|===
| Value | Description
m| "BINARY" | InMemoryFormatBinary Data will be stored in serialized binary format.
m| "OBJECT" | InMemoryFormatObject Data will be stored in deserialized form.
m| "NATIVE" | InMemoryFormatNative Data will be stored in the map that uses Hazelcast's High-Density Memory Store feature.
|===

<<Table of Contents,Back to TOC>>

=== IndexType



[cols="5,10"options="header"]
|===
| Value | Description
m| "SORTED" | &#160;
m| "HASH" | &#160;
m| "BITMAP" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== InitialModeType



[cols="5,10"options="header"]
|===
| Value | Description
m| "LAZY" | Loading is asynchronous. It is the default mode.
m| "EAGER" | Loading is blocked until all partitions are loaded.
|===

<<Table of Contents,Back to TOC>>

=== LoggingLevel

LoggingLevel controlls log verbosity for Hazelcast.

[cols="5,10"options="header"]
|===
| Value | Description
m| "OFF" | &#160;
m| "FATAL" | &#160;
m| "ERROR" | &#160;
m| "WARN" | &#160;
m| "INFO" | &#160;
m| "DEBUG" | &#160;
m| "TRACE" | &#160;
m| "ALL" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== MapConfigState



[cols="5,10"options="header"]
|===
| Value | Description
m| "Failed" | &#160;
m| "Success" | &#160;
m| "Pending" | &#160;
m| "Persisting" | Map config is added into all members but waiting for map to be persisten into ConfigMap
m| "Terminating" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== MaxSizePolicyType



[cols="5,10"options="header"]
|===
| Value | Description
m| "PER_NODE" | Maximum number of map entries in each cluster member. You cannot set the max-size to a value lower than the partition count (which is 271 by default).
m| "PER_PARTITION" | Maximum number of map entries within each partition.
m| "USED_HEAP_PERCENTAGE" | Maximum used heap size percentage per map for each Hazelcast instance. If, for example, JVM is configured to have 1000 MB and this value is 10, then the map entries will be evicted when used heap size exceeds 100 MB. It does not work when "in-memory-format" is set to OBJECT.
m| "USED_HEAP_SIZE" | Maximum used heap size in megabytes per map for each Hazelcast instance. It does not work when "in-memory-format" is set to OBJECT.
m| "FREE_HEAP_PERCENTAGE" | Minimum free heap size percentage for each Hazelcast instance. If, for example, JVM is configured to have 1000 MB and this value is 10, then the map entries will be evicted when free heap size is below 100 MB.
m| "FREE_HEAP_SIZE" | Minimum free heap size in megabytes for each Hazelcast instance.
m| "USED_NATIVE_MEMORY_SIZE" | Maximum used native memory size in megabytes per map for each Hazelcast instance. It is available only in Hazelcast Enterprise HD.
m| "USED_NATIVE_MEMORY_PERCENTAGE" | Maximum used native memory size percentage per map for each Hazelcast instance. It is available only in Hazelcast Enterprise HD.
m| "FREE_NATIVE_MEMORY_SIZE" | Minimum free native memory size in megabytes for each Hazelcast instance. It is available only in Hazelcast Enterprise HD.
m| "FREE_NATIVE_MEMORY_PERCENTAGE" | Minimum free native memory size percentage for each Hazelcast instance. It is available only in Hazelcast Enterprise HD.
|===

<<Table of Contents,Back to TOC>>

=== MemberAccess

MemberAccess describes how each Hazelcast member is accessed from the external client.

[cols="5,10"options="header"]
|===
| Value | Description
m| "NodePortExternalIP" | MemberAccessNodePortExternalIP lets the client access Hazelcast member with the NodePort service and the node external IP/hostname
m| "NodePortNodeName" | MemberAccessNodePortNodeName lets the client access Hazelcast member with the NodePort service and the node name
m| "LoadBalancer" | MemberAccessLoadBalancer lets the client access Hazelcast member with the LoadBalancer service
|===

<<Table of Contents,Back to TOC>>

=== NodeState



[cols="5,10"options="header"]
|===
| Value | Description
m| "PASSIVE" | &#160;
m| "ACTIVE" | &#160;
m| "SHUT_DOWN" | &#160;
m| "STARTING" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== Phase

Phase represents the current state of the cluster

[cols="5,10"options="header"]
|===
| Value | Description
m| "Running" | Running phase is the state when all the members of the cluster are successfully started
m| "Failed" | Failed phase is the state of error during the cluster startup
m| "Pending" | Pending phase is the state of starting the cluster when not all the members are started yet
m| "Terminating" | Terminating phase is the state where deletion of cluster scoped resources and Hazelcast dependent resources happen
|===

<<Table of Contents,Back to TOC>>

=== ResourceKind



[cols="5,10"options="header"]
|===
| Value | Description
m| "Map" | &#160;
m| "Hazelcast" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== RestoreState



[cols="5,10"options="header"]
|===
| Value | Description
m| "Unknown" | &#160;
m| "Failed" | &#160;
m| "InProgress" | &#160;
m| "Succeeded" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== UniqueKeyTransition



[cols="5,10"options="header"]
|===
| Value | Description
m| "OBJECT" | &#160;
m| "LONG" | &#160;
m| "RAW" | &#160;
|===

<<Table of Contents,Back to TOC>>

=== WanStatus



[cols="5,10"options="header"]
|===
| Value | Description
m| "Failed" | &#160;
m| "Pending" | &#160;
m| "Success" | &#160;
m| "Terminating" | &#160;
|===

<<Table of Contents,Back to TOC>>
