= Persistence, Backup and Restore
:description: Persistence allows individual members and whole clusters to recover data by persisting map entries, JCache data, and streaming job snapshots on disk. Members can use persisted data to recover from a planned shutdown (including rolling upgrades), a sudden cluster-wide crash, or a single member failure.
:page-enterprise: true

Persistence allows individual members and whole clusters to recover data by persisting map entries, JCache data, and streaming job snapshots on disk. Members can use persisted data to recover from a planned shutdown (including rolling upgrades), a sudden cluster-wide crash, or a single member failure.

This topic assumes that you know about Persistence in Hazelcast. To learn about Persistence, see the xref:hazelcast:storage:persistence.adoc[Platform documentation].

The Operator supports two options for enabling Persistence: PVC and `HostPath`. We recommend using PVC, so the examples on this page use this option. If you need to use `HostPath`, see <<hostpath,  HostPath Support for Persistence>>.

Before you back up and restore Hazelcast data, you need to enable Persistence in the `Hazelcast` resource.
There are two options for backup and restore; `External` or `Local` (Default option)

== Enabling Local Persistence

. Create the `Hazelcast` resource:
+
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-persistence.yaml[]
----
<1> Base directory of the backup data.
<2> <<recovery-policy, Cluster recovery policy>>.
<3> Size of the PersistentVolumeClaim (PVC) where Hazelcast data is persisted.
+
NOTE: Make sure to calculate the total disk space that you will use. The total used disk space may be larger than the size of in-memory data, depending on how many <<local-backup, backups>> you take.

. Apply the resource:
+
[source,bash]
----
kubectl apply -f ./hazelcast-persistence.yaml
----

. Check that Hazelcast members are ready:
+
[source,bash]
----
kubectl get pods -l app.kubernetes.io/instance=hazelcast
----
+
[source,bash]
----
NAME          READY   STATUS    RESTARTS   AGE
hazelcast-0   1/1     Running   0          2m
hazelcast-1   1/1     Running   0          1m
hazelcast-2   1/1     Running   0          1m
----

. Check that Hazelcast PVCs are created:
+
[source,bash]
----
kubectl get pvc -l app.kubernetes.io/instance=hazelcast
----
+
[source,bash]
----
NAME                                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
hot-restart-persistence-hazelcast-0   Bound    pvc-116b4084-a436-4462-b413-511b77df307b   20Gi       RWO            standard       2m
hot-restart-persistence-hazelcast-1   Bound    pvc-a7711b6b-dcbf-45cb-9577-8ce6b1892f2f   20Gi       RWO            standard       1m
hot-restart-persistence-hazelcast-2   Bound    pvc-64314d82-da7a-4e38-bd2d-e770a63dc4e8   20Gi       RWO            standard       1m
----

[[local-backup]]
=== Triggering Local Backups
After Persistence is enabled for the cluster, you can trigger backups, using a `HotBackup` resource.

. Create the `HotBackup` resource:
+
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hot-backup.yaml[]
----

. Apply the resource:
+
[source,bash]
----
kubectl apply -f ./hot-backup.yaml
----

=== Scheduling Local Backups

You can schedule regular backups, using the `schedule` and `hotBackupTemplate` fields of the `CronHotBackup` resource. For more information about the `CronHotBackup` resource, see the xref:api-ref.adoc#cronhotbackupspec[API Reference].

. Create the `CronHotBackup` resource and add values for the `schedule` and `hotBackupTemplate` fields. For example:
+
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/cron-hot-backup.yaml[]
----
+
The `schedule` field takes a valid cron expression. For example, you can configure the following scheduled backups:
+
[cols="1,1"]
|===
| ```30 10 * * *```
| At 10:30 AM every day

| ```0, 0, 1,15,25 * *```
| On 1st, 15th, and 25th of each month at midnight

| ```@monthly```
| On the first day of each month at midnight
|===

+
For a full list of supported expressions, see the link:https://pkg.go.dev/github.com/robfig/cron/v3@v3.0.1#hdr-CRON_Expression_Format[library documentation].

. Apply the resource:
+
[source,bash]
----
kubectl apply -f ./cron-hot-backup.yaml
----

=== Checking the Status of a Local Backup

To check the status of a local backup, run the following command:
[source,bash]
----
kubectl get hotbackup hot-backup
----

The status of the backup is displayed in the output.
[source,bash]
----
NAME         STATUS
hot-backup   Success
----

=== Restoring from Local Backups

To restore a cluster from local backups, you can directly reapply the `Hazelcast` resource, and it will have access to the PVCs that contain the persisted data. This will restore the Hazelcast cluster from existing `hot-restart` folders.

However, if you want to restore from local backups you have taken using the `HotBackup` resource, you can give the `HotBackup` resource name in the restore configuration. For restore to work correctly, make sure the status of the `HotBackup` resource is `Success`. 

When restore mechanism is used, the Restore Agent container will
be deployed with the Hazelcast container in the same Pod. The agent will start as an initContainer before the Hazelcast container.

. Delete the Hazelcast cluster:
+
[source,bash]
----
kubectl delete hazelcast hazelcast
----

. Check that the PVCs are still available:
+
[source,bash]
----
kubectl get pvc -l app.kubernetes.io/instance=hazelcast
----
+
[source,bash]
----
NAME                                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
hot-restart-persistence-hazelcast-0   Bound    pvc-116b4084-a436-4462-b413-511b77df307b   20Gi       RWO            standard       6m
hot-restart-persistence-hazelcast-1   Bound    pvc-a7711b6b-dcbf-45cb-9577-8ce6b1892f2f   20Gi       RWO            standard       5m
hot-restart-persistence-hazelcast-2   Bound    pvc-64314d82-da7a-4e38-bd2d-e770a63dc4e8   20Gi       RWO            standard       5m

----

. Apply the `Hazelcast` resource with restore configuration:
+
[source,bash]

----
include::ROOT:example$/hazelcast-persistence-restore-cr-name.yaml[]
----

<1> The `HotBackup` resource name that will be used for restore. The backup folder name will be taken from the `HotBackup` resource.
<2> The agent which is responsible for restoring data from the external storage.
    The agent configuration is optional. If you give `restore` under the `persistence` and do not pass the agent configuration, the operator
    will use the latest agent version compatible with the operator version.

----
kubectl apply -f ./hazelcast-persistence-restore.yaml
----

. See that the same PVCs are bound to the new pods:
+
[source,bash]
----
kubectl get pods -l app.kubernetes.io/instance=hazelcast -ojsonpath='{.items[*].spec.volumes[?(@.name=="hot-restart-persistence")].persistentVolumeClaim.claimName}'

----
+
You should see something like the following:
+
[source,bash]
----
hot-restart-persistence-hazelcast-0 hot-restart-persistence-hazelcast-1 hot-restart-persistence-hazelcast-2
----

== Enabling External Persistence

In some cases, keeping the data only at PVC and restoring the data from it is not enough.
For example, moving data between two Kubernetes clusters. You can use external storages so they
will become portable.

For enabling external persistence, you need two additional configurations. One is `backupType`.
The other one is `agent configuration`. When external persistence is used, the Backup Agent container will
be deployed with the Hazelcast container in the same Pod.

. Create the `Hazelcast` resource:
+
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-persistence-agent.yaml[]
----
<1> The backup type for where the backup data will be stored. It is either `Local` or `External`. Default value is `Local`.
<5> The agent which is responsible for backing data up into the external storage.
The agent configuration is optional. If you set the `backupType` to `External` and do not pass the agent configuration, the operator
directly use the latest stable version of the agent.
+

. Apply the resource:
+
[source,bash]
----
kubectl apply -f ./hazelcast-persistence-agent.yaml
----

. Check that Hazelcast members are ready:
+
[source,bash]
----
kubectl get pods -l app.kubernetes.io/instance=hazelcast
----
+
[source,bash]
----
NAME          READY   STATUS    RESTARTS   AGE
hazelcast-0   2/2     Running   0          2m55s
hazelcast-1   2/2     Running   0          2m15s
hazelcast-2   2/2     Running   0          99s
----

. Check that Hazelcast PVCs are created:
+
[source,bash]
----
kubectl get pvc -l app.kubernetes.io/instance=hazelcast
----
+
[source,bash]
----
NAME                                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
hot-restart-persistence-hazelcast-0   Bound    pvc-116b4084-a436-4462-b413-511b77df307b   20Gi       RWO            standard       2m
hot-restart-persistence-hazelcast-1   Bound    pvc-a7711b6b-dcbf-45cb-9577-8ce6b1892f2f   20Gi       RWO            standard       1m
hot-restart-persistence-hazelcast-2   Bound    pvc-64314d82-da7a-4e38-bd2d-e770a63dc4e8   20Gi       RWO            standard       1m
----

=== Triggering External Backups

To trigger an external backup, you need to configure a bucket URI and a secret to tell Hazelcast where to store backup data and how to authenticate.

. Create the `HotBackup` resource:
+
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hot-backup-agent.yaml[]
----
<1> The bucket URI where backup data will be stored in
<2> Name of the secret with credentials for accessing the given Bucket URI.


. Create the secret: [[create-secret]]
+
[tabs]
====

AWS::
+
--
See https://docs.aws.amazon.com/sdk-for-go/api/aws/session/[AWS Session] to learn about authentication procedure.
[source,bash]
----
kubectl create secret generic <secret-name> --from-literal=region=<region> \
	--from-literal=access-key-id=<access-key-id> \
	--from-literal=secret-access-key=<secret-access-key>
----
--

GCP::
+
--
See https://cloud.google.com/docs/authentication/production/[Application Default Credentials] to learn about authentication procedure.
[source,bash]
----
kubectl create secret generic <secret-name> --from-file=google-credentials-path=<service_account_json_file>
----
--

Azure::
+
--
See https://docs.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?tabs=azure-portal/[Azure Storage Account Keys] to learn about authentication procedure.
[source,bash]
----
kubectl create secret generic <secret-name> \
	--from-literal=storage-account=<storage-account> \
	--from-literal=storage-key=<storage-key>
----
--

====

. Apply the resource:
+
[source,bash]
----
kubectl apply -f ./hot-backup-agent.yaml
----

=== Scheduling External Backups

You can schedule regular backups to an external storage bucket, using the `schedule` and `hotBackupTemplate` fields of the `CronHotBackup` resource. For more information about the `CronHotBackup` resource, see the xref:api-ref.adoc#cronhotbackupspec[API Reference].

. Create the `CronHotBackup` resource and add values for the `schedule` and `hotBackupTemplate` fields. For example:
+
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/cron-hot-backup-agent.yaml[]
----
+
The `schedule` field takes a valid cron expression. For example, you can configure the following scheduled backups:
+
[cols="1,1"]
|===
| ```30 10 * * *```
| At 10:30 AM every day

| ```0, 0, 1,15,25 * *```
| On 1st, 15th, and 25th of each month at midnight

| ```@monthly```
| On the first day of each month at midnight
|===

+
For a full list of supported expressions, see the link:https://pkg.go.dev/github.com/robfig/cron/v3@v3.0.1#hdr-CRON_Expression_Format[library documentation].

. Apply the resource:
+
[source,bash]
----
kubectl apply -f ./cron-hot-backup-agent.yaml
----

=== Checking the Status of an External Backup

To check the status of an external backup, run the following command:
[source,bash]
----
kubectl get hotbackup hot-backup
----

The status of the backup is displayed in the output.
[source,bash]
----
NAME         STATUS
hot-backup   Success
----

=== Restoring from External Backups

To restore a cluster from external backups, you can either set up the bucket configuration or give the `HotBackup` resource name you triggered the external backup. In either case backups will be restored from the external buckets.

When restore mechanism is used, the Restore Agent container will
be deployed with the Hazelcast container in the same Pod. The agent will start as an initContainer before the Hazelcast container.

. Delete the Hazelcast cluster:
+
[source,bash]
----
kubectl delete hazelcast hazelcast
----

. Apply the `Hazelcast` resource with restore configuration:
+
[tabs]
====

Bucket Configuration::
+
--
----
include::ROOT:example$/hazelcast-persistence-restore-external.yaml[]
----
<1> The bucket URI where backup data will be restored from.
<2> Name of the secret with credentials for accessing the given Bucket URI.
<3> The agent which is responsible for restoring data from the external storage.
    The agent configuration is optional. If you give `restore` under the `persistence` and do not pass the agent configuration, the operator
    will use the latest agent version compatible with the operator version.
+

. If you have not created the secret, you must create the secret using the same way with the <<create-secret, Triggering External Backups>>.

--

HotBackup resource name::
+
--
----
include::ROOT:example$/hazelcast-persistence-restore-cr-name.yaml[]
----

<1> The `HotBackup` resource name that will be used for restore. The bucket URI and secret will be taken from the `HotBackup` resource.
<2> The agent which is responsible for restoring data from the external storage.
    The agent configuration is optional. If you give `restore` under the `persistence` and do not pass the agent configuration, the operator
    will use the latest agent version compatible with the operator version.
--

====
[source,yaml,subs="attributes+"]

. Apply the `Hazelcast` resource:
+
[source,bash]
----
kubectl apply -f ./hazelcast-persistence-restore-external.yaml
----

. See that the same PVCs are bound to the new pods:
+
[source,bash]
----
kubectl get pods -l app.kubernetes.io/instance=hazelcast -ojsonpath='{.items[*].spec.volumes[?(@.name=="hot-restart-persistence")].persistentVolumeClaim.claimName}'

----
+
You should see something like the following:
+
[source,bash]
----
hot-restart-persistence-hazelcast-0 hot-restart-persistence-hazelcast-1 hot-restart-persistence-hazelcast-2
----

=== Data Recovery Timeout

To choose a data recovery timeout, you can use dataRecoveryTimeout. The field takes an integer value representing the timeout in seconds and uses this value to set link:https://docs.hazelcast.com/hazelcast/5.1/storage/configuring-persistence#global-persistence-options[validation-timeout-seconds, data-load-timeout-seconds] Hazelcast Persistence options.

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-persistence-datarecoverytimeout.yaml[]
----

[[recovery-policy]]
== Choosing a Cluster Recovery Policy

To decide how a cluster should behave when one or more members cannot rejoin after a cluster-wide restart, you can define one of the following cluster recovery policies. The Operator supports all the policies in the Hazelcast Platform `cluster-data-recovery-policy configuration` options. For complete descriptions and advice on choosing a policy, see the xref:hazelcast:storage:configuring-persistence.adoc#policy[Platform documentation].

[cols="1,1"]
|===
| ```FullRecoveryOnly```
| Does not allow partial start of the cluster.

| ```PartialRecoveryMostRecent```
| Allows partial start with the members that have most recent partition table.

| ```PartialRecoveryMostComplete```
| Allows partial start with the member that have most complete partition table.
|===

=== Configuring Force-Start

If you use the `FullRecoveryOnly` policy, you can configure the Operator to detect failed Hazelcast members and automatically trigger a force-start. The Operator will trigger a force-start only if the cluster is in a `PASSIVE` state.

WARNING: The cluster loses all persisted data after a force-start.

Enable `autoForceStart`:

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-autoforcestart.yaml[]
----

[[hostpath]]
== HostPath Support for Persistence

You can also use HostPath to enable persistence.

WARNING: HostPath support is discouraged for the production environments for the reasons
mentioned in the link:https://kubernetes.io/docs/concepts/storage/volumes/#hostpath[Kubernetes documentation]

WARNING: HostPath support expects the size of the cluster to be equal to the number of Kubernetes nodes
and pods are distributed to the nodes equally. You can manage how pods are distributed among nodes by setting the `topologySpreadContraints` field, which is described in xref:scheduling-configuration.adoc#topology-spread-constraints[Scheduling Hazelcast Pods].

. Create the Hazelcast resource with the `clusterSize` equal to the number of Kubernetes nodes
and give the proper `topologySpreadConstraints`:
+
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-persistence-hostpath.yaml[]
----

. Apply the Hazelcast resource
+
[source,bash]
----
kubectl apply -f ./hazelcast-persistence-hostpath.yaml
----
