= Persistence, Backup and Restore
:description: Persistence allows individual members and whole clusters to recover data by persisting map entries, JCache data, and streaming job snapshots on disk. Members can use persisted data to recover from a planned shutdown (including rolling upgrades), a sudden cluster-wide crash, or a single member failure.
:page-enterprise: true

Persistence allows individual members and whole clusters to recover data by persisting map entries, JCache data, and streaming job snapshots on disk. Members can use persisted data to recover from a planned shutdown (including rolling upgrades), a sudden cluster-wide crash, or a single member failure.

This topic assumes that you know about Persistence in Hazelcast. To learn about Persistence, see the xref:hazelcast:storage:persistence.adoc[Platform documentation].

The Operator supports two volume options for enabling Persistence: PVC and `HostPath`. We recommend using PVC, so the examples on this page use this option. If you need to use `HostPath`, see <<hostpath,  HostPath Support for Persistence>>.

There are two options for a backup: local and external. Local backups are kept in volume and never moved anywhere whereas external backups are moved into buckets provided by the user. 

== Enabling Persistence

Enabling Hazelcast is done with the following configuration.


[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-persistence.yaml[]
----

<1> Base directory of the backup data.
<2> <<recovery-policy, Cluster recovery policy>>.
<3> Size of the PersistentVolumeClaim (PVC) where Hazelcast data is persisted.
<4> Agent responsible for moving data from the local storage to external buckets.
    The agent configuration is optional. If you enable `persistence` and do not pass the agent configuration, Hazelcast Platform Operator
    uses the latest agent version that is compatible with its version.

NOTE: Make sure to calculate the total disk space that you will use. The total used disk space may be larger than the size of in-memory data, depending on how many <<local-backup, backups>> you take.

[[trigger-backup]]
== Triggering Local Backups

You can take local backups using the `HotBackup` custom resource. Local backups are kept in volume and are not moved anywhere.

--
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hot-backup-local.yaml[]
----
--

== Triggering External Backups

In some cases, keeping the data only at PVC and restoring the data from it is not enough.
For example, moving data between two Kubernetes clusters. You can use external storages so they
will become portable.

When persistence is enabled Hazelcast pod will start with a sidecar agent which will upload the backups into an external bucket provided by the user.

To trigger an external backup, you need to configure a bucket URI and a secret to tell Hazelcast where to store backup data and how to authenticate.

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hot-backup-external.yaml[]
----
<1> The bucket URI where backup data will be stored in
<2> Name of the secret with credentials for accessing the given Bucket URI.


[tabs]
====

AWS::
+
--
See https://docs.aws.amazon.com/sdk-for-go/api/aws/session/[AWS Session] to learn about authentication procedure.
[source,bash]
----
kubectl create secret generic <secret-name> --from-literal=region=<region> \
	--from-literal=access-key-id=<access-key-id> \
	--from-literal=secret-access-key=<secret-access-key>
----
--

GCP::
+
--
See https://cloud.google.com/docs/authentication/production/[Application Default Credentials] to learn about authentication procedure.
[source,bash]
----
kubectl create secret generic <secret-name> --from-file=google-credentials-path=<service_account_json_file>
----
--

Azure::
+
--
See https://docs.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?tabs=azure-portal/[Azure Storage Account Keys] to learn about authentication procedure.
[source,bash]
----
kubectl create secret generic <secret-name> \
	--from-literal=storage-account=<storage-account> \
	--from-literal=storage-key=<storage-key>
----
--

====

== Scheduling Backups

You can schedule backups using the `schedule` and `hotBackupTemplate` fields of the `CronHotBackup` resource. For more information about the `CronHotBackup` resource, see the xref:api-ref.adoc#cronhotbackupspec[API Reference].

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/cron-hot-backup.yaml[]
----

The `schedule` field takes a valid cron expression. For example, you can configure the following scheduled backups:

[cols="1,1"]
|===
| ```30 10 * * *```
| At 10:30 AM every day

| ```0, 0, 1,15,25 * *```
| On 1st, 15th, and 25th of each month at midnight

| ```@monthly```
| On the first day of each month at midnight
|===


For a full list of supported expressions, see the link:https://pkg.go.dev/github.com/robfig/cron/v3@v3.0.1#hdr-CRON_Expression_Format[library documentation].

== Checking the Status of a Backup

To check the status of a local backup, run the following command:
[source,bash]
----
kubectl get hotbackup hot-backup
----

The status of the backup is displayed in the output.
[source,bash]
----
NAME         STATUS
hot-backup   Success
----

== Restoring from Local Backups

To restore a cluster from local backups, you can directly reapply the `Hazelcast` resource, which gives the cluster access to the PVCs that contain the persisted data. This will restore the Hazelcast cluster from existing `hot-restart` folders.

Or, to restore from local backups that you have taken using the `HotBackup` resource, give the `HotBackup` resource name in the restore configuration. For the restore to work correctly, make sure the status of the `HotBackup` resource is `Success`. 

When this restore mechanism is used, the Restore Agent container is
deployed with the Hazelcast container in the same Pod. The agent starts as an initContainer before the Hazelcast container.


[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-persistence-restore-cr-name.yaml[]
----

<1> `HotBackup` resource name used for restore. The backup folder name will be taken from the `HotBackup` resource.
<2> Agent responsible for restoring data from the local storage.
    The agent configuration is optional. If you give `restore` under `persistence` and do not pass the agent configuration, Hazelcast Platform Operator
    uses the latest agent version that is compatible with its version.

NOTE: For restore to be successful you have to give restore configuration at the `Hazelcast` custom resource creation. Otherwise, triggering restore on currently running members will likely to fail. 


== Restoring from External Backups

To restore a cluster from external backups, you can either set up the bucket configuration or give the `HotBackup` resource name that you used to trigger the external backup. In either case, the backup is restored from the external bucket.

When this restore mechanism is used, the Restore Agent container is deployed with the Hazelcast container in the same Pod. The agent starts as an initContainer before the Hazelcast container.

NOTE: If you have not created the secret, you must do so in the same way as in <<create-secret, Triggering External Backups>>.

[tabs]
====

Bucket Configuration::
+
--
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-persistence-restore-external.yaml[]
----
<1> Bucket URI where backup data will be restored from.
<2> Name of the secret with credentials for accessing the given bucket URI.
<3> Agent which is responsible for restoring data from the external storage.
    The agent configuration is optional. If you provide `restore` under `persistence` and do not pass the agent configuration, Hazelcast Platform Operator
    uses the latest agent version that is compatible with its version.
--

HotBackup resource name::
+
--
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-persistence-restore-cr-name.yaml[]
----

<1> `HotBackup` resource name used for the restore. The bucket URI and secret are taken from the `HotBackup` resource.
<2> Agent responsible for restoring data from external storage.
    The agent configuration is optional. If you provide `restore` under `persistence` and do not pass the agent configuration, Hazelcast Platform Operator
    uses the latest agent version that is compatible with its version.
--

====

NOTE: For restore to be successful you have to give restore configuration at the `Hazelcast` custom resource creation. Otherwise, triggering restore on currently running members will likely to fail. 

== Configuring Persistence

=== Data Recovery Timeout

To choose a data recovery timeout, you can use dataRecoveryTimeout. The field takes an integer value representing the timeout in seconds and uses this value to set link:https://docs.hazelcast.com/hazelcast/5.1/storage/configuring-persistence#global-persistence-options[validation-timeout-seconds, data-load-timeout-seconds] Hazelcast Persistence options.

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-persistence-datarecoverytimeout.yaml[]
----

[[recovery-policy]]
=== Choosing a Cluster Recovery Policy

To decide how a cluster should behave when one or more members cannot rejoin after a cluster-wide restart, you can define one of the following cluster recovery policies. The Operator supports all the policies in the Hazelcast Platform `cluster-data-recovery-policy configuration` options. For complete descriptions and advice on choosing a policy, see the xref:hazelcast:storage:configuring-persistence.adoc#policy[Platform documentation].

[cols="1,1"]
|===
| ```FullRecoveryOnly```
| Does not allow partial start of the cluster.

| ```PartialRecoveryMostRecent```
| Allows partial start with the members that have most recent partition table.

| ```PartialRecoveryMostComplete```
| Allows partial start with the member that have most complete partition table.
|===

=== Configuring Force-Start

If you use the `FullRecoveryOnly` policy, you can configure the Operator to detect failed Hazelcast members and automatically trigger a force-start. The Operator will trigger a force-start only if the cluster is in a `PASSIVE` state.

WARNING: The cluster loses all persisted data after a force-start.

Enable `autoForceStart`:

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-autoforcestart.yaml[]
----

[[hostpath]]
== HostPath Support for Persistence

You can also use HostPath to enable persistence.

WARNING: HostPath support is discouraged for the production environments for the reasons
mentioned in the link:https://kubernetes.io/docs/concepts/storage/volumes/#hostpath[Kubernetes documentation]

WARNING: HostPath support expects the size of the cluster to be equal to the number of Kubernetes nodes
and pods are distributed to the nodes equally. You can manage how pods are distributed among nodes by setting the `topologySpreadContraints` field, which is described in xref:scheduling-configuration.adoc#topology-spread-constraints[Scheduling Hazelcast Pods].

Create the Hazelcast resource with the `clusterSize` equal to the number of Kubernetes nodes and give the proper `topologySpreadConstraints`.

+
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-persistence-hostpath.yaml[]
----

