= Client authentication and authorization

You can use Operator to configure xref:hazelcast:security:authentication-overview.adoc[client authentication] and xref:hazelcast:security:client-authorization.adoc[client authorization].

== Simple authentication

You can enable xref:hazelcast:security:simple-authentication.adoc[Hazelcast simple authentication] with minimal changes to the original configuration.

To enable simple authentication:

* Remove `security.enabled`.
* Convert kebab case to camel case:
** `client-authentication` -> `clientAuthentication`
** `client-permissions` -> `clientPermissions`
* Add a `permissions` node to `clientPermissions` to wrap permissions other than `all`.

For example:

[source,yaml]
----
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
    security:
        operatorClientSecretName: user1-secret
        realms:
          - name: simpleRealm-clients
            authentication:
              simple:
                users:
                - secretName: user1-secret
                  roles:
                    - admin
                - secretName: user2-secret
                  roles:
                    - monitor
                    - application
        clientAuthentication:
          realm: simpleRealm-clients
        clientPermissions:
          all:
            principal: admin
            endpoints:
              - 127.0.0.1
          permissions:
            map:
              - name: playground
                actions:
                  - all
              - name: accounts
                principal: monitor
                actions:
                  - read
              - name: accounts
                principal: application
                endpoints:
                  - 192.168.1.*
                  - 192.168.2.*
                actions:
                  - create
                  - destroy
                  - put
                  - read
                  - remove
                  - lock
----

NOTE: `operatorClientSecretName` is a mandatory field required for Operator to establish a connection with the Hazelcast cluster. The given user in the `operatorClientSecretName` field must have a role that has all the client permissions. Otherwise, Operator will fail with a validation error.

=== Configure Management Center

Because Management Center serves as a client of the Hazelcast cluster, it must be properly configured to connect to the cluster. The `security.clientSecretName` field in the `hazelcastClusters` section is used for this configuration.

.Management Center Simple Authentication Example
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/management-center-simple-auth.yaml[]
----

NOTE: The given user in the `ClientSecretName` field must have a role that has all the client permissions. Otherwise, Operator will fail with a validation error.