= Connect to Hazelcast from Outside Kubernetes

To connect to a Hazelcast cluster from outside Kubernetes, you need to configure the `expose-externally` field of your custom resource.

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast_expose_externally.yaml[]
----

After applying the configuration change in Kubernetes, each Hazelcast member will be exposed as a separate service.

[source,shell]
----
kubectl get service
----

```
NAME                 TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)          AGE
hazelcast-sample     LoadBalancer   10.219.246.19    35.230.92.217   5701:30560/TCP   2m11s
hazelcast-sample-0   NodePort       10.219.254.192   <none>          5701:31890/TCP   2m11s
hazelcast-sample-1   NodePort       10.219.247.43    <none>          5701:32310/TCP   2m11s
hazelcast-sample-2   NodePort       10.219.243.16    <none>          5701:32585/TCP   2m11s
```

To connect to the cluster, you can add the external IP address of the LoadBalancer service to your Hazelcast client configuration.

You can configure the `expose-externally` field with the following properties:

* `type`: The way in which Hazelcast members are exposed to clients.
** `Unisocket`: Members are exposed via one Kubernetes service.
** `Smart`: Each member is exposed via a separate Kubernetes service.
* `discoveryServiceType`: Type of Kubernetes service used for discovering members in a Hazelcast cluster.
** `LoadBalancer` (default): Hazelcast client configuration `<load-balancer-external-ip>:5701`.
** `NodePort`: Hazelcast client configuration `<node-address>:<node-port>`.
* `memberAccess`: The way in which clients access Hazelcast members.
** `NodePortExternalIP` (default): Hazelcast clients are outside the Kubernetes network, so a client can access members only via the public IP address that's assigned to their Kubernetes nodes.
** `NodePortNodeName`: Hazelcast clients are inside the same network as the Kubernetes nodes, so clients can access a member by the hostname of its Kubernetes node.
** `LoadBalancer`: Hazelcast clients are outside the Kubernetes network and can access members via the the external IP assigned to the LoadBalancer service.

WARNING: Your Kubernetes cluster should be able to assign public IPs to LoadBalancer services to connect to Hazelcast from outside Kubernetes.

WARNING: If NodePorts are used (`discoveryServiceType: NodePort` or `memberAccess: NodePortExternalIP`), then the Kubernetes nodes should have access from outside Kubernetes. This includes both the node IPs and ports.

== Google Kubernetes Engine

If you are using Google Kubernetes Engine (GKE) and trying to connect to Hazelcast from outside Kubernetes, then you need to consider the following:

- The Kubernetes cluster should not be private.
- If NodePorts are used (`discoveryServiceType: NodePort` or `memberAccess: NodePortExternalIP`), a firewall rule for each Hazelcast member should be added to allow TCP traffic on node ports.

== Amazon Elastic Kubernetes Service

If you are using Amazon Elastic Kubernetes Service (EKS) and trying to connect to Hazelcast from outside Kubernetes, then you need to consider the following:

- Having the VPC of the EKS cluster configured only with private subnets is not recommended.
- If NodePorts are used (`discoveryServiceType: NodePort` or `memberAccess: NodePortExternalIP`), the VPC of the EKS cluster should be configured only with public subnets. Additionally, inbound rules for the node ports should be added to the nodes' security groups.
- AWS load balancers are assigned with hostnames by default. Since it takes some time to resolve these hostnames, the member pods might fail to start with `CrashLoopBackOff` status in the beginning. But the pods will be running fine eventually after a couple of restarts.

== Azure Kubernetes Service

If you are using Azure Kubernetes Service (AKS) and trying to connect to Hazelcast from outside Kubernetes, then you need to consider the following:

- The Kubernetes cluster should not be private.
- If NodePorts are used (`discoveryServiceType: NodePort` or `memberAccess: NodePortExternalIP`), the node pools should be created by using `--enable-node-public-ip` flag. Additionally, the required inbound rules should be added for network security groups (NSGs) to allow access to node IPs and ports.
