= Connect to Hazelcast from Outside Kubernetes
:description: Hazelcast supports connections from both smart and unisocket clients that are outside your Kubernetes cluster. To allow these clients to connect to Hazelcast, you must configure the Hazelcast custom resource.

{description}

TIP: Follow the link:https://docs.hazelcast.com/tutorials/hazelcast-platform-operator-expose-externally/[Connect to Hazelcast from Outside Kubernetes] tutorial if you prefer a working example.

== Environmental Constraints

The `kubectl` command-line tool must be configured to communicate with your cluster.

If you use a Kubernetes service to run Kubernetes, there might be further constraints. Examples of such constraints for common Kubernetes services include the following:

.Google Kubernetes Engine (GKE)
[%collapsible]
====
- The Kubernetes cluster must be public.
- If you want to use NodePorts (that is, you have set `discoveryServiceType: NodePort` or `memberAccess: NodePortExternalIP`), a firewall rule must exist for each Hazelcast member to allow TCP traffic on node ports.
====

.Amazon Elastic Kubernetes Service (EKS)
[%collapsible]
====
- Configuring the Virtual Private Cloud (VPC) of the EKS cluster with private subnets only is not recommended.
- If you want to use NodePorts (that is, you have set `discoveryServiceType: NodePort` or `memberAccess: NodePortExternalIP`):

** The VPC of the EKS cluster must be configured with public subnets only.
** Inbound rules for the node ports must be added to the nodes' security groups.
====

.Azure Kubernetes Service (AKS)
[%collapsible]
====
- The Kubernetes cluster must be public.

- If you want to use NodePorts (that is, you have set `discoveryServiceType: NodePort` or `memberAccess: NodePortExternalIP`):

** The node pools must be created using the `--enable-node-public-ip` flag.
** The required inbound rules must be added. If these are not added, network security groups (NSGs) do not allow access to node IPs and ports.
====

== Configure the Hazelcast Custom Resource

To allow connections from clients, you must configure the `exposeExternally` field of the Hazelcast custom resource. 

The `exposeExternally` field has the following properties:

[cols="20%m,80%a"]
|===
|Property|Description

|type
|The operation mode used to expose Hazelcast members to clients. Valid values are as follows:

- `Unisocket`. Members are exposed through one Kubernetes service that automatically load balances the traffic to Hazelcast members. Use this property if your clients communicate with a single member in the cluster only.
- `Smart`. Each member is exposed through a separate Kubernetes service that allows clients to send requests directly to the members that own a particular partition. Use this property if your clients communicate with all members in the cluster.

|discoveryServiceType
|The type of Kubernetes service used to discover members in a Hazelcast cluster. Valid values are as follows:

- `LoadBalancer`. Default. Hazelcast client configuration: `<load-balancer-external-ip>:5701`.
+
NOTE: If you configure the `discoveryServiceType` to `LoadBalancer`, your Kubernetes cluster must be able to assign public IPs to LoadBalancer services.

- `NodePort`. Hazelcast client configuration: `<node-address>:<node-port>`.

|memberAccess
|The method used by clients to access Hazelcast members. Valid values are as follows:

- `LoadBalancer`. Hazelcast clients are outside the Kubernetes network. Clients can access members using the external IP that is assigned to the `LoadBalancer` service.
- `NodePortExternalIP`. Default. Hazelcast clients are outside the Kubernetes network. Clients can access members using the public IP address assigned to their Kubernetes nodes only.
- `NodePortNodeName`. Hazelcast clients are inside the same network as the Kubernetes nodes. Clients can access a member using the hostname of its Kubernetes node.
|===

NOTE: If you use NodePorts (that is, you have set `discoveryServiceType: NodePort` or `memberAccess: NodePortExternalIP`), the Kubernetes nodes must allow external TCP traffic on node IPs and ports.

== Expose Hazelcast to Smart Clients

A smart client is one that can communicate with all members in the cluster, or with a single member.

Smart clients access partitioned data in a cluster by communicating with the partition owner. This operation mode increases the overall throughput and efficiency of client-cluster communication.

If data is not partitioned, smart clients can communicate with any cluster member.

To allow smart clients to connect to the Hazelcast cluster, you must set the `type` property of the `exposeExternally` field to `smart`.

Kubernetes routes client traffic as follows:

* If the client accesses partitioned data, traffic is routed to the correct member.
* If the client does not access partitioned data, traffic is automatically load balanced.

== Expose Hazelcast to Unisocket Clients

A unisocket client is one that communicates with a single member in the cluster only. 

To allow unisocket clients to connect to the Hazelcast cluster, you must set the `type` property of the `exposeExternally` field to `unisocket`.

Kubernetes automatically load balances client traffic across the Hazelcast cluster.

== Example Configuration

In this example, we configure the connections from smart clients that are to be load balanced for our Hazelcast cluster.

The configuration is as follows:

.Example configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast_expose_externally.yaml[]
----

This configuration creates a load balancer for the discovery service, and a single service for each member. 

With the cluster running, we can use the following command to see created connections:

[source,shell]
----
kubectl get service
----

The result is similar to the following:

```
NAME                 TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)          AGE
hazelcast-sample     LoadBalancer   10.219.246.19    35.230.92.217   5701:30560/TCP   2m11s <1>
hazelcast-sample-0   NodePort       10.219.254.192   <none>          5701:31890/TCP   2m11s <2>
hazelcast-sample-1   NodePort       10.219.247.43    <none>          5701:32310/TCP   2m11s <2>
hazelcast-sample-2   NodePort       10.219.243.16    <none>          5701:32585/TCP   2m11s <2>
```

<1> Discovery service
<2> Individual member access services

To list the external addresses used by the cluster, use the following command:

[source,shell]
----
kubectl get hazelcastendpoint --selector="app.kubernetes.io/instance=hazelcast-sample"
----

The result is similar to the following:

```
NAME                   TYPE        ADDRESS
hazelcast-sample       Discovery   35.238.20.134:5701
hazelcast-sample-0     Member      34.122.120.18:30108
hazelcast-sample-1     Member      34.27.85.200:32012
hazelcast-sample-2     Member      34.173.81.209:30512
hazelcast-sample-wan   WAN         35.238.20.134:5710
```

Smart clients can be configured to connect to the cluster using the external IP address assigned to the load balancer as follows:

[tabs]
====
Java::
+
--
[source, java]
----
ClientConfig config = new ClientConfig();
config.getNetworkConfig().addAddress("35.230.92.217");
HazelcastInstance client = HazelcastClient.newHazelcastClient(config);
----
--

Node.js::
+
--
[source, javascript]
----
const { Client } = require('hazelcast-client');

const clientConfig = {
  network: {
    clusterMembers: [
      '35.230.92.217'
    ]
  }
};
const client = await Client.newHazelcastClient(clientConfig);
----
--

Go::
+
--
[source, go]
----
import (
	"context"

	"github.com/hazelcast/hazelcast-go-client"
)

func main() {
	config := hazelcast.Config{}
	cc := &config.Cluster
	cc.Network.SetAddresses("35.230.92.217")
	cc.Discovery.UsePublicIP = true
	ctx := context.TODO()
	client, err := hazelcast.StartNewClientWithConfig(ctx, config)
	if err != nil {
		panic(err)
	}
}
----
--

Python::
+
--
[source, python]
----
import logging
import hazelcast

logging.basicConfig(level=logging.INFO)

client = hazelcast.HazelcastClient(
    cluster_members=["35.230.92.217"],
    use_public_ip=True,
)
----
--
====
