= Enabling CP Subsystem
:description: CP Subsystem is a component of a Hazelcast cluster that builds a strongly consistent layer for a set of distributed data structures. As well as network partitions, the CP Subsystem withstands server and client failures.

{description}

See xref:hazelcast:cp-subsystem:cp-subsystem.adoc[CP Subsystem] for more detailed information about the configuration and behavior of CP Subsystem component of Hazelcast.

== Configuring CP Subsystem

To enable CP Subsystem you must configure the `cpSubsystem` section in the Hazelcast custom resource. All the members of the Hazelcast cluster will configured as CP Members.

.Example of CP Subsystem
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-cp-subsystem.yaml[]
----

When CP subsystem is enabled, it always enables CP Subsystem Persistence. This means that a PVC must be configured before enabling CP Subsystem.
When the `pvc` section is configured in `cpSubsystem`, a PVC is created and mounted for the CP Subsystem. If you want to use the same PVC for both xref:backup-restore.adoc[Persistence] and CP Subsytem, configure the Persistence but do not configure `pvc` for the CP Subsystem.

.Example of CP Subsystem with Persistence
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-cp-subsystem-presistence.yaml[]
----