= Custom Configuration of Hazelcast Cluster
:description: pass:q[With Hazelcast Operator, you can provide a raw Hazelcast configuration for direct use. This approach is ideal if you want complete control over your configuration or to extend the available Hazelcast Operator configuration.]

{description}

== Configure Hazelcast using Custom Configuration

Your custom configuration must be created as a `ConfigMap` that contains the member configuration.

The configuration must be available in a valid YAML configuration file. For further information on declaring settings for Hazelcast members using a YAML configuration file, refer to xref:hazelcast:configuration:configuring-declaratively.adoc[Member Configuration Files,window=_blank] in the Platform documentation.

In this example, we define custom configuration in a `ConfigMap`.

The configuration is as follows:

[source,yaml]
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-config-cm
data:
  hazelcast: |-
    security:
      enabled: false
      realms:
        - name: simpleRealm
          authentication:
            simple:
              users:
                - username: dev
                  password: 'secret'
                  roles:
                    - root
```

To use the custom configuration, ensure that the name of the `ConfigMap` matches the `customConfigCmName` defined in the Hazelcast custom resource. 
You can find the `customConfigCmName` in the `spec` section of your Hazelcast custom resource, as follows:

[source,yaml]
```
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  customConfigCmName: custom-config-cm
```

== Custom Configuration and Hazelcast Custom Resource

The Hazelcast custom resource configuration and your custom configuration are merged and used to configure the Hazelcast member. 

Custom configuration is designed to work with the Hazelcast custom resource configuration and we recommend that it is not the main source of the your configuration. If you have configured the same feature using both the Hazelcast custom resource and your custom configuration, the Hazelcast custom resource configuration overrides your custom configuration.

For example, we can provide custom configuration to provide access to our `simpleRealm` realm as follows:

[source,yaml]
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-config-cm
data:
  hazelcast: |-
    security:
      enabled: false
      realms:
        - name: simpleRealm
          authentication:
            simple:
              users:
                - username: dev
                  password: 'secret'
                  roles:
                    - root
```

While we define our user code deployment, which uses the realm, in the Hazelcast custom resource as follows:

[source,yaml]
```
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  customConfigCmName: custom-config-cm
  userCodeDeployment:
    bucketConfig:
      secretName: br-secret-gcp
      bucketURI: "gs://operator-custom-class/executorService"
  executorServices:
    - name: service1
  durableExecutorServices:
    - name: service2
  scheduledExecutorServices:
    - name: service3
```

== Limitations

As the custom configuration contains raw Hazelcast configuration, which is not managed by Hazelcast Operator, the following limitations apply:

* You cannot configure a single feature in both the Hazelcast custom resource and the custom configuration. 
+
Any configuration in the Hazelcast custom resouce overrides the configuration in the custom configuration.

* Some Hazelcast features need additional Kubernetes resources to be configured; for example, Persistence requires PVCs. 
+
Custom configuration cannot be used to configure Kubernetes deployments. Therefore, you cannot use custom configuration for these features, which must be configured using only the Hazelcast custom resource.

* Hazelcast Operator communicates with the Hazelcast cluster, therefore the network communication must be configured. 
+
The network must be configured in the Hazelcast custom resource.
+
If you configure network communication in your custom configuration, this can break communication between Hazelcast Operator and the cluster. 
To avoid this, Hazelcast Operator always overrides the networking section in your custom configuration. 
