= Deploy Management Center
:description: In this tutorial, you'll deploy an instance of Management Center using Operator.

{description}

For more information about Management Center, see link:https://docs.hazelcast.com/management-center/latest/getting-started/overview[].

== Prerequisites

* A Kubernetes or OpenShift cluster.
* The link:https://kubernetes.io/docs/tasks/tools/#kubectl[`kubectl`] or link:https://docs.openshift.com/container-platform/latest/cli_reference/openshift_cli/getting-started-cli.html[`oc`] command line tools, configured to communicate with your cluster.
* Operator xref:get-started.adoc[installed and running].

== Deploy Management Center

. Create a Kubernetes secret to hold your license key:
+
.For Kubernetes
[source,shell]
----
kubectl create secret generic hazelcast-license-key --from-literal=license-key=<YOUR_LICENSE_KEY>
----
+
.For Openshift
[source,shell]
----
oc create secret generic hazelcast-license-key --from-literal=license-key=<YOUR_LICENSE_KEY>
----

. Create the `ManagementCenter` custom resource file and name it `management-center.yaml`:
+
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/management-center-with-license-key.yaml[]
----

. Apply the custom resource file to start Management Center:
+
.For Kubernetes
[source,shell]
----
kubectl apply -f management-center.yaml
----
+
.For Openshift
[source,shell]
----
oc apply -f management-center.yaml
----


. After a moment, you can verify that Management Center is up and running by checking the Management Center logs:
+
.For Kubernetes
[source,shell]
----
kubectl logs pod/managementcenter-sample-0
----
+
.For Openshift
[source,shell]
----
oc logs pod/managementcenter-sample-0
----

```
2021-08-26 15:21:04,842 [ INFO] [MC-Client-dev.lifecycle-1] [c.h.w.s.MCClientManager]: MC Client connected to cluster dev.
2021-08-26 15:21:05,241 [ INFO] [MC-Client-dev.event-1] [c.h.w.s.MCClientManager]: Started communication with member: Member [10.36.8.3]:5701 - ccf31703-de3b-4094-9faf-7b5d0dc145b2
2021-08-26 15:21:05,245 [ INFO] [MC-Client-dev.event-1] [c.h.w.s.MCClientManager]: Started communication with member: Member [10.36.7.2]:5701 - e75bd6e2-de4b-4360-8113-040773d858b7
2021-08-26 15:21:05,251 [ INFO] [MC-Client-dev.event-1] [c.h.w.s.MCClientManager]: Started communication with member: Member [10.36.6.2]:5701 - c3d105d2-0bca-4a66-8519-1cacffc05c98
2021-08-26 15:21:07,234 [ INFO] [main] [c.h.w.Launcher]: Hazelcast Management Center successfully started at http://localhost:8080/
```

. To access the Management Center dashboard, navigate to `http://<management-center-ip-address>:8080` in a browser.

// RJS: What do these kubectl get service commands do? Just find the IP address / hostname to use to access MC?

[tabs]
====
Kubernetes::
+
--
[source,shell]
----
MANCENTER_IP=$( kubectl get service managementcenter-sample -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
----
--
Openshift::
+
--
[source,shell]
----
MANCENTER_IP=$( oc get service managementcenter-sample -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
----
--
====

Or if the external IP address of the service is a hostname:

[tabs]
====
Kubernetes::
+
--
[source,shell]
----
MANCENTER_IP=$( kubectl get service managementcenter-sample -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
----
--
Openshift::
+
--
[source,shell]
----
MANCENTER_IP=$( oc get service managementcenter-sample -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
----
--
====

== Next steps

xref:management-center-external-access.adoc[].