= Deploy a Cluster with the Hazelcast Platform Operator for Kubernetes
[[deploying-with-operator]]

The simplest way of installing and operating your Hazelcast Platform cluster in the Kubernetes (and OpenShift) environments is to use Hazelcast Platform Operator.

== Deploy Hazelcast Platform Operator

You can deploy Hazelcast Platform Operator by applying the https://github.com/hazelcast/hazelcast-platform-operator-docs/blob/main/bundle.yaml[`bundle.yaml`] file. Please apply it to your Kubernetes cluster with the following command.

[source,shell]
----
kubectl apply -f https://raw.githubusercontent.com/hazelcast/hazelcast-platform-operator-docs/main/bundle.yaml
----

At this point, your Hazelcast Platform Operator should be up and running. You can check it with the command below.

[source,shell]
----
kubectl logs deployment.apps/hazelcast-platform-controller-manager
----

```
2021-07-14T09:03:40.713Z        INFO    setup   Watching namespace: default
2021-07-14T09:03:41.524Z        INFO    controller-runtime.metrics      metrics server is starting to listen    {"addr": ":8080"}
2021-07-14T09:03:41.524Z        INFO    setup   starting manager
2021-07-14T09:03:41.525Z        INFO    controller-runtime.manager      starting metrics server {"path": "/metrics"}
```

== Customize Namespace (optional)

By default, Hazelcast Operator is installed into the `default` namespace. If you want to change it, you can either replace all `namespace: default` parameters in `bundle.yaml` or use https://kustomize.io/[Kustomize] to achieve it by creating the following `kustomization.yaml` file.

[source,yaml]
----
namespace: <your-namespace>
resources:
- bundle.yaml
----

Then, use Kustomize to apply `bundle.yaml` with the changed namespace.

[source,shell]
----
kubectl apply -k .
----

Note that you'll need to add a parameter `-n <your-namespace>` to all further commands.

== Start Hazelcast cluster

After installing and running Hazelcast Platform Operator, you can create a Hazelcast cluster. First, create `Hazelcast` Custom Resource file as `hazelcast.yaml`.

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast.yaml[]
----

Apply it with the following command to start the Hazelcast cluster.

[source,shell]
----
kubectl apply -f hazelcast.yaml
----

After some time, you can verify that Hazelcast cluster is up and running by checking the Hazelcast member logs.

[source,shell]
----
kubectl logs pod/hazelcast-sample-0
----

```
Members {size:3, ver:3} [
        Member [10.36.8.3]:5701 - ccf31703-de3b-4094-9faf-7b5d0dc145b2 this
        Member [10.36.7.2]:5701 - e75bd6e2-de4b-4360-8113-040773d858b7
        Member [10.36.6.2]:5701 - c3d105d2-0bca-4a66-8519-1cacffc05c98
]
```

== Start Hazelcast Enterprise Cluster

Hazelcast Enterprise requires having the license key specified as Kubernetes Secret.

NOTE: If you don't have Hazelcast Enterprise License Key, you can link:http://trialrequest.hazelcast.com/[request one] from the Hazelcast website.

[source,shell]
----
kubectl create secret generic hazelcast-license-key --from-literal=license-key=<YOUR LICENSE KEY>
----

Finally, you can create `Hazelcast` Custom Resource file as `hazelcast-enterprise.yaml`.

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-enterprise.yaml[]
----

Apply it with the following command to start the Hazelcast cluster.

[source,shell]
----
kubectl apply -f hazelcast-enterprise.yaml
----

After a moment, you can verify that Hazelcast cluster is up and running by checking the Hazelcast member logs.

[source,shell]
----
kubectl logs pod/hazelcast-sample-0
----

```
Members {size:3, ver:3} [
        Member [10.36.8.3]:5701 - ccf31703-de3b-4094-9faf-7b5d0dc145b2 this
        Member [10.36.7.2]:5701 - e75bd6e2-de4b-4360-8113-040773d858b7
        Member [10.36.6.2]:5701 - c3d105d2-0bca-4a66-8519-1cacffc05c98
]
```

== Check that the Hazelcast Cluster is Running

To check if a cluster is running, see the `status` field of the Hazelcast resource.

The status can be checked using the command below.

[source,shell]
----
kubectl get hazelcast
----

```
NAME        STATUS    MEMBERS
hazelcast   Running   3/3
```

You can use the following command for the long format.

[source,shell]
----
kubectl get hazelcast -o=yaml
----

[source,yaml,subs="attributes+"]
----
status:
  hazelcastClusterStatus:
    readyMembers: 3/3
  phase: Running
----

The `phase` field represents the current status of the cluster, and can contain any of the following values:

* `Running`: The cluster is up and running.
* `Pending`: The cluster is in the process of starting.
* `Failed`: An error occurred while starting the cluster.

Any additional info such as validation errors will be provided in the `message` field.

The `readyMembers` field represents the number of Hazelcast members that are connected to the cluster.

WARNING: Use the `readyMembers` field only for informational purposes. This field is not always accurate. Some members may have joined or left the cluster since this field was last updated.

== Start Management Center

You can monitor the Hazelcast cluster by starting the Management Center. You can create `ManagementCenter` custom resource file as `management-center.yaml`.

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/management-center.yaml[]
----
WARNING: StatefulSet does not support updates to `volumeClaimTemplates` field, so `persistence` field should be set only at the creation of the custom resource. Any update to the `persistence` field will not affect the Management Center.

WARNING: `hazelcastClusters` field does not support deleting clusters from the custom resource. If you want to remove a cluster from the Management Center, you can do it from the Management Center UI.

Apply it with the following command to start Management Center.

[source,shell]
----
kubectl apply -f management-center.yaml
----

After a moment, you can verify that Management Center is up and running by checking the Management Center logs.

[source,shell]
----
kubectl logs managementcenter-sample-0
----

```
2021-08-26 15:21:04,842 [ INFO] [MC-Client-dev.lifecycle-1] [c.h.w.s.MCClientManager]: MC Client connected to cluster dev.
2021-08-26 15:21:05,241 [ INFO] [MC-Client-dev.event-1] [c.h.w.s.MCClientManager]: Started communication with member: Member [10.36.8.3]:5701 - ccf31703-de3b-4094-9faf-7b5d0dc145b2
2021-08-26 15:21:05,245 [ INFO] [MC-Client-dev.event-1] [c.h.w.s.MCClientManager]: Started communication with member: Member [10.36.7.2]:5701 - e75bd6e2-de4b-4360-8113-040773d858b7
2021-08-26 15:21:05,251 [ INFO] [MC-Client-dev.event-1] [c.h.w.s.MCClientManager]: Started communication with member: Member [10.36.6.2]:5701 - c3d105d2-0bca-4a66-8519-1cacffc05c98
2021-08-26 15:21:07,234 [ INFO] [main] [c.h.w.Launcher]: Hazelcast Management Center successfully started at http://localhost:8080/
```

To access the Management Center dashboard, open the browser at address `http://$MANCENTER_IP:8080`.

[source,shell]
----
MANCENTER_IP=$( kubectl get service managementcenter-sample -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
----

== Clean up

You can run the commands below to remove Hazelcast cluster and  Management Center.

[source,shell]
----
kubectl delete -f hazelcast.yaml
kubectl delete -f management-center.yaml
----

If you installed Hazelcast Enterprise, run the following commands to remove Hazelcast Enterprise cluster and Hazelcast License Key Secret.

[source,shell]
----
kubectl delete -f hazelcast-enterprise.yaml
kubectl delete secret hazelcast-license-key
----

Finally, run the command below to delete Hazelcast Platform Operator deployment.

[source,shell]
----
kubectl delete -f https://raw.githubusercontent.com/hazelcast/hazelcast-platform-operator-docs/main/bundle.yaml
----
