= Install Operator and deploy a Hazelcast cluster
:description: This topic explains how to deploy a Hazelcast cluster using Operator for Kubernetes.

{description}

NOTE: If you want to migrate from the Hazelcast Helm Chart, see xref:migrating-from-helm.adoc[].

== Overview

As part of the deployment process, you will install the custom resource definitions (CRDs) that describe the Hazelcast resource types.

A CRD is a Kubernetes feature that allows you to create custom resources that extend the Kubernetes API. CRDs allow new types of resources tailored to specific use cases to be created, without adding another API server. They also provide detailed reports on the configuration content of a CRD to any authorized Kubernetes API consumer. Using CRDs, you can:

* Introduce unique objects or types into the Kubernetes cluster.
* Create platform resources on top of Kubernetes.
* Build and use platforms through self-service activity.

For example, the `clusterName` field in the Hazelcast CRD can be used to rename a cluster.

CRDs are expressed in YAML format, just like standard Kubernetes entities. The Kubernetes API server processes and manages CRDs the same way it does with built-in resources.

For more information about the Operator CRD, see xref:api-ref.adoc[].

== Prerequisites

* A Kubernetes or OpenShift cluster.
* The link:https://kubernetes.io/docs/tasks/tools/#kubectl[`kubectl`] or link:https://docs.openshift.com/container-platform/latest/cli_reference/openshift_cli/getting-started-cli.html[`oc`] command line tools, configured to communicate with your cluster.
* link:https://helm.sh/docs/intro/install[`Helm`].
* A Hazelcast Enterprise license key. If you don't have a license key, you can request one from the link:http://trialrequest.hazelcast.com/[Hazelcast website].

NOTE: Because CRDs are global resources, they may need to be installed by an administrator.

== Install and run Operator

Operator is installed using a Helm chart.

NOTE: Hazelcast images are hosted at `docker.io/hazelcast` and `registry.connect.redhat.com/hazelcast`. The Docker images are used by default. If you need to fetch images from Red Hat or a private mirror, you can xref:image-registry.adoc[change the default image registry].

. Add the Hazelcast Helm Charts repository to your Helm repository list:

+
[source,shell]
----
helm repo add hazelcast https://hazelcast-charts.s3.amazonaws.com/
helm repo update
----

. You can either deploy Operator at the same time as the CRDs or separately.

+
[tabs]
====
Cluster-wide installation::
+
--
Run the following command to *deploy Operator and the CRDs together*. By default, Operator watches all namespaces. Use the `watchedNamespaces` variable to change this configuration if needed.

[source,shell,subs="attributes"]
----
helm install operator hazelcast/hazelcast-platform-operator --version={operator-chart-version} \
    --set=installCRDs=true
----
--

Restricted installation::
+
--
Run the following commands to *deploy Operator and the CRDs separately*.

[source,shell,subs="attributes"]
----
helm install operator-crds hazelcast/hazelcast-platform-operator-crds --version={operator-chart-version}
----

After installing CRDs, install Operator by running the following command. This operation requires only namespace-scoped permissions for `hz-system`, `ns-1` and `ns-2` namespaces, which should already exist.

[source,shell,subs="attributes+"]
----
helm install operator hazelcast/hazelcast-platform-operator --version={operator-chart-version} -n hz-system \
    --set=createClusterScopedResources=false \#<1>
    --set=webhook.enabled=false \#<2>
    --set=enableHazelcastNodeDiscovery=false \#<3>
    --set=installCRDs=false \
    --set=watchedNamespaces="{ns-1, ns-2}"
----
<1> Disabling `createClusterScopedResources` means that the management of resources by Operator is constrained to specified namespaces, improving security.
<2> Disabling `webhook.enabled` means that webhooks cannot be used. The cluster-wide permissions required for webhooks conflict with the restrictions on cluster-scoped resource creation.
<3> Disabling `enableHazelcastNodeDiscovery` means that Operator does not automatically discover nodes across all namespaces. This limits the use of `NODE_AWARE` in `highAvailabilityMode` and of `NodePort` in `discoveryServiceType`, both of which depend on broader node discovery.
--
====

+
TIP: You can view all configuration options by running the following command: `helm show values hazelcast/hazelcast-platform-operator`

+
. Monitor the Operator logs. At this point, Operator should be up and running. To check:

+
[tabs]
====
Kubernetes::
+
--
[source,shell]
----
kubectl logs deployment.apps/operator-hazelcast-platform-operator -n hz-system
----
--
Openshift::
+
--
[source,shell]
----
oc logs deployment.apps/operator-hazelcast-platform-operator -n hz-system
----
--
====

== Start the Hazelcast cluster

After installing and running Operator, you can create a Hazelcast cluster. 

. Create a Kubernetes secret to hold your license key.
+
.For Kubernetes
[source,shell]
----
kubectl create secret generic hazelcast-license-key --from-literal=license-key=<YOUR LICENSE KEY>
----
+
.For Openshift
[source,shell]
----
oc create secret generic hazelcast-license-key --from-literal=license-key=<YOUR LICENSE KEY>
----

. Create the `Hazelcast` custom resource file and name it `hazelcast-enterprise.yaml`.
+
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-enterprise.yaml[]
----

. Apply the custom resource to start the Hazelcast cluster.
+
.For Kubernetes
[source,shell]
----
kubectl apply -f hazelcast-enterprise.yaml
----
+
.For Openshift
[source,shell]
----
oc apply -f hazelcast-enterprise.yaml
----

. Verify that Hazelcast cluster is up and running by checking the Hazelcast member logs.
+
.For Kubernetes
[source,shell]
----
kubectl logs pod/hazelcast-sample-0
----
+
.For Openshift
[source,shell]
----
oc logs pod/hazelcast-sample-0
----

You should see the following:

```
Members {size:3, ver:3} [
        Member [10.36.8.3]:5701 - ccf31703-de3b-4094-9faf-7b5d0dc145b2 this
        Member [10.36.7.2]:5701 - e75bd6e2-de4b-4360-8113-040773d858b7
        Member [10.36.6.2]:5701 - c3d105d2-0bca-4a66-8519-1cacffc05c98
]
```

== Check that the Hazelcast cluster is running

To check if a cluster is running, see the `status` field of the Hazelcast resource. You can check the status using `get hazelcast`:

[tabs]
====
Kubernetes::
+
--
[source,shell]
----
kubectl get hazelcast
----
--
Openshift::
+
--
[source,shell]
----
oc get hazelcast
----
--
====

```
NAME               STATUS    MEMBERS
hazelcast-sample   Running   3/3
```

You can also see the status in YAML format:

// RJS: Does this provide more info or is it just a different format?

[tabs]
====
Kubernetes::
+
--
[source,shell]
----
kubectl get hazelcast hazelcast-sample -o=yaml
----
--
Openshift::
+
--
[source,shell]
----
oc get hazelcast hazelcast-sample -o=yaml
----
--
====

[source,yaml,subs="attributes+"]
----
status:
  hazelcastClusterStatus:
    readyMembers: 3/3
  phase: Running
----

The `phase` field represents the current status of the cluster, and can contain any of the following values:

* `Running`: The cluster is up and running.
* `Pending`: The cluster is in the process of starting.
* `Failed`: An error occurred while starting the cluster.

Any additional information, such as validation errors, will be provided in the `message` field.

The `readyMembers` field represents the number of Hazelcast members that are connected to the cluster.

== Next steps

xref:connect-outside-kubernetes.adoc[Expose Hazelcast clusters outside Kubernetes] so you can connect external clients to them.
