= Deploy a Cluster with Hazelcast Operator
:description: In this tutorial, we deploy a Hazelcast cluster on either Kubernetes or Red Hat OpenShift using Hazelcast Operator.

{description}

== Before you Begin

You need one of the following:

* A Kubernetes cluster, with the `kubectl` command-line tool configured to communicate with your cluster. For further information on getting started with Kubernetes and configuring `kubectl`, refer to the link:https://kubernetes.io/docs/home/[Kubernetes documentation,window=_blank].
* An OpenShift cluster with the `oc` command-line tool configured to communicate with your cluster. For further information on getting started with OpenShift configuring `oc`, refer to the link:https://docs.openshift.com/[OpenShift documentation,window=_blank].

You also need the Helm package manager for Kubernetes. For further information on installing and using Helm, refer to the link:https://helm.sh/docs/[Helm documentation,window=_blank]. You can check the version of Helm you have installed using the following command:

[source,shell]
----
helm list
----

NOTE: Remove all custom resource definitions (CRDs) before continuing.

== Step 1. Deploy Hazelcast Operator

From release 5.6.0, you can use a Helm chart to install the Hazelcast Operator as follows:

. Add the link:https://github.com/hazelcast/charts[Hazelcast Helm Charts repository] to your Helm repository list using the following command:

+
[source,shell]
----
helm repo add hazelcast https://hazelcast-charts.s3.amazonaws.com/
helm repo update
----

. Deploy Hazelcast Operator and CRDs. You can deploy these simultaneously (cluster-wide installation) or separately (restricted installation), as follows:

+
NOTE: CRDs are global resources. This means that administrator rights might be required to install them.

+
[tabs]
====
Cluster-wide Installation::
+
--
By default, Hazelcast Operator watches all namespaces. To specify namespaces to watch, configure the `watchedNamespaces` variable.

To deploy the Hazelcast Operator and the CRDs simultaneously, use the following command: 

[source,shell,subs="attributes"]
----
helm install operator hazelcast/hazelcast-platform-operator --version={operator-chart-version} \
    --set=installCRDs=true
----
--

Restricted Installation::
+
--
You might require administrator rights to deploy the CRDs. You only require namespace-scoped permissions for the `hz-system`, `ns-1`, and `ns-2` namespaces to install Hazelcast Operator. 

NOTE: You must have added these namespaces to your cluster configuration. If this has not been done, the installation fails. 

The CRDs must be successfully installed before installing Hazelcast Operator.

To deploy Hazelcast Operator and the CRDs separately, complete the following steps:

. Deploy the CRDs using the following command: 
+
[source,shell,subs="attributes"]
----
helm install operator-crds hazelcast/hazelcast-platform-operator-crds --version={operator-chart-version}
----

. Install Hazelcast Operator in the namespaces using the following command:

[source,shell,subs="attributes+"]
----
helm install operator hazelcast/hazelcast-platform-operator --version={operator-chart-version} -n hz-system \
    --set=createClusterScopedResources=false \ <1>
    --set=webhook.enabled=false \ <2>
    --set=enableHazelcastNodeDiscovery=false \ <3>
    --set=installCRDs=false \
    --set=watchedNamespaces="{ns-1, ns-2}"
----
<1> Disabling `createClusterScopedResources` means that the management of resources by Operator is constrained to specified namespaces. This enhances both security and compliance.
<2> Disabling `webhook.enabled` means that webhooks cannot be used. This is needed as the cluster-wide permissions required for webhooks conflict with our restrictions on cluster-scoped resource creation.
<3> Disabling `enableHazelcastNodeDiscovery` means that Operator does not automatically discover nodes across all namespaces. This limits the use of `NODE_AWARE` in `highAvailabilityMode` and of `NodePort` in `discoveryServiceType`, both of which depend on broader node discovery.
--
====

+
TIP: You can view all configuration options using the `helm show values hazelcast/hazelcast-platform-operator` command.

+
. Monitor the operator logs. With Hazelcast Operator running, you can monitor the logs as follows:

+
[tabs]
====
Kubernetes::
+
--
[source,shell]
----
kubectl logs deployment.apps/operator-hazelcast-platform-operator
----
--
Openshift::
+
--
[source,shell]
----
oc logs deployment.apps/operator-hazelcast-platform-operator
----
--
====

== Step 2. Start the Hazelcast Cluster

After installing and starting Hazelcast Operator, you can create and start a Hazelcast cluster as follows:

[tabs]
====
Enterprise Edition::
+
--
Hazelcast Platform (Enterprise Edition) requires a license key. 

If you don't have a license key, you can request a trial license from the link:http://trialrequest.hazelcast.com/[Hazelcast website].

. Create a Kubernetes secret to hold your license key as follows:
+
.For Kubernetes
[source,shell]
----
kubectl create secret generic hazelcast-license-key --from-literal=license-key=<YOUR LICENSE KEY>
----
+
.For Openshift
[source,shell]
----
oc create secret generic hazelcast-license-key --from-literal=license-key=<YOUR LICENSE KEY>
----

. Create the Hazelcast custom resource file with the following content, and save it in your repository as _hazelcast-enterprise.yaml_:
+
TIP: This is the Hazelcast custom resource referred to throughout this documentation.
+
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-enterprise.yaml[]
----

. Apply the custom resource file to start the Hazelcast cluster as follows:
+
.For Kubernetes
[source,shell]
----
kubectl apply -f hazelcast-enterprise.yaml
----
+
.For Openshift
[source,shell]
----
oc apply -f hazelcast-enterprise.yaml
----

. Verify that Hazelcast cluster is running by viewing the Hazelcast member logs as follows:
+
.For Kubernetes
[source,shell]
----
kubectl logs pod/hazelcast-sample-0
----
+
.For Openshift
[source,shell]
----
oc logs pod/hazelcast-sample-0
----

If the cluster is running, the result is similar to the following:

```
Members {size:3, ver:3} [
        Member [10.36.8.3]:5701 - ccf31703-de3b-4094-9faf-7b5d0dc145b2 this
        Member [10.36.7.2]:5701 - e75bd6e2-de4b-4360-8113-040773d858b7
        Member [10.36.6.2]:5701 - c3d105d2-0bca-4a66-8519-1cacffc05c98
]
```

--

Community Edition::
+
--

. Create the Hazelcast custom resource file with the following content, and save it in your repository as _hazelcast.yaml_:
+
TIP: This is the Hazelcast custom resource referred to throughout this documentation.
+
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast.yaml[]
----

. Apply the custom resource to start the Hazelcast cluster as follows:
+

.For Kubernetes
[source,shell]
----
kubectl apply -f hazelcast.yaml

----
+
.For Openshift
[source,shell]
----
oc apply -f hazelcast.yaml
----


. Verify that the cluster is running using the Hazelcast member logs as follows:
+

.For Kubernetes
[source,shell]
----
kubectl logs pod/hazelcast-sample-0
----
+
.For Openshift
[source,shell]
----
oc logs pod/hazelcast-sample-0
----

If the cluster is running, the result is similar to the following:

```
Members {size:3, ver:3} [
        Member [10.36.8.3]:5701 - ccf31703-de3b-4094-9faf-7b5d0dc145b2 this
        Member [10.36.7.2]:5701 - e75bd6e2-de4b-4360-8113-040773d858b7
        Member [10.36.6.2]:5701 - c3d105d2-0bca-4a66-8519-1cacffc05c98
]
```
--
====

== Step 3. Check that the Hazelcast Cluster is Running

You can use the `status` field of the Hazelcast custom resource to check if a cluster is running as follows:

[tabs]
====
Kubernetes::
+
--
[source,shell]
----
kubectl get hazelcast
----
--
Openshift::
+
--
[source,shell]
----
oc get hazelcast
----
--
====

If the custom resource is running, the result is similar to the following:

```
NAME               STATUS    MEMBERS
hazelcast-sample   Running   3/3
```

You can get more detailed information on the status as follows:


[tabs]
====
Kubernetes::
+
--
[source,shell]
----
kubectl get hazelcast hazelcast-sample -o=yaml
----
--
Openshift::
+
--
[source,shell]
----
oc get hazelcast hazelcast-sample -o=yaml
----
--
====

The result is similar to the following:

[source,yaml,subs="attributes+"]
----
status:
  hazelcastClusterStatus:
    readyMembers: 3/3
  phase: Running
----

In the detailed information, the `phase` field provides the current status of the cluster, and can contain any of the following values:

* `Running`: The cluster is up and running.
* `Pending`: The cluster is in the process of starting.
* `Failed`: An error occurred while starting the cluster.

If additional information is available, such as validation errors, this is provided in the `message` field.

The number of Hazelcast members that are connected to the cluster is provided in the `readyMembers` field.

NOTE: The `readyMembers` field is for informational purposes only. This field is not always accurate, as some members might have joined or left the cluster since this field was last updated.


== Step 4. Clean up

You can remove the Hazelcast cluster as follows:

[tabs]
====
Kubernetes::
+
--
[source,shell]
----
kubectl delete -f hazelcast.yaml
----
--
Openshift::
+
--
[source,shell]
----
oc delete -f hazelcast.yaml
----
--
====

If you installed Hazelcast Platform Enterprise Edition, you can remove the Hazelcast cluster and license key secret as follows:

[tabs]
====
Kubernetes::
+
--
[source,shell]
----
kubectl delete -f hazelcast-enterprise.yaml
kubectl delete secret hazelcast-license-key
----
--
Openshift::
+
--
[source,shell]
----
oc delete -f hazelcast-enterprise.yaml
oc delete secret hazelcast-license-key
----
--
====

Remove the CRDs and Hazelcast Operator as follows:

* If you installed the CRDs and Hazelcast Operator simultaneously, use the following command:

+
[source,shell]
----
helm uninstall operator
----

* If you installed the CRDs and Hazelcast Operator separately, use the following command to remove the CRDs:

+
[source,shell]
----
helm uninstall operator-crds
----

== Next Steps

Learn how to xref:connect-outside-kubernetes.adoc[expose Hazelcast clusters outside Kubernetes], so that you can connect external clients to them.
