= Configuring Hazelcast Parameters

You can configure Hazelcast parameters using the `properties` field in the CRD spec.

It is worth highlighting the following system properties:

- Hazelcast supports IPv6 addresses seamlessly, although IPv6 support is switched off by default. To enable IPv6 addressing in Hazelcast and set up a Hazelcast cluster on an IPv6-stack Kubernetes Cluster, you'll need extra configurations. These configurations can be passed through properties. The provided example below shows how to create an IPv6 Hazelcast cluster using the Hazelcast Platform Operator.
+
.IPv6 Example configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-ipv6.yaml[]
----

- During a rolling upgrade, the cluster is shutdown gracefully to prevent data loss. You can configure this using the link:https://docs.hazelcast.com/hazelcast/5.3/system-properties#hazelcast.graceful.shutdown.max.wait[hazelcast.graceful.shutdown.max.wait system property].
+
Example Configuration:
+
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/properties.yaml[]
----

- The final step in the link:https://docs.hazelcast.com/hazelcast/5.3/maintain-cluster/rolling-upgrades#rolling-upgrade-procedure[rolling upgrade procedure] is to trigger a rolling upgrade on the cluster. Hazelcast Platform Operator triggers it automatically by setting `hazelcast.cluster.version.auto.upgrade.enabled` to `true` by default, and it cannot be changed.

- `hazelcast.persistence.auto.cluster.state` set to `true` by default and `hazelcast.persistence.auto.cluster.state.strategy` is set to `NO_MIGRATION` by default. They cannot be changed.