= Configure highly available Hazelcast clusters
:description: High Availability mode avoids data loss when the Kubernetes node or availability zone is down. You can configure partition groups with High Availability mode to add resilience to your clusters.

{description}

Partition groups let you choose where Hazelcast members store backups of a data partition. You can configure a partition group to back up data to a member in a different availability zone (ZONE_AWARE) or on a different Kubernetes node (NODE_AWARE). See xref:hazelcast:clusters:partition-group-configuration.adoc[Partition Group configuration] for details.

When using either type of partition grouping (ZONE_AWARE or NODE_AWARE) with a Hazelcast cluster that spans multiple availability zones and nodes, you must have an equal number of members in each zone or node. Otherwise, distribution of partitions between members will be uneven.

The `highAvailabilityMode` parameter allows you to specify partition groups and to automatically distribute members across availability zones and nodes using the Kubernetes policy `topologySpreadConstraints`.

== Configure High Availability mode

High Availability mode supports the following configuration options.

[cols="20%m,80%a"]
|===
|Field|Description

|`highAvailabilityMode`
|Configuration for partition groups and Kubernetes scheduling policy::

  - `NODE`: the partition-group is configured as NODE_AWARE and `topologySpreadConstraints` is added into the statefulset:

[source,yaml]
```
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
          matchLabels:
            app.kubernetes.io/name: hazelcast
            app.kubernetes.io/instance: hazelcast
            app.kubernetes.io/managed-by: hazelcast-platform-operator
```

  - `ZONE`: the partition-group is configured as ZONE_AWARE and `topologySpreadConstraints` is added into the statefulset:
[source,yaml]
```
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
          matchLabels:
            app.kubernetes.io/name: hazelcast
            app.kubernetes.io/instance: hazelcast
            app.kubernetes.io/managed-by: hazelcast-platform-operator
```

|===

=== Example configuration

The following example configures ZONE_AWARE high availability.

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-high-availability-mode.yaml[]
----

== High Availability mode and multi-member routing

`MULTI_MEMBER` routing allows a client to connect to a subset of members that is determined by a grouping strategy. To benefit from `MULTI_MEMBER` routing, you must enable High Availability mode, because this parameter is used to determine partition groups. In addition, if the `MULTI_MEMBER` routing mode is used on the client side, `exposeExternally.type` must be set to `smart` in the Hazelcast CR.

Example server and client configuration using `MULTI_MEMBER` routing:

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-high-availability-mode-multi-member-routing.yaml[]
----

[tabs]
====
Java::
+
--
[source, java]
----
ClientConfig clientConfig = new ClientConfig();
ClientNetworkConfig networkConfig = clientConfig.getNetworkConfig();
networkConfig.getClusterRoutingConfig().setRoutingMode(RoutingMode.MULTI_MEMBER);
// PARTITION_GROUPS is the default strategy, so it does not need to be explicitly defined
networkConfig.getClusterRoutingConfig().setRoutingStrategy(RoutingStrategy.PARTITION_GROUPS);
----
--

XML::
+
--
[source, xml]
----
...
    <network>
        <cluster-routing mode="MULTI_MEMBER">
          <grouping-strategy>PARTITION_GROUPS</grouping-strategy>
        </cluster-routing>
    </network>
...
----
--

YAML::
+
--
[source, yaml]
----
  network:
    cluster-routing:
      mode: MULTI_MEMBER
      grouping-strategy: PARTITION_GROUPS
----
--
====
