= Hazelcast Operator
:!page-pagination:
:description: Hazelcast Operator extends cluster behaviour without the need to modify Kubernetes code directly. This simplifies working with Hazelcast clusters on Kubernetes and Red Hat OpenShift. 

{description}

By eliminating the need for manual deployment and life-cycle management, Hazelcast Operator helps your development and DevOps teams to automate common Kubernetes management tasks for your Hazelcast clusters. For example, you can use Hazelcast Operator to automate the following tasks:

* Configuration
* Creation
* Scaling
* Recovery

To get the most from this documentation, we recommend that you have completed the following Kubernetes tutorials, or have experience using Kubenetes:

* link:https://kubernetes.io/docs/tutorials/kubernetes-basics[Kubernetes Basics,window=_blank]
* link:https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/[StatefulSet Basics,window=_blank]

Hazelcast also recommends that you understand how Kubernetes works. For further information on the concepts used by Kubernetes, refer to the link:https://kubernetes.io/docs/concepts/[Kubernetes documentation,window=_blank]. 

////
Content to consider for this page:

Requirements (supported versions of Platform, Kubernetes, Openshift, supported managed services such as GKE)
High-level architectural diagram of components, workflow
Short discussion of the difference between the Helm chart and the operator
Known limitations
////

== Community Support

Community support is for every Hazelcast user. You can use the following channels to get community support:

* https://github.com/hazelcast/hazelcast-platform-operator[Hazelcast Operator GitHub^] (for reporting issues through our GitHub repository)
* https://slack.hazelcast.com/[Hazelcast Community Slack^]

== Customer Support

Customer support is for paying Hazelcast customers. For further information on Hazelcast's comprehensive 24/7 support offerings, refer to the https://hazelcast.com/services/support/[Hazelcast website^].

A support subscription from Hazelcast allows you to get the most value from Hazelcast Operator. Our rapid response times to technical
support inquiries, access to critical software patches, and other services allow you to improve productivity and quality.

When you have an account set up, you can https://support.hazelcast.com/s/[open a support request].

When submitting a ticket to the team, provide the following information:

* *A clear summary of the issue*. Add this in the title of your issue to help the team to direct the issue to the right expert.
* *The steps to take to reproduce the issue*, if possible. If you aren't sure, describe the sequence of events that led to the problem. Your test case, or use case is also very helpful.
* *A full description of the problem and any error* that was encountered. Your test and use cases can provide us with guidance on where we need to focus our investigations. Include the time at which you encountered the issue.
* *Hazelcast Logs*. Ensure that all your environments capture Hazelcast diagnostics logs, which we will use to diagnose your issues. If your environments are not capturing diagnostics logs, update them and capture diagnostics logs before opening the ticket. Do not truncate the diagnostic logs. The process, health monitoring, and networking logs also contain useful information, and should be attached along with the diagnostic logs when you open a ticket. Ensure that system and environment details captured at system startup are included, even in truncated logs, and that the provided logs include entries for the time at which you encountered the issue. 
* *Relevant screenshots and/or error messages*.
* *Thread dumps for all members*.
* *Heap dumps*.
* *The severity of the issue*, as follows:

** `PROD` issues affecting production: severity 1.

** `DEV` issues: severity 3 and priority low.

** Other issues, such as questions or documentation feedback: severity 2 or 3 depending on severity.

The more information that you can provide, the faster Hazelcast Customer Support can respond to your issue. Hazelcast appreciates your help and timely response to any further communication. 

== Getting Started

xref:get-started.adoc[].




