= Hazelcast Platform Operator
:!page-pagination:
:description: By eliminating the need for manual deployment and life-cycle management, Hazelcast Platform Operator simplifies working with Hazelcast clusters on Kubernetes and Red Hat OpenShift.

{description}

Hazelcast Platform Operator allows your development and DevOps teams to automate common management tasks for your Hazelcast clusters on Kubernetes and Red Hat OpenShift. For example, you can use Hazelcast Platform Operator to automate the following tasks:

* Configuration
* Creation
* Scaling
* Recovery

This documentation assumes an intermediate knowledge of Kubernetes.

////
Content to consider for this page:

Requirements (supported versions of Platform, Kubernetes, Openshift, supported managed services such as GKE)
High-level architectural diagram of components, workflow
Short discussion of the difference between the Helm chart and the operator
Known limitations
////

== Support

Community support is for every Hazelcast user. You can use the following channels to get community support:

*  https://github.com/hazelcast/hazelcast[Hazelcast GitHub^] (for reporting issues through our GitHub repository)
* https://slack.hazelcast.com/[Hazelcast Community Slack^]
* https://groups.google.com/forum/#!forum/hazelcast[Mail Group^]
* http://www.stackoverflow.com/[StackOverflow^]

== Getting Started

xref:get-started.adoc[].




