= Hazelcast Platform Operator
:!page-pagination:
:description: By eliminating the need for manual deployment and life-cycle management, Hazelcast Platform Operator simplifies working with Hazelcast clusters on Kubernetes and Red Hat OpenShift.

{description}

Hazelcast Platform Operator allows your development and DevOps teams to automate common management tasks for your Hazelcast clusters on Kubernetes and Red Hat OpenShift. For example, you can use Hazelcast Platform Operator to automate the following tasks:

* Configuration
* Creation
* Scaling
* Recovery

This documentation assumes an intermediate knowledge of Kubernetes.

== Supported Platform Versions

=== Kubernetes Versions

Hazelcast Platform Operator supports the following Kubernetes versions:

- 1.26
- 1.27
- 1.28
- 1.29
- 1.30

Every Hazelcast Platform Operator version is tested against these Kubernetes versions.

=== OpenShift Versions

Hazelcast Platform Operator supports following OpenShift versions:

- 4.13
- 4.14
- 4.15
- 4.16

////
Content to consider for this page:

Requirements (supported versions of Platform, Kubernetes, Openshift, supported managed services such as GKE)
High-level architectural diagram of components, workflow
Short discussion of the difference between the Helm chart and the operator
Known limitations
////

== Get Started

xref:get-started.adoc[].
