= What is Hazelcast Platform Operator?
:!page-pagination:
:description: Operator simplifies working with Hazelcast clusters on Kubernetes and Red Hat OpenShift by eliminating the need for manual deployment and lifecycle management.

{description}

Operator automates common management tasks, making it easier to work with Hazelcast clusters in cloud-native environments.

For example, you can use Operator to automate the following tasks:

* Creation
* Configuration
* Scaling
* Recovery

Hazelcast, Kubernetes and OpenShift are complex systems that you will need a good understanding of before you use Operator. For more information about Hazelcast, see the link:https://docs.hazelcast.com/hazelcast/latest/what-is-hazelcast[Hazelcast Platform documentation].

== Features and benefits

By using Operator, teams can benefit from a more streamlined, automated, and Kubernetes-native approach to managing Hazelcast clusters. This helps to reduce complexity and improve operational efficiency. Operator enables:

* Kubernetes-native experience: Makes Hazelcast Platform Kubernetes-native by using Custom Resource Definitions (CRDs).
* Automated configuration and management: Handles creation, configuration, scaling and recovery tasks automatically.
* Simplified persistence, backup and restore: Makes it easier to enable persistence on Hazelcast and manage backup and restore on Kubernetes.
* Support for WAN Replication: Simplifies the configuration and management of WAN Replication.
* Dynamic configuration: Allows updating configuration without cluster restarts.
* Rich API: Provides an intuitive API that abstracts complex Hazelcast configuration, focusing on features rather than specific settings.
* Automatic feature lifecycle control: Simplifies advanced operations such as cluster backups without manual intervention.
* Platform-specific optimizations: Automatically applies optimal configurations based on the runtime environment.

== Supported versions

Operator only supports Enterprise Edition deployments of Hazelcast Platform. Community Edition does not support Operator.  

=== Kubernetes versions

Operator supports Kubernetes versions 1.26 - 1.33.

=== OpenShift versions

Operator supports OpenShift versions 4.13 - 4.18.

== Get started

To get started, xref:get-started.adoc[].

////
Content to consider for this page:

Requirements (supported versions of Platform, Kubernetes, Openshift, supported managed services such as GKE)
High-level architectural diagram of components, workflow
Short discussion of the difference between Helm charts and Operator
Known limitations
////