= Save the State of Data Pipelines
:description: When processing data pipelines, the states are saved and used by the pipelines. These states ensure the accuracy and integrity of the data processing operations. You can use Hazelcast Operator to export a Jet snapshot to save the processing states, and to restore them.
:page-enterprise: true

{description}

A snapshot captures the state of a running Jet job at a particular point in time. This provides a consistent record of in-flight computations and processed data, which you can use for various purposes including fault tolerance, job migration, or analysis.

A snapshot records the following:

* All data in transit.
* The internal state of the members processing the job.

This means that if the job fails or is restarted, it is restored to the state captured by the snapshot. This supports fault-tolerant processing and helps to ensure data integrity.

== Configure the JetJobSnapshot Resource

Jet job snapshots are configured using the following fields:

[cols="20%m,80%a"]
|===
|Field|Description

|name
|The name of the exported snapshot. If this field is empty, the custom resource name is used to create the name of the snapshot. You cannot update the name after the object has been created.

|cancelName
|Whether to cancel the job after exporting a snapshot. 
By default, set to `false`, which does not cancel the job after exporting the snapshot. If you want to cancel the job after exporting a snapshot, set to `true`.

|jetJobResourceName
|The name of the `JetJob` custom resource from which the snapshot is exported.

|===

For further information on the fields used to configure Jet snapshots, see xref::api-ref.adoc#jetjobsnapshotspec[JetJobSnapshotSpec] in the Hazelcast Operator API Reference

== Export a Snapshot

The Jet job you want to export must have a status of `Running`.

In this example, we configure `JetJobSnapshot` to export the snapshot from the `jet-job-sample` `JetJob` custom resource to `snapshot-example`.

The configuration is as follows:

.Example JetJobSnapshot configuration 
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/jetjobsnapshot-example.yaml[]
----

<1> The name of the exported snapshot.
<2> The name of the JetJob custom resource from which the snapshot is exported.

== Start a Jet Job with the Snapshot

In this example, we start a Jet job that uses the snapshot exported in the previous example for initialization.

The configuration is as follows:

.Example JetJob initialization from Snapshot
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/jetjob-initial-snapshot-example.yaml[]
----

<1> The name of the JetJobSnapshot custom resource from which the Jet job is initialized.
