= Configure JVM arameters
:description: pass:q[You can configure the JVM in the `hazelcast` container using the `jvm` field of the CRD.]

{description}

== Configure a JVM parameter

Operator supports the following JVM configuration options in the `Hazelcast` resource. For more information, see the xref:api-ref.adoc#jvmconfiguration[API reference].

[cols="25%m,75%a"]
|===
|Field|Description

|initialRAMPercentage
|Initial heap size of the Hazelcast process as a percentage of the total memory of a container.

|maxRAMPercentage
|Maximum heap size for a JVM running with a large amount of memory.

|minRAMPercentage
|Maximum heap size for a JVM running with a small amount of memory.

|===

=== Set arbitrary JVM arguments

You can provide a list of JVM arguments.

.Example configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/jvm_args.yaml[]
----

== Example configuration

The following `Hazelcast` custom resource creates a cluster that uses all three parameters.

.Example configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/jvm.yaml[]
----

== Garbage collector parameters

=== Enable logging

To enable garbage collector logging, you can use the following configuration:

.Example configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/jvm_gc_logging.yaml[]
----

This sets the JVM argument `-verbose:gc`.

=== Set the garbage collector

WARNING: Before making garbage collector-related changes using Operator, read link:https://docs.hazelcast.com/hazelcast/latest/capacity-planning#garbage-collection-considerations[Garbage collector considerations] to decide which garbage collector to use.

To set the garbage collector:

.Example configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/jvm_gc_collector.yaml[]
----

`<collector>` can be replaced with the following options:

[cols="25%m,75%a"]
|===
|`<collector>`|JVM Equivalent

|Serial
|`-XX:+UseSerialGC`

|Parallel
|`-XX:+UseParallelGC`

|G1
|`-XX:+UseG1GC`

|===

== Enable IPv6 stack

You can use JVM arguments to enable IPv6 addressing in Hazelcast and set up a Hazelcast cluster on an IPv6-stack Kubernetes Cluster. The following example creates an IPv6 Hazelcast cluster:

.IPv6 Example configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-ipv6.yaml[]
----
