= Configuring JVM Parameters
:description: pass:q[You can configure the JVM in the `hazelcast` container using the `jvm` field of the CRD spec.]

{description}

== Configuring a JVM Parameter

Use any of the following configuration options in the `Hazelcast` resource. For more information, see the xref:api-ref.adoc#jvmconfiguration[API Reference].

[cols="25%m,75%a"]
|===
|Field|Description

|initialRAMPercentage
|Configures the initial heap size of the Hazelcast process as a percentage of the total memory of a container.

|maxRAMPercentage
|Sets the maximum heap size for a JVM running with a large amount of memory.

|minRAMPercentage
|Unlike its name, this parameter sets the maximum heap size for a JVM running with a small amount of memory.

|===

=== Setting Arbitrary JVM Arguments
You can provide a list of JVM arguments.

.Example configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/jvm_args.yaml[]
----

== Example Configuration

The following `Hazelcast` custom resource creates a cluster that uses all three parameters.

.Example configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/jvm.yaml[]
----

== GC Parameters
=== Enabling Logging
To enable Garbage Collector Logging, you can use the following configuration:

.Example configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/jvm_gc_logging.yaml[]
----

It is going to set the following JVM argument: `-verbose:gc`

=== Setting the Garbage Collector
WARNING: Before making Garbage Collector related changes using the Hazelcast Platform Operator, it is highly recommended to read link:https://docs.hazelcast.com/hazelcast/latest/capacity-planning#garbage-collection-considerations[Garbage Collector Considerations section of Capacity Planning Document] to decide which Garbage Collector to use.

To set the Garbage Collector, following configuration can be used:

.Example configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/jvm_gc_collector.yaml[]
----

`<collector>` can be replaced with the following options:

[cols="25%m,75%a"]
|===
|`<collector>`|JVM Equivalent

|Serial
|`-XX:+UseSerialGC`

|Parallel
|`-XX:+UseParallelGC`

|G1
|`-XX:+UseG1GC`

|===

== Enabling IPv6 Stack
Hazelcast supports IPv6 addresses seamlessly, although IPv6 support is switched off by default. To enable IPv6 addressing in Hazelcast and set up a Hazelcast cluster on an IPv6-stack Kubernetes Cluster, you'll need extra configurations. These configurations can be passed through JVM arguments. The provided example below shows how to create an IPv6 Hazelcast cluster using the Hazelcast Platform Operator.

.IPv6 Example configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-ipv6.yaml[]