= Deploying Lite Members

Use the Hazelcast Platform Operator to deploy xref:{page-latest-supported-hazelcast}@hazelcast:maintain-cluster:lite-members.adoc[Lite Members]. You can use the separate `liteMember` section in the xref:api-ref.adoc#litemember[Hazelcast CR].

WARNING: When `jvm`, `env`, `resources`, `scheduling` sections are configured in the Hazelcast CR, it will not affect the lite member configuration. Lite members must be configured as explained in the following sections.

== Configuring the Number of Lite Members

To configure the number of lite members you want to deploy in the Hazelcast CR, use the `count` field in the `liteMember` section of the xref:api-ref.adoc#litemember[Hazelcast CR].

.Example Lite Member Count Configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/lite-member.yaml[]
----

When you apply the given example, 3 data members and 2 lite members are deployed.

NOTE: As seen in the example, `clusterSize` represents the number of data members to be created.

== Configuring JVM Parameters

To configure JVM Parameters specifically for lite members, you can use the `jvm` field in the `liteMember` section of the xref:api-ref.adoc#litemember[Hazelcast CR].

.Example Lite Member JVM Configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/lite-member-jvm.yaml[]
----

== Configuring Environment Variables

To configure environment variables specifically for lite members, you can use the `env` field in the `liteMember` section of the xref:api-ref.adoc#litemember[Hazelcast CR].

Same rules and logic is applicable as in the xref:env-vars.adoc[Environment variables].

== Configuring Resource Limits

To configure resource limits specifically for lite members, you can use the `resources` field in the `liteMember` section of the xref:api-ref.adoc#litemember[Hazelcast CR].

.Example Lite Member Resource Limits Configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/lite-member-resource-limits.yaml[]
----

== Configuring Scheduling

To configure scheduling specifically for lite members, you can use the `scheduling` field in the `liteMember` section of the xref:api-ref.adoc#litemember[Hazelcast CR].

.Example Lite Member Scheduling Configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/lite-member-scheduling.yaml[]
----
