= Deploy Lite members
:description: Lite members are Hazelcast cluster members that do not store data or have partitions. They are mainly used to execute tasks and register listeners.

{description}

You can use Operator to deploy link:https://docs.hazelcast.com/hazelcast/latest/maintain-cluster/lite-members[Lite members]. Lite members use the separate `liteMember` section in the xref:api-ref.adoc#litemember[Hazelcast custom resource (CR)].

NOTE: Configuring `jvm`, `env`, `resources` or `scheduling` sections in the Hazelcast CR does not affect Lite member configuration. Lite members are configured separately.

== Deploy Lite members

To set the number of Lite members you want to deploy in the Hazelcast CR, use the `count` field in the `liteMember` section of the xref:api-ref.adoc#litemember[Hazelcast CR].

.Example Lite member count configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/lite-member.yaml[]
----

This example deploys three data members and two Lite members. Note that `clusterSize` represents the number of data members only.

== Configure JVM parameters

To configure JVM Parameters for Lite members, use the `jvm` field in the `liteMember` section of the xref:api-ref.adoc#litemember[Hazelcast CR].

.Example Lite member JVM configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/lite-member-jvm.yaml[]
----

== Configure resource limits

To configure resource limits for Lite members, use the `resources` field in the `liteMember` section of the xref:api-ref.adoc#litemember[Hazelcast CR].

.Example Lite member resource limits configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/lite-member-resource-limits.yaml[]
----

== Configure scheduling

To configure scheduling for Lite members, use the `scheduling` field in the `liteMember` section of the xref:api-ref.adoc#litemember[Hazelcast CR].

.Example Lite member scheduling configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/lite-member-scheduling.yaml[]
----

== Configure environment variables

To configure environment variables for Lite members, use the `env` field in the `liteMember` section of the xref:api-ref.adoc#litemember[Hazelcast CR].

The `env` field uses the link:https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#envvar-v1-core/[Kubernetes' EnvVar format].

NOTE: You cannot use the `env` field to configure Hazelcast environment variables, which are prefixed `HZ_`. To configure the Hazelcast environment variables, use xref:custom-config.adoc[].