= External Access to Management Center
:description: You can expose Management Center to an external IP address, which is accessible from outside the cluster, to monitor and manage your Hazelcast cluster.

{description}

Hazelcast Management Center supports multiple external access methods.

== Configuring Hazelcast External Access

You can use the following fields to expose Management Center to an external IP address:

[cols="30%m,70%a"]
|===
|Field|Description

|`externalConnectivity.type`
|The method used by Hazelcast Management Center for external access.
Valid values are as follows:

- `LoadBalancer` (default). Use this on cloud providers that support external load balancers, to provision a load balancer for Management Center.
- `NodePort`. Use this to allow the Kubernetes control plane to allocate a port from the range specified by the Kubernetes `--service-node-port-range` flag. By default the port range is `30000-32767`. Each node proxies the same port number on every Node to your Service.
- `ClusterIP`: Assigns an IP address from a pool of internal IP addresses that your cluster has reserved for that purpose.

|`externalConnectivity.ingress`
|The HTTP and HTTPS routes exposed from outside the cluster to Management Center in the cluster. For further information on the rules that control traffic routing, refer to the https://kubernetes.io/docs/concepts/services-networking/ingress/[Kubernetes documentation,window=_blank].

|`externalConnectivity.route`
|Only used if using RedHat OpenShift. A route that allows access at a public URL to allow external clients to connect using the hostname.  For further information on route configuration in OpenShift, refer to the https://docs.openshift.com/container-platform/4.13/networking/routes/route-configuration.html[OpenShift documentation,windo=_blank].

|===

=== Example LoadBalancer Configuration

In this example, we expose Management Center using a dedicated load balancer.

The configuration is as follows:

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/management-center-loadbalancer.yaml[]
----

=== Example Ingress Configuration

In this example, we expose Management Center using Ingress.

For further information on Ingress, refer to the https://kubernetes.io/docs/concepts/services-networking/ingress/[Kubernetes documentation,window=_blank].

The configuration is as follows:

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/management-center-ingress.yaml[]
----

NOTE: You must use Hazelcast Management Center version 5.4.0 or later if the path to your repository consists of multiple segments, such as _/hazelcast/management-center_.

=== Example Route Configuration

In this example, we expose Management Center using the default OpenShift Container Platform.

For further information on the OpenShift Container Platform, refer to the https://docs.openshift.com/container-platform/4.13/networking/routes/route-configuration.html[OpenShift documentation,window=_blank].

The configuration is as follows:

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/management-center-route.yaml[]
----
