= LDAP Security Provider
:description: You can use your existing Lightweight Directory Access Protocol (LDAP) server for Hazelcast Management Center authentication.

{description}

For further information on using LDAP with Hazelcast Management Center, refer to the xref:management-center:deploy-manage:ldap.adoc[Management Center documentation,window=_blank].

== Set Up the LDAP Security Provider

To set up the LDAP security provider, you must configure the `securityProvider.ldap` section of the Management Center custom resource.

The LDAP security provider is configured using the following fields in the Management Center custom resource:

[cols="30%m,70%a"]
|===
|Field|Description

|`url`
|The URL of your LDAP server, including the schema (_ldap://_) and port.

|`credentialsSecretName`
|The name of the secret containing the authentication credentials for administrator privileges on the LDAP server. 
In the secret, the `username` must be set to the distinguished name (DN).

|`userDN`
|The DNs to use when searching users.

|`groupDN`
|The DNs to use when searching groups.

|`adminGroups`
|The groups whose members, and nested group members, have administrator privileges in Management Center.

|`userGroups`
|The groups whose members, and nested group members, have read and write privileges in Management Center.

|`readonlyUserGroups`
|The groups whose members, and nested group members, have read only privileges in Management Center.

|`metricsOnlyGroups`
|The groups whose members, and nested group members, can only view metrics in Management Center.

|`userSearchFilter`
|The LDAP search filter expression to apply when searching for users.

|`groupSearchFilter`
|The LDAP search filter expression to apply when searching for groups.

|===

== Create a Secret for LDAP Credentials

To create a `Secret`, named `ldap-credentials`, for the LDAP credentials, use the following command:

[source,shell]
----
$ kubectl create secret generic ldap-credentianls --from-literal=username="cn=admin,dc=example,dc=org" --from-literal=password="adminpassword"
----

You can use the following command to check that the credentials were successfully added to the secret:

[source,shell]
----
$ kubectl get secret ldap-credentianls -o=yaml
----

The result is similar to the following:

[source,shell]
----
apiVersion: v1
data:
  password: YWRtaW5wYXNzd29yZA==
  username: Y249YWRtaW4sZGM9ZXhhbXBsZSxkYz1vcmc=
kind: Secret
metadata:
  creationTimestamp: "2023-10-11T10:51:37Z"
  name: ldap-credentianls
  namespace: default
  resourceVersion: "59391"
  uid: 299e5d42-4c72-4877-9a99-c6ffa3c68d07
type: Opaque
----

== Example Management Center LDAP Configuration

In this example, we configure the LDAP Security Provider as follows:

* Set the name of the secret containing the credentials.
* Set the DN for group searches.
* Set the filter for group searches. The filter in this configuration searches for groups that match the `member` attribute.
* Exclude nested groups from searches.
* Define the LDAP server URL.
* Set the DN for user searches.
* Define the privileges granted to each group.

The configuration is as follows:

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/management-center-ldap.yaml[]
----
