= Management Center Persistence
:description: Hazelcast Management Center persists metrics data for connected Hazelcast Clusters in a persistent volume, or on disk depending on the configuration.

{description}

The time series metrics collected for each connected Hazelcast cluster include the following:

* CPU load
* Memory consumption
* Operation counters

For further information on collected metrics and their configuration, refer to xref:hazelcast:ROOT:list-of-metrics.adoc[List of Hazelcast Metrics,window=_blank] in the Platform documentation.

By default, Management Center persists the collected metrics to a persistent volume. If you want to use disk instead of the persistent volume, disable persistence as described below.

== Configure Management Center Persistence

Set the `persistence` fields described below on creation of the custom resource only. Management Center is unaffected by any update to the `persistence` fields.

You can use the following fields to configure persistence in Management Center:

[cols="30%m,70%a"]
|===
|Field|Description

|`persistence.enabled`
|Whether to use a persistent volume or disk to store data.
By default, set to `true`, Management Center uses the defined `PersistentVolumeClaim` to store data.
If you want to store data on disk, set to `false`.

|`persistence.size`
|The requested storage size of the `PersistentVolumeClaim`.

|`persistence.existingVolumeClaimName`
|The `PersistentVolumeClaim` name used by Management Center for persistence. 
If this field is not empty, Management Center uses the existing claim instead of creating one.

|`persistence.storageClass`
|The `StorageClass` from which `PersistentVolumeClaim` is created.

|===

NOTE: StatefulSets do not support updates to the `volumeClaimTemplates` field. 

By default, Management Center persists metric data in the _hazelcast-mc_ directory of your home directory. If you want to use an existing `PersistentVolumeClaim` instead, set the name in the `.spec.persistence.existingVolumeClaimName` field of the Management Center custom resource. For further information on configuring where Management Center persists metrics, refer to xref:management-center:deploy-manage:configuring.adoc#where-management-center-saves-data[Where Management Center Saves Data,window=_blank] in the Management Center documentation.

=== Example Configuration

In this example, we assigns a Kubernetes Persistent Volume with a size of 10Gi.

The configuration is as follows:

.Example Management Center with Persistence Configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/management-center-persistence.yaml[]
----
