= Configure external access to Management Center
:description: You can expose Management Center outside Kubernetes to remotely manage your Hazelcast deployment.

{description}

Management Center supports several options for external access.

== Configure external access

Operator supports the following configuration for Management Center external access.

[cols="30%m,70%a"]
|===
|Field|Description

|`externalConnectivity.type`
| Management Center external access methods:

- `LoadBalancer` (default): On cloud providers that support external load balancers, setting `LoadBalancer` provisions a load balancer for your Management Center.
- `NodePort`: If you set `NodePort`, the Kubernetes control plane allocates a port from a reserved range (default: 30000-32767). Each node proxies that port (the same port number on every node) into your Kubernetes service.
- `ClusterIP`: Assigns an IP address from a pool of internal IP addresses that your Kubernetes cluster has reserved for that purpose.

|`externalConnectivity.ingress`
| Ingress exposes HTTP and HTTPS routes from outside the Kubernetes cluster to Management Center. Traffic routing is controlled by rules defined on the https://kubernetes.io/docs/concepts/services-networking/ingress/[Ingress] resource.

|`externalConnectivity.route`
| An OpenShift Container Platform https://docs.openshift.com/container-platform/4.13/networking/routes/route-configuration.html[Route] exposes a service at a host name so that external clients can reach it by name.

|===

=== Example Management Center load balancer configuration

The following example exposes Management Center using a dedicated load balancer.

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/management-center-loadbalancer.yaml[]
----

=== Example Management Center ingress configuration

The following example exposes Management Center using https://kubernetes.io/docs/concepts/services-networking/ingress/[Ingress].

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/management-center-ingress.yaml[]
----

=== Example Management Center route configuration

The following example exposes Management Center using the default OpenShift Container Platform https://docs.openshift.com/container-platform/4.13/networking/routes/route-configuration.html[Route].

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/management-center-route.yaml[]
----
