= Connecting to Hazelcast Cluster over TLS
:description: You can connect Management Center to a cluster that is configured to use TLS.

{description}

See xref:hazelcast:security:tls-ssl.adoc#tlsssl-for-hazelcast-clients[TLS/SSL for Hazelcast Clients] for more detailed information about the configuration and behavior of TLS in Hazelcast.

== Prerequisites

If a Hazelcast cluster is configured to use TLS, you need to configure the TLS secret.

[source,shell]
----
kubectl create secret tls example --cert=example.crt --key=example.key
----

== Configuring connection to Hazelcast Cluster over TLS

Below are the configuration options for the TLS client.

[cols="30%m,70%a"]
|===
|Field|Description

|`hazelcastClusters[].tls.secretName`
| Specifies the name of Kubernetes TLS secret.

|===

=== Example Configuration

The example configuration does the following:

- Configuring connection to a Hazelcast cluster using `hazelcast` DNS name
- Connect to `dev` Hazelcast cluster name
- Use `example` secret name to configure Management Center client configuration for TLS

.Example Management Center with TLS Configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/management-center-tls.yaml[]
----
