= Connect to a Hazelcast Cluster
:description: To connect Hazelcast Management Center to a Hazelcast cluster, you must configure at least the cluster name and the address of at least one member. 

{description}

You can connect Hazelcast Management Center to the following:

* Multiple clusters.
* A cluster that is configured to use TLS.

For further information on using Hazelcast Management Center, refer to the xref:management-center:deploy-manage:cluster-connections.adoc[Management Center documentation,window=_blank].

== Configure Cluster Connections

You can use the following fields to configure which Hazelcast clusters are monitored by Hazelcast Management Center:

[cols="30%m,70%a"]
|===
|Field|Description

|`hazelcastClusters[].address`
|The IP address or DNS name of the Hazelcast cluster. If the cluster is exposed from a service name in a different namespace, set the value using `<service-name>.<service-namespace>`.

|`hazelcastClusters[].name`
|The name of the Hazelcast cluster to which Hazelcast Management Center connects.
Default is `dev`.

|`hazelcastClusters[].tls.secretName`
|The name of the Kubernetes TLS secret.

|===

WARNING: You cannot delete clusters from the custom resource using the `hazelcastClusters` fields. To remove the cluster from Management Center, use the Management Center UI.

=== Example Management Center Configuration

In this example, we configure the following:

- The name used to connect to a Hazelcast cluster.
- The Hazelcast cluster name.

The configuration is as follows:

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/management-center-clusters.yaml[]
----

=== Example Configuration for Management Center with TLS

In this example, we configure the following:

- The name to use to connect to a Hazelcast cluster.
- The Hazelcast cluster name.
- The TLS secret to use when connecting to the Hazelcast cluster.

The configuration is as follows:

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/management-center-tls.yaml[]
----

Use the following command to create a TLS secret from the existing PEM certificate:

[source,shell]
----
kubectl create secret tls example --cert=example.crt --key=example.key
----
