= Configure Management Center persistence
:description: By default, Management Center persists metrics to a persistent volume. You can turn this off by disabling persistence.

{description}

Management Center collects and report metrics data for connected Hazelcast clusters. See xref:hazelcast:maintain-cluster:monitoring.adoc[Monitoring] for more information.

== Configure Management Center persistence

Operator supports the following configuration for Management Center persistence.

[cols="30%m,70%a"]
|===
|Field|Description

|`persistence.enabled`
| When true, Management Center will use a Persistent Volume Claim (PVC) to store data.

|`persistence.size`
| Size of the PVC.

|`persistence.existingVolumeClaimName`
| Name of an existing PVC to use. If left blank, Management Center will request a new PVC.

By default, xref:management-center:deploy-manage:configuring.adoc#where-management-center-saves-data[Management Center data] is persisted to the `/data` directory. If you want to use an existing PVC, set its name here.

|`persistence.storageClass`
| Storage class for the PVC.

|===

WARNING: StatefulSet does not support updates to the `volumeClaimTemplates` field, so the `persistence` field should be set only at the creation of the custom resource. Any update to the `persistence` field will not affect Management Center.

=== Example configuration

The following example configuration assigns a Kubernetes Persistent Volume with a size of 10GiB:

.Example Management Center with Persistence Configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/management-center-persistence.yaml[]
----
