= Connect Management Center to a Hazelcast cluster
:description: You can connect an instance of Management Center to multiple Hazelcast clusters.

{description}

To connect Management Center to a Hazelcast cluster, you need to configure the name of the cluster and the addresses of one or more members. You can connect Management Center to a cluster that is configured to use TLS by providing the Kubernetes secret.

See the xref:management-center:deploy-manage:cluster-connections.adoc[Management Center documentation] for more information.

== Configure cluster connections

Connection configuration for the Hazelcast clusters that Management Center will monitor.

[cols="30%m,70%a"]
|===
|Field|Description

|`hazelcastClusters[].address`
| IP address or DNS name of the Hazelcast cluster. If the cluster is exposed with a service name in a different namespace, use the following syntax: `<service-name>.<service-namespace>`.

|`hazelcastClusters[].name`
| Name of the Hazelcast cluster that Management Center will connect to. Default is `dev`.

|`hazelcastClusters[].tls.secretName`
| Name of the Kubernetes TLS secret.

|===

WARNING: The `hazelcastClusters` field does not support deleting clusters from the custom resource. If you want to remove a cluster from the Management Center, use the Management Center UI.

=== Example Management Center configuration

The example configuration creates a connection to a Hazelcast cluster `dev` with `hazelcast` as the DNS name.

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/management-center-clusters.yaml[]
----

=== Example Management Center configuration with TLS

The example configuration creates a TLS-secured connection to a Hazelcast cluster `dev` with `hazelcast` as the DNS name. It uses a secret named `example` for the TLS certificate.

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/management-center-tls.yaml[]
----

If required, you can create a TLS secret from an existing PEM certificate:

[source,shell]
----
kubectl create secret generic example \
  --from-file=tls.crt=example.crt \
  --from-file=tls.key=example.key
----

== Next steps

xref:management-center-external-access.adoc[].