= Configure Maps
:description: pass:q[Hazelcast maps are used to distribute data across a cluster and help to scale your applications while protecting data against member failures. You can create and configure maps using the Map custom resource.]

{description}

== Configure the `Map` Resource

The Map custom resource is configured using the following fields:

[cols="20%m,80%a"]
|===
|Field|Description

|name
|The name of the map configuration to create. If this field is empty, the custom resource name is used to create the name of the map. You cannot update the name after the map configuration has been created.

|hazelcastResourceName
|The name of the Hazelcast resource for which the map configuration is created.

|backupCount
|The count of synchronous backups.

|timeToLiveSeconds
|The maximum time in seconds that each entry remains in the map.

|maxIdleSeconds
|The maximum time in seconds that each entry can stay idle in the map.

|eviction
|When to remove data from the map based on the specified maximum size of the map. 
For information on the attributes used by this field, see xref:api-ref.adoc#evictionconfig[`EvictionConfig`] in the Hazelcast Operator API Reference.

|indexes
|The indexes to create for the map data.
For information on the attributes used by this field, see xref:api-ref.adoc#indexconfig[`IndexConfig`] in the Hazelcast Operator API Reference.
For further information on indexing maps, refer to :xref:hazelcast:query:indexing-maps.adoc[Indexing Maps,window=_blank] in the Platform documentation.

|attributes
|The custom attributes for field queries that use the Predicates API.
For information on the attributes used by this field, see xref:api-ref.adoc#attributeconfig[`AttributeConfig`] in the Hazelcast Operator API Reference.
For further information on using custom attributes for field queries, refer to xref:hazelcast:query:predicate-overview.adoc#creating-custom-query-attributes[Creating Custom Query Attributes, window=_blank] in the Platform documentation.

|persistenceEnabled
|Whether to enable map data persistence.
Deafult is `false`, which means that map data is not persisted. If you want to persist map data, set to `true`.

NOTE: Ensure that you enable persistence for Hazelcast before you enable persistence for the map. For further information on enabling persistence for Hazelcast, see  xref:backup-restore.adoc#enabling-persistence[Persistence, Backup and Restore].

|mapStore
|The configuration options for use when the map entries load from, or store to, a persistent data store such as a relational database using MapLoader or MapStore. 
For information on the attributes used by this field, see xref:api-ref.adoc#mapstoreconfig[`MapStoreConfig`] in the Hazelcast Operator API Reference.
For further information on using MapLoader and MapStore to connect to an external system, refer to xref:hazelcast:mapstore:working-with-external-data.adoc[Building a Cache with MapStore,window=_blank] in the Platform documentation.

|entryListeners
|The configuration options for use when listening for map-level or entry-based events using the listeners provided by the Hazelcast’s eventing framework. 
For information on the attributes used by this field, see xref:api-ref.adoc#entrylistenerconfiguration[`EntryListenerConfigurationConfig`] in the Hazelcast Operator API Reference.
For more information on listening for map-level and entry-based events, refer to xref:hazelcast:pipelines:object-events.adoc[Distributed Object Events,window=_blank] in the Platform documentation.

|nearCache
|The configuration options for server-side `Near Cache`. 
For information on the attributes used by this field, see xref:api-ref.adoc#nearcache[`NearCache`] in the Hazelcast Operator API Reference.
For further information on Near Cache, refer to xref:hazelcast:cluster-performance:best-practices.adoc#near-cache[Near Cache] in the Platform documentation.
|===

For further details on the fields used to configure Maps, see xref:api-ref.adoc#mapspec[MapSpec] in the Hazelcast Operator API Reference.

== Example Configuration

In this example, we configure a Map for the Hazelcast custom resource defined in the `hazelcastResourceName` field.

The configuration is as follows:

.Example configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/map.yaml[]
----

Once created, you can use the following command to check the status of the Map resource:

[source,shell]
----
kubectl get map map-sample -o wide
----

The result is similar to the following:

```
NAME         STATUS    HAZELCAST-RESOURCE   MESSAGE
map-sample   Success   hazelcast-sample
```
