= Migrate from Helm to Operator

Migrating from Helm requires recreating the Hazelcast cluster. Operator can't take control of custom resources created by a Helm chart.

To migrate, you can either restore from a backup or attach new pods to existing persistent volume claims (PVCs).

== Prerequisites

Both options require xref:backup-restore.adoc[persistence] to be enabled. You should also set the `cluster-data-recovery-policy` parameter's value to `PARTIAL_RECOVERY_MOST_COMPLETE` to avoid any issues during the restore process.

// RJS: How?

Restoring from a backup requires xref:deploy-management-center.adoc[Management Center].

== Restore from a backup

To create a new cluster from a backup of your current cluster:

. link:https://docs.hazelcast.com/management-center/5.9/clusters/triggering-hot-backup[Trigger a backup] using the Management Center user interface.

. Uninstall the existing Helm-managed cluster.

. xref:backup-restore#restoring-from-persistent-volumes.adoc[Restore from a persistent volume].

== Attach new pods to existing PVCs

You can also restore your data to a new cluster created by Operator without creating a backup by using the newly created Hazelcast CR's name.

The name of the new CR must be in the following format: `<name>-hazelcast-persistence`.

For example, if the older cluster was installed with the command `helm install hz hazelcast/hazelcast-enterprise`, the new CR name must be `hz-hazelcast-enterprise`. This means that PVCs created by the Helm Chart will attach to the pods created by Operator correctly.

// RJS: This is contradictory - hz-hazelcast-enterprise does not match the format name-hazelcast-persistence!