= Module deployment
:description: Operator allows you to deploy your own custom and domain classes to Hazelcast Plaftorm cluster members. You can deploy your application code from external buckets, ConfigMap objects, and URLs in Kubernetes.

{description}

This topic explains how to configure module deployment. It also brings together examples of when you might use module deployments as part of the configuration of other features, such as the xref:hazelcast:data-structures:working-with-external-data.adoc[implementation of an external data store] or an xref:hazelcast:computing:executor-service.adoc[executor service] for the asynchronous execution of tasks.

== Configure Module Deployment

Operator provides the following configuration options for the Module Deployment feature. For more information, see the xref:api-ref.adoc#moduledeploymentconfiguration[API reference].

[cols="20%m,80%a"]
|===
|Field|Description

|`bucketConfig`
|JAR files from an external bucket are placed under the Java classpath when the following parameter values are supplied:

  - `secretName`: Name of the Secret object that holds the credentials for your cloud provider.
  - `bucketURI`: Full path for the external bucket. For example: `gs://your-bucket/path/to/jars`.

|`configMaps`
|Files specified are placed under the Java classpath.

WARNING: The data stored in a ConfigMap cannot exceed 1 MiB. For more information, see link:https://kubernetes.io/docs/concepts/configuration/configmap/#motivation[Kubernetes documentation for ConfigMap].

|`remoteURLs`
|Files downloaded from these URLS will be placed under the Java classpath.

|`triggerSequence`
|Triggers a rolling restart to begin another download of the custom code.

|===

=== Example configuration

The example configuration below:

* Downloads the JAR files from the specified external bucket and places them under the classpath of each of the Hazelcast members.
* Puts all the files specified in the ConfigMap objects under the classpath of each of the Hazelcast members. 

WARNING: Mounted persistent volumes are not supported; only cloud provider external buckets are supported.

[tabs]
====

AWS::
+
--
Module Deployment in AWS S3:
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-module-deployment-aws.yaml[]
----
--

GCP::
+
--
Module Deployment in GCP:
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-module-deployment-gcp.yaml[]
----
--

Azure::
+
--
Module Deployment in Azure Blob:
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-module-deployment-azure.yaml[]
----
--
====
<1> Name of the secret with credentials for accessing the bucket URI.
<2> URI of the bucket where backup data will be stored.

== Configure an external data store

The `MapLoader` and `MapStore` interfaces in Hazelcast allow you to load map entries from and save map entries to an external data store. See xref:hazelcast:data-structures:working-with-external-data.adoc[Working with an external data store] for details.

To use an external data store, you need to create `MapLoader` and/or `MapStore` classes and add configuration. In Operator:

. Deploy the `MapLoader` and/or `MapStore` classes to the classpath of each Hazelcast member.
. Configure a `Map` resource for the MapLoader or MapStore.

Use the following configuration options in the `Map` resource for a MapStore. The example shows how you might implement these options. For more detailed information, see the xref:api-ref.adoc#mapstoreconfig[API reference].

|===
|Field|Description

|`initialMode`
|Sets the initial entry loading mode. LAZY is the default load mode, where load is asynchronous. EAGER means map operations are blocked until all partitions are loaded.

|`className`
|Name of your class that implements the `MapLoader` and/or `MapStore` interface.

|`writeDelaySeconds`
|Number of seconds to delay the storing of map entries.

|`writeBatchSize`
|Used to create batches when writing to the map store. In default mode, with a value of less than two, Hazelcast tries to write all map entries in one go.

|`writeCoealescing`
|For use with write-behind mode in a MapStore. When this option is set to true, Hazelcast coalesces updates on a specific key, and so applies only the last update. Set this option to false to store all updates performed on a key to the data store.

|`propertiesSecretName`
|You can use properties to give information to the MapStore implementation. In this case, properties are taken from the secret with the given name.

|===

=== Example MapStore configuration

An example `Map` resource with MapStore configuration. 

.Example configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/map-map-store.yaml[]
----

== Configure executor services

Hazelcast offers an executor service (`IExecutorService`), which is an implementation of `java.util.concurrent.ExecutorService`. With `IExecutorService`, you can execute tasks asynchronously and perform other useful tasks.

To use the executor service, you need to create `Callable` and/or `Runnable` classes and add configuration. In Operator:

. Deploy your `Callable` or `Runnable` classes to the classpath of each Hazelcast member.
. Configure a `Hazelcast` resource for the `Callable` or `Runnable` interface.

There are three variants of the executor service:

- Executor Service
- Durable Executor Service
- Scheduled Executor Service

Configuration options for a `Hazelcast` resource to work with all three variants are shown in this section, along with examples of how you might implement these options. For more detailed information, see xref:hazelcast:computing:executor-service.adoc[Java executor service]. 

[tabs]
====
Executor service::
+
--
See the xref:api-ref.adoc#executorserviceconfiguration[API reference] for more information.

|===
|Field|Description

|`name`
|The name of the executor service.

|`poolSize`
|The number of executor threads per member.

|`queueCapacity`
|Task queue capacity of the executor.

|===
--

Durable executor service::
+
--
See the xref:api-ref.adoc#durableexecutorserviceconfiguration[API reference] for more information.

|===
|Field|Description

|`name`
|The name of the executor service.

|`poolSize`
|The number of executor threads per member.

|`durability`
|Number of backups in the cluster for the submitted task.

|`capacity`
|Capacity of the executor task per partition.

|===
--

Scheduled executor service::
+
--
See the xref:api-ref.adoc#scheduledexecutorserviceconfiguration[API reference] for more information.

|===
|Field|Description

|`name`
|The name of the executor service.

|`poolSize`
|The number of executor threads per member.

|`durability`
|Number of backups in the cluster for the submitted task.

|`capacity`
|Capacity of the executor task per partition.

|`capacityPolicy`
|The active policy for the capacity setting.

|===
--

====


=== Example executor services

An example `Hazelcast` resource with Executor Services configured:

[tabs]
====
Executor service::
+
--
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-executor-service.yaml[]
----
--

Durable executor service::
+
--
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-durable-executor-service.yaml[]
----
--


Scheduled executor service::
+
--
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-scheduled-executor-service.yaml[]
----
--

====

== Configure an entry processor

An entry processor executes your code on a map entry in an atomic way. To implement the `EntryProcessor` interface, you can deploy an `EntryProcessor` class from Operator to the classpath of a Hazelcast member. See xref:hazelcast:data-structures:entry-processor.adoc[Entry processor] for more detailed information.
