= Configure the Native Memory Store
:description: The Native Memory Store is a pluggable memory manager that sets up different configurations, or stores, for your application’s data structures on a single JVM. These memory stores form part of a common access layer that scales up to use a configured amount of memory on the JVM.

{description}

The Native Memory Store provides the following:

* More predictable application scaling.
* Boosted performance.
* Reduced latency.
* Minimized garbage collection pauses. 

== Configure a Native Memory Store

You can use the following configuration options for the Native Memory Store:

[cols="25%m,75%a"]
|===
|Field|Description

|`allocatorType`
|The mechanism used to allocate memory. Valid values are as follows:

* `POOLED`. Default. Manages memory blocks in local thread pools.
* `STANDARD`. Allocates and frees memory using the default OS memory manager.

|`size`
|The total native memory. 
Set the `size` and `unit` attributes to define the amount of memory to allocate, and the unit in which the size is measured.
The default size is `128`, and the default unit is `MEGABYTES`


|`minBlockSize`
|The minimum amount of memory to allocate to the blocks in bytes. Default is `16`.
This is only used if the `allocatorType` is set to `POOLED`.
The value must be a power of two.

|`pageSize`
|Size of the page in bytes to allocate as a block of memory. Default is `4194304`, which is approximately 4 MB.
This is only used if the `allocatorType` is set to `POOLED`.

|`metadataSpacePercentage`
|Percentage of allocated native memory that is used for the metadata of other map components, including index, for predicates, and offset. Default is 12.5.
This is only used if the `allocatorType` is set to `POOLED`.

|===

=== Example Configuration

To configure the Native Memory Store, we must configure the cluster, the Map, and the cache.

In the following example, we configure the Native Memory Store as follows:

* Manage memory blocks in local thread pools.
* Allocate `512M` for the total native memory.

The configuration is as follows:

.Example Hazelcast configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-native-memory.yaml[]
----

In the following example, we configure the Map to use the Native Memory Store.

The configuration is as follows:

.Example Map configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-native-memory-map.yaml[]
----

In the following example, we configure the cache to use the Native Memory Store.

The configuration is as follows:

.Example Cache configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-native-memory-cache.yaml[]
----
