= Configure Container Resources

:description: pass:q[You can configure the resources required by your container, such as CPU and memory, using Hazelcast Operator.]

{description}

You can configure resources for the following containers:

* Hazelcast
* The platform-operator-agent sidecar
* Hazelcast Management Center

You can specify limits and requests for each container, which work as follows:

* Limits prevent the container from using more than the configured resource limt. 
+
For example, if you set a limit for the memory used by a container, that container cannot consume more memory than set by this limit. If a process tries to exceed this limit, the process is terminated with an out of memory (OOM) error.

* Requests do not impose limits. If sufficient resource is available for a container, it can use more resource than specified in the request. Requests are used by Kubernetes to schedule the container on a node with a minimum of the configured resource allocation.

For further information about resources and their management, refer to link:https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/[Resource Management for Pods and Containers,window=_blank] in the Kubernetes documentation.

== Configure Hazelcast Container Resources

To configure resources for the Hazelcast container, enter your requests and limits in the `resources` field of the CRD `spec` as follows:

.Example configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-resources.yaml[]
----

== Configure Sidecar Container Resources

To configure resources for the platform-operator-agent sidecar container, enter your requests and limits in the `agent.resources` field of the CRD `spec` as follows:

.Example configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/sidecar-resources.yaml[]
----

== Configure Hazelcast Management Center Container Resources

To configure resources for the Hazelcast Management Center container, enter your requests and limits in the `resources` field of the CRD `spec` as follows:

.Example configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/management-center-resources.yaml[]
----