= Scaling and Upgrading a Hazelcast Deployment

To scale an existing Hazelcast deployment, use the following command:

[source,shell]
----
kubectl scale hazelcast <name> --replicas <replica-count>
----

Example:

[source,shell]
----
kubectl scale hazelcast hazelcast-sample --replicas 5
----

== Upgrading

Before upgrade, we recommend you to check link:https://docs.hazelcast.com/hazelcast/5.3/maintain-cluster/rolling-upgrades#hazelcast-members-compatibility-guarantees[Hazelcast's Compatibility Guarantees].

To upgrade your existing deployment to a newer version, you need to update `spec.version` field and re-apply. For example:

Assuming the following is the existing configuration:

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-5.2.4.yaml[]
----

and you want to upgrade your Hazelcast version to {page-latest-supported-hazelcast}, you need to apply the following:


Assuming the following is the existing configuration:

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast.yaml[]
----

There are two system properties worth mentioning related to upgrade:

- During rolling upgrade cluster is shutdown gracefully to prevent data loss. You might want to configure link:https://docs.hazelcast.com/hazelcast/5.3/system-properties#hazelcast.graceful.shutdown.max.wait[hazelcast.graceful.shutdown.max.wait system property].

- Last step of link:https://docs.hazelcast.com/hazelcast/5.3/maintain-cluster/rolling-upgrades#rolling-upgrade-procedure[rolling upgrade procedure] is to trigger a rolling upgrade on the cluster. Hazelcast Platform Operator triggers it automatically by setting `hazelcast.cluster.version.auto.upgrade.enabled` to `true` by default.

NOTE: You can check xref:jvm-parameters.adoc[JVM Parameters] documentation to learn how to configure.

Example Configuration:

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/auto-upgrade.yaml[]
----

