= Scale and Upgrade a Hazelcast Deployment
:description: You can scale your deployment to create replicas, which can help to prevent the unexpected availability of your deployment. You can also upgrade the version of your deployment using a rolling upgrade.

{description}

== Scale

You can scale an existing Hazelcast deployment in either of the following ways:

- Modify the Hazelcast custom resource (the YAML definition you used to deploy Hazelcast cluster) by updating the `clusterSize` field.
+
You must re-apply the definition after you have updated it.
+
In this example, the existing configuration is as follows:
+
[source,yaml]
----
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast-sample
spec:
  clusterSize: 3
----
+
To scale the deployment to five replicas, we update this configuration as follows:
+
[source,yaml]
----
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast-sample
spec:
  clusterSize: 5
----
+
Once we have saved the changes, we reapply the configuration as follows:
+
[source,shell]
----
kubectl apply -f hazelcast-enterprise.yaml
----

- Use a command to scale an existing Hazelcast deployment. The command has the following format:
+
[source,shell]
----
kubectl scale hazelcast <name> --replicas <replica-count>
----
+
For example, we can scale the deployment to five replicas using the following command:
+
[source,shell]
----
kubectl scale hazelcast hazelcast-sample --replicas 5
----

== Upgrade

Before upgrading, refer to the xref:hazelcast:maintain-cluster:rolling-upgrades.adoc#hazelcast-members-compatibility-guarantees[Compatibility Guarantees,window=_blank] in the Platform documentation.

To upgrade the version of your existing deployment, you must do the following:

* Update the `spec.version` field in your Hazelcast custom resource. 
* Re-apply the definition.

In this example, the existing configuration is as follows:

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-5.2.4.yaml[]
----

To upgrade the Hazelcast version to {page-latest-supported-hazelcast},  we update this configuration as follows:

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast.yaml[]
----

Once we have saved the changes, we reapply the configuration, as follows:

[source,shell]
----
kubectl apply -f hazelcast-enterprise.yaml
----
