= Scaling and Upgrading a Hazelcast Deployment

To scale an existing Hazelcast deployment, use the following command:

[source,shell]
----
kubectl scale hazelcast <name> --replicas <replica-count>
----

Example:

[source,shell]
----
kubectl scale hazelcast hazelcast-sample --replicas 5
----

== Upgrading

Before upgrade, we recommend you to check xref:hazelcast:maintain-cluster:rolling-upgrades.adoc#hazelcast-members-compatibility-guarantees[Rolling Upgrades].

To upgrade your existing deployment to a newer version, you need to update `spec.version` field and re-apply. For example:

Assuming the following is the existing configuration:

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-5.2.4.yaml[]
----

and you want to upgrade your Hazelcast version to {page-latest-supported-hazelcast}, you need to apply the following:


Assuming the following is the existing configuration:

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast.yaml[]
----

It is worth highlighting the following system properties, which are related to upgrades:

- During a rolling upgrade, the cluster is shutdown gracefully to prevent data loss. You can configure this using the link:https://docs.hazelcast.com/hazelcast/5.3/system-properties#hazelcast.graceful.shutdown.max.wait[hazelcast.graceful.shutdown.max.wait system property].

- The final step in the link:https://docs.hazelcast.com/hazelcast/5.3/maintain-cluster/rolling-upgrades#rolling-upgrade-procedure[rolling upgrade procedure] is to trigger a rolling upgrade on the cluster. Hazelcast Platform Operator triggers it automatically by setting `hazelcast.cluster.version.auto.upgrade.enabled` to `true` by default, and it cannot be changed.

Example Configuration:

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/properties.yaml[]
----

