= Configure Hazelcast Serialization
:description: Before data can be sent over a network between cluster members and/or clients, it must be serialized into raw bytes. With Hazelcast Operator, you can configure Hazelcast Serialization using the Hazelcast custom resource.

{description}

Hazelcast Operator supports various serialization options; the one you choose depends on what you want to do with your data. For further information on the serialization options supported by Hazelcast, refer to the xref:hazelcast:serialization:serialization.adoc#serialization-options[Hazelcast Platform documentation,window=_blank].

For details of the fields used to configure serialization, see xref:api-ref.adoc#serializationconfig[SerializationConfig] in the Hazelcast Operator API Reference.

== Configure Custom Serialization

To register custom serializers, you must define the list of serializers and their types in the `serializers` section of your configuration. 

In this example, we register two custom serializers of different types.

The configuration is as follows:

.Custom serializers example configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/serialization-custom.yaml[]
----

== Configure Compact Serialization

To configure Compact serialization, you must define an explicit serializer and/or a zero-config serializer for a class in the `compactSerialization` section of your configuration. 

In this example, we register an explicit serializer, `com.example.FooSerializer`, and a zero-config serializer for the `com.example.Bar` class.

The configuration is as follows:

.Compact serialization example configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/serialization-compact.yaml[]
----

== Disallow Deserialization of Untrusted Java Classes

You can prevent Hazelcast Operator from deserializing arbitrary Java classes in the `javaSerializationFilter` section of your configuration. You can configure classes and/or packages to allow (whitelist) or disallow (blacklist) deserialization by name.

In this example, we allow the `example.Foo` class and the `com.acme.app` package, but disallow the `com.acme.app.BeanComparator` class.

The configuration is as follows:

.Java serialization filter example configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/serialization-filter.yaml[]
----
