= Tiered Storage
:description: Tiered Storage offers an extension to Hazelcast map, which allows you to store a larger data set than available memory.
:page-enterprise: true
:page-beta: true

{description}

See xref:hazelcast:tiered-storage:overview.adoc[Tiered Storage] for more detailed information about the configuration and behavior of Tiered Storage in Hazelcast.

Configuration for Tiered Storage includes setting the local device (local disk) parameters for the Hazelcast CR and providing Tiered Storage details for the Map CR.

== Configuring Local Devices

Native Memory must be enabled for Tiered Storage. You can learn about enabling Native Memory for Hazelcast in xref:native-memory.adoc#example-configuration[Native Memory]

WARNING: Native Memory size(*NativeMemory.Size*) must be at least 1084 MB * Number of Tiered Store Map. For example if you are planning to have 3 Tiered Store Map, you need at least 3 * 1084 MB Native Memory size.

For each given local device configuration, *clusterSize*(3) PVCs will be created and used as local disk.

.Example of Hazelcast CR
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-tiered-storage.yaml[]
----

== Configuring Tiered Store Map

In-memory-format must be *NATIVE* for the tiered-store maps.

.Example of Tiered Store Map
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/map-tiered-store.yaml[]
----

== Configuration Based Validations

- Native Memory must be enabled on Hazelcast CR and *InMemoryFormat* must be *NATIVE* on Map CR.
- Data Persistence and Tiered Storage are mutually exclusive features. Both can not be enabled simultaneously. *PersistenceEnabled* must be false.
- *Indexes*, *Eviction*, *TimeToLiveSeconds*, and *MaxIdleSeconds* are not supported for tiered-store maps.
- Configured local device size (*LocalDevice.PVC.RequestStorage*) must be higher than *MemoryCapacity*.
- Native Memory size(*NativeMemory.Size*) must be higher than sum of all *MemoryCapacity*
