= Configuring TLS
:description: Hazelcast TLS is a security feature that provides encryption and authentication of data transmitted between Hazelcast nodes, preventing unauthorized access and eavesdropping.

{description}

Hazelcast TLS uses standard SSL/TLS certificates, which can be obtained from trusted Certificate Authorities (CA) or self-signed. The certificates are used to establish trust between the communicating parties and ensure the authenticity of the communication channel.

See xref:hazelcast:security:tls-ssl.adoc[TLS/SSL Basics] for more detailed information about the configuration and behavior of TLS in Hazelcast.

== Prerequisites for TLS

Before you create and configure TLS, you need to create Kubernetes secret:

[source,shell]
----
kubectl create secret tls example --cert=example.crt --key=example.key
----

== Configuring Hazelcast TLS

Below are the configuration options for the TLS.

[cols="25%m,75%a"]
|===
|Field|Description

|`secretName`
| Specifies the name of Kubernetes TLS secret.

|`type`
| Type of SSL factory used in Hazelcast member and client network configuration.

  - `BasicSSL`: It corresponds to `com.hazelcast.nio.ssl.BasicSSLContextFactory` factory class. It is default value.
  - `OpenSSL`: It sets factory class to `com.hazelcast.nio.ssl.OpenSSLEngineFactory`. Be aware that it requires some external Jar files or even native libraries (OpenSSL/BoringSSL). See xref:hazelcast:security:integrating-openssl.adoc[Integrating OpenSSL] for more information.

|===

=== Example Configuration

The example configuration does the following:

- Enables member to member and member-client Hazelcast TLS connections
- Enforces mutual TLS authentication for cluster members

.Example Hazelcast configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-tls.yaml[]
----

.Example Managment Center configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/management-center-tls.yaml[]
----

==== OpenSSL Example

To be able to use `OpenSSL`, you need to add required Jar files into the classpath. You can take advantage of `UserCodeDeployment` feature to install dependency Jars and add them in the classpath.

.Example Hazelcast configuration for OpenSSL
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-tls-openssl.yaml[]
----

<1> Enable UserCodeDeployment to install required Jar files by OpenSSL
    Here is a sample list of Jars required by BoringSSL implementation:
    - netty-handler-4.1.91.Final.jar
    - netty-tcnative-boringssl-static-2.0.59.Final-linux-x86_64.jar
    - netty-tcnative-classes-2.0.59.Final.jar
<2> Set TLS type to OpenSSL
