= Configuring TLS
:description: Hazelcast TLS is a security feature that provides encryption and authentication of data transmitted between Hazelcast nodes, preventing unauthorized access and eavesdropping.

{description}

Hazelcast TLS uses standard SSL/TLS certificates, which can be obtained from trusted Certificate Authorities (CA) or self-signed. The certificates are used to establish trust between the communicating parties and ensure the authenticity of the communication channel.

See xref:hazelcast:security:tls-ssl.adoc[TLS/SSL Basics] for more detailed information about the configuration and behavior of TLS in Hazelcast.

== Prerequisites for TLS

Before you create and configure TLS, you need to create Kubernetes secret. The Operator uses the secret to create truststore and keystore, and it modifies the Hazelcast configuration according to it.

Example:

[source,shell]
----
kubectl create secret generic example \
  --from-file=tls.crt=example.crt \
  --from-file=tls.key=example.key
----

`ca.crt` is optional. You can also provide it to create the truststore:

[source,shell]
----
kubectl create secret generic example \
  --from-file=tls.crt=example.crt \
  --from-file=tls.key=example.key \
  --from-file=ca.crt=ca.crt
----

NOTE: If you provide `ca.crt`, it creates a truststore using it, if you don't create it, truststore and keystore will be the same.

NOTE: The Operator creates keystore and truststore in link:https://en.wikipedia.org/wiki/PKCS_12[PKCS12] format.

WARNING: The provided `tls.key` must be unencrypted.

== Configuring Hazelcast TLS

Below are the configuration options for the TLS.

[cols="25%m,75%a"]
|===
|Field|Description

|`secretName`
| Specifies the name of Kubernetes TLS secret.

|`mutualAuthentication`
|  Mutual authentication configuration, available values are:

- `None` (default): The client side of the connection is not authenticated.  
- `Required`:  Server forces usage of a trusted client certificate
- `Optional`: Server asks for a client certificate, but it doesn't require it

|===

=== Example Configuration

The example configuration does the following:

- Enables member to member and member-client Hazelcast TLS connections
- Enforces mutual TLS authentication for cluster members

.Example Hazelcast configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-tls.yaml[]
----

.Example Management Center configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/management-center-tls.yaml[]
----
