= Upgrade a Hazelcast deployment

Before upgrading, you should read the information in the xref:hazelcast:maintain-cluster:rolling-upgrades.adoc#hazelcast-members-compatibility-guarantees[rolling upgrade documentation] for Hazelcast Platform.

// RJS: Do you need to do any of the steps from this procedure, like triggering a rolling upgrade, or does Operator handle everything automatically?

Each Operator version has been tested with a specific Hazelcast Platform version as listed in the following table. You should use the appropriate version to avoid problems.

[cols="1,1"options="header"]
|===
| Operator version | Hazelcast Platform version
| 5.11 | 5.4.0
| 5.12 | 5.4.0
| 5.13 | 5.5.0
| 5.14 | 5.5.2
| 5.15 | 5.5.4
| 5.16 | 5.6.0
|===

== Upgrade the deployment

To upgrade your existing Hazelcast deployment to a newer version, update the `spec.version` field and re-apply.

For example, if the following is the existing configuration:

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-5.2.4.yaml[]
----

Apply the following to upgrade your Hazelcast version to {page-latest-supported-hazelcast}:

[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast.yaml[]
----

== Check the cluster status

You can check that the upgrade has completed by checking the cluster status:

[tabs]
====
Kubernetes::
+
--
[source,shell]
----
kubectl get hazelcast
----
--
Openshift::
+
--
[source,shell]
----
oc get hazelcast
----
--
====

```
NAME               STATUS    MEMBERS
hazelcast-sample   Running   3/3
```

// RJS: Can you check the version with Operator or do you need to use the MC cluster dashboard? What's the behavior / service impact during upgrade?