= User Code Namespaces
:description: User Code Namespaces provide a container for Java classpath resources, such as user code and accompanying artifacts like property files. This provides namespace isolation to ensure that access to resources in different namespaces can be managed through configuration. From Hazelcast Platform Operator, you can deploy your application code from external buckets using UserCodeNamespace CRs. 

{description}

See xref:hazelcast:clusters:user-code-namespaces.adoc[User Code Namespaces] for more detailed information about the configuration and behavior of User Code Namespaces in Hazelcast.

== Enabling User Code Namespaces

To enable User Code Namespaces you must configure the `userCodeNamespaces` section in the Hazelcast custom resource.

.Example of Hazelcast with User Code Namespaces enabled
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-ucn.yaml[]
----

== Creating a User Code Namespace

To create a User Code Namespace, you must create a new `UserCodeNamespace` CR. The name of the CR is used as the name of the created User Code Namespace. The JAR files stored in the configured bucket are uploaded to the Hazelcast cluster under the newly created namespace.

.Example of User Code Namespaces
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/user-code-namespace.yaml[]
----
<1> The bucket URI in which to store backup data
<2> Name of the secret with credentials for accessing the Bucket URI.

To allow your data structures to resolve your user code, you must reference the required namespace in the data structure configuration. You can configure the same namespace for multiple data structures.

.Example of Map with User Code Namespace
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/map-ucn.yaml[]
