= User Code Namespaces
:description: User Code Namespaces provide a container for Java classpath resources, such as user code and accompanying artifacts like property files. This provides namespace isolation to ensure that access to resources in different namespaces can be managed through configuration. Using Operator, you can deploy your application code from external buckets using UserCodeNamespace CRs.

{description}

See xref:hazelcast:clusters:user-code-namespaces.adoc[User Code Namespaces] for more detailed information about the configuration and behavior of User Code Namespaces in Hazelcast, including how updates to deployed resources affect running members.

== Enable User Code Namespaces

To enable User Code Namespaces, configure the `userCodeNamespaces` section in the Hazelcast custom resource (CR).

.Example of Hazelcast with User Code Namespaces enabled
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/hazelcast-ucn.yaml[]
----

== Create a User Code Namespace

To create a User Code Namespace, you must create a new `UserCodeNamespace` CR. The name of the CR is used as the name of the created User Code Namespace. The JAR files stored in the configured bucket are uploaded to the Hazelcast cluster under the newly created namespace.

[tabs]
====

AWS::
+
--
User Code Namespaces in AWS S3:
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/user-code-namespace-aws.yaml[]
----

NOTE: For further information about accessing resources on different cloud providers, see xref:authorization.adoc[Authorization Methods to Access Cloud Provider Resources].
--

GCP::
+
--
User Code Namespaces in GCP:
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/user-code-namespace-gcp.yaml[]
----

NOTE: For further information about accessing resources on different cloud providers, see xref:authorization.adoc[Authorization Methods to Access Cloud Provider Resources].
--

Azure::
+
--
User Code Namespaces in Azure Blob:
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/user-code-namespace-azure.yaml[]
----

NOTE: For further information about accessing resources on different cloud providers, see xref:authorization.adoc[Authorization Methods to Access Cloud Provider Resources].
--
====
<1> Name of the secret with credentials for accessing the bucket URI.
<2> The bucket URI from which user code JAR files are loaded.

To allow your data structures to resolve your user code, set `spec.userCodeNamespace` on the data structure CR to the name of the `UserCodeNamespace` CR. You can use the same namespace name on multiple data structures.

.Example of Map with User Code Namespace
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/map-ucn.yaml[]
----

== Delete a User Code Namespace

Deleting a `UserCodeNamespace` CR removes only that resource from Kubernetes. It does not delete `Map`, `Cache`, or other CRs that set `spec.userCodeNamespace` to the same name.

To remove a User Code Namespace:

. Delete any `Map`, `Cache`, `Queue`, `Topic`, `MultiMap`, or `ReplicatedMap` CR that sets `spec.userCodeNamespace` to that namespace, and any executor services on the `Hazelcast` CR that use the same name.
. Delete the `UserCodeNamespace` CR.
. Restart Hazelcast members.

[CAUTION]
====
Restart Hazelcast members after deleting the `UserCodeNamespace` CR. Deleting the CR does not unload the namespace from members that are already running.
====

[tabs]
====
Kubernetes::
+
--
[source,shell]
----
kubectl delete usercodenamespace <namespace-cr-name>
----
--
Openshift::
+
--
[source,shell]
----
oc delete usercodenamespace <namespace-cr-name>
----
--
====
