= Using Service Accounts to Access Cloud Provider Resources

You can use `Service Accounts` to access cloud provider resources without providing `secretName` in `HotBackup`, `JetJob`, `UCN` custom resources. To be able to use it you need to provide `serviceAccountName` in your Hazelcast CR.

.Example of Service Account Configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/service-account.yaml[]
----

== Accessing GCP Resources using Workload Identity
Google Kubernetes Engine (GKE) Workload Identity is a feature that allows you to map a Kubernetes Service Account to a Google Cloud IAM (Identity and Access Management) Service Account so that users can manage pods permissions using IAM.

Create a Service Account using the following command:

[source,shell]
----
kubectl create serviceaccount myServiceAccount --namespace <NAMESPACE>
----

To be able to use it, you need to annotate the service account you created with the following command:

[source,shell]
----
kubectl annotate serviceaccount myServiceAccount \
--namespace <NAMESPACE> \
iam.gke.io/gcp-service-account=<GCP_SA_NAME>@<GCP_PROJECT>.iam.gserviceaccount.com
----

== Accessing AWS Resources using IAM Roles for Service Accounts
IAM roles for service accounts is a feature that allows you to map a Kubernetes Service Account to a AWS IAM Role so that users can manage pods permissions using IAM.

Create a Service Account using the following command:

[source,shell]
----
kubectl create serviceaccount myServiceAccount --namespace <NAMESPACE>
----

To be able to use it, you need to annotate the service account you created with the following command:

[source,shell]
----
kubectl annotate serviceaccount myServiceAccount \
--namespace <NAMESPACE> \
eks.amazonaws.com/role-arn=arn:aws:iam::<AWS_ACCOUNT_ID>:role/my-role
----