= Syncronizing WAN replicated data
:description: pass:q[WAN Syncronization allows you to overcome out-of-sync issues with the WAN replicated data. ]
:page-enterprise: true

{description}

See xref:hazelcast:wan:advanced-features#synchronizing-wan-clusters.adoc[Synchronizing WAN Clusters] for more detailed information about the configuration and behavior of WAN replication in Hazelcast.

== Prerequisites for WAN Sync

Before you create and configure a `WanSync` resource, you must create the following:

- At least one `Hazelcast` resource and one `Map` resource for the source Hazelcast cluster.
- A target Hazelcast cluster that is accessible from the source cluster.   
- A `WanReplication` CR that points to the target cluster.

== Configuring the WanSync Resource

To configure WAN Syncronization, you must create `WanSync` resource. For more detailed information, see the xref:api-ref.adoc#wansyncspec[API Reference].

To create `WanSync` resource you must use the existing `WanReplication` CR. This means that the `WanSync` reuses the existing and running WAN replication process.

.Example of WanSync using the existing WanReplication
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/wan-sync-full.yaml[]
----

== Configuring Delta WanSync

To configure xref:hazelcast:wan:advanced-features#delta-wan-synchronization.adoc[Delta WAN Sync] for the Hazelcast cluster, you must configure Merkle Tree for the `Map` and set the `synConsistencyCheckStrategy` to `MERKLE_TREES` in the `WanReplication`. The created `WanSync` will automatically use Delta WAN Synchronization.

.Example of Delta WanSync
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/wan-sync-delta.yaml[]
----


== Checking the Status of a WAN Sync

After creating the `WanSync` resource, run the following command to see the WAN syncronization status:

[source,shell]
----
kubectl get wansync wansync-sample
----

The output is similar to the following:

----
NAME                     STATUS
wansync-sample-sample    Completed
----
