= Syncronize WAN replicated data
:description: pass:q[WAN syncronization allows you to overcome out-of-sync issues with WAN replicated data.]

{description}

See xref:hazelcast:wan:advanced-features#synchronizing-wan-clusters.adoc[Synchronizing WAN clusters] for more detailed information about the configuration and behavior of WAN syncronization in Hazelcast.

TIP: For a worked example, see the xref:tutorials:operator-tutorial-wan-sync.adoc[Synchronize WAN replicated data tutorial].

== Prerequisites for WAN syncronization

Before you create and configure a `WanSync` resource, you must create the following:

- At least one `Hazelcast` resource and one `Map` resource for the source Hazelcast cluster.
- A target Hazelcast cluster that is accessible from the source cluster.   
- A `WanReplication` CR that points to the target cluster.

== Configure the WAN syncronization resource

To configure WAN syncronization, you must create a `WanSync` resource. For more detailed information, see the xref:api-ref.adoc#wansyncspec[API reference].

To create a `WanSync` resource you must use the existing `WanReplication` CR. This means that the `WanSync` resource reuses the existing and running WAN replication process.

.Example of WanSync using the existing WanReplication
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/wan-sync-full.yaml[]
----

== Configure delta WAN syncronization

To configure xref:hazelcast:wan:advanced-features#delta-wan-synchronization.adoc[delta WAN syncronization] for the Hazelcast cluster, do the following:

* Configure Merkle tree for the `Map` resource.
* Set `syncConsistencyCheckStrategy` to `MERKLE_TREES` in the `WanReplication` resource.
* Create the `WanSync` resource. The created `WanSync` automatically uses Delta WAN Synchronization.

.Example of delta WAN syncronization
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/wan-sync-delta.yaml[]
----

== Checking the status of a WAN syncronization

After creating the `WanSync` resource, run the following command to see the WAN syncronization status:

[source,shell]
----
kubectl get wansync wansync-sample
----

The output is similar to the following:

----
NAME                     STATUS
wansync-sample-sample    Completed
----
