= Synchronize WAN Replicated Data
:description: pass:q[WAN Synchronization allows you to overcome issues when the WAN replicated data becomes unsynchronized.]
:page-enterprise: true

{description}

For further information on WAN replication and cluster synchronization in Hazelcast, refer to xref:hazelcast:wan:advanced-features.adoc#synchronizing-wan-clusters[Synchronizing WAN Clusters,window=_blank] in the Platform documentation.

== Prerequisites

Before you create and configure a WanSync resource, you must create the following:

- At least one Hazelcast custom resource for the source Hazelcast cluster.
- One Map resource for the source Hazelcast cluster.
- A target Hazelcast cluster that is accessible from the source cluster.   
- A WanReplication resource that points to the target cluster.

== Configure the WanSync Resource

You must use the existing WanReplication custom resource to create WanSyn resource. This ensures that the WanSync resource reuses the existing and running WAN publisher configuration.

To create the WanSync resource based on the existing WANReplication custom resource, update your configuration as follows: 

.Example of WanSync using the existing WanReplication
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/wan-sync-full.yaml[]
----

For further information on the fields used to configure WAN Synchronization, see xref:api-ref.adoc#wansyncspec[WanSyncSpec] in the Hazelcast Operator API Reference.

== Check the Status of a WAN Sync

Once created, you can use the following command to check the status of the WanSync resource:

[source,shell]
----
kubectl get wansync wansync-sample
----

The result is similar to the following:

----
NAME                     STATUS
wansync-sample-sample    Completed
----
