= Configuring WAN Replication
:description: pass:q[WAN Replication allows you to keep multiple Hazelcast clusters in sync on multi-site and multi-cloud deployments worldwide. You can create a WanReplication resource to be able to replicate a map on a target Hazelcast cluster. ]

{description}

== Configuring the `WanReplication` Resource

Below are the configuration options for the `WanReplication` resource. Before creating the `WanReplication` resource you need to create a source `Hazelcast` cluster resource and a `Map` resource for the source cluster. You should also create a target cluster which should be accessible from the source cluster. You can learn more about WAN Replication in the link:https://docs.hazelcast.com/hazelcast/latest/wan/wan[Hazelcast Platform Documentation].

You can find more detailed information about `WanReplication` resource configuration in xref:api-ref.adoc#wanreplicationspec[API Reference] page.

[cols="20%m,80%a"]
|===
|Field|Description

|mapResourceName
|MapResourceName is the name of Map custom resource which WAN replication will be applied to.

|targetClusterName
|targetClusterName is the cluster name of the target Hazelcast cluster.

|endpoints
|Endpoints is the comma separated target cluster member adresses.

|queue
|Queue is the configuration for WAN events queue.

- capacity: Capacity is the total capacity of WAN queue.
- fullBehavior: FullBehavior represents the behavior of the new arrival when the queue is full.

|batch
|Batch is the configuration for WAN events batch.

- size: Size represents the maximum batch size.
- maximumDelay: MaximumDelay represents the maximum delay in milliseconds. If the batch size is not reached, the events will be sent after the maximum delay.

|acknowledgement
|Acknowledgement is the configuration for the condition when the next batch of WAN events are sent.

- type: Type represents how a batch of replication events is considered successfully replicated.
- timeout: Timeout represents the time the source cluster waits for the acknowledgement. After timeout, the events will be resent.

|===

== Example Configuration

The following `WanReplication` resource creates WAN Replication configuration for the `Hazelcast` resource the map is created for.

.Example configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/wan-replication-example.yaml[]
----

After creating the `WanReplication` resource, you can learn about its status with the following command

[source,shell]
----
kubectl get wanreplication wanreplication-sample -o wide
----

----
NAME                     STATUS    MESSAGE
wanreplication-sample    Success
----

You can also monitor the status of the WAN replications in Management Center dashboard. Learn to deploy Management Center at xref:get-started.adoc#step-4-start-management-center[Start Management Center].