= Configure WAN Replication
:description: pass:q[WAN replication allows you to keep Hazelcast clusters synchronized across multiple sites or cloud deployments. You can replicate maps from different source clusters to a single target Hazelcast cluster. ]
:page-enterprise: true

{description}

Hazelcast Operator allows you to create a WanReplication resource, which handles the replication.

For further information on  WAN replication in Hazelcast, refer to xref:hazelcast:wan:wan.adoc[WAN replication,window=_blank] in the Platform documentation.

== Prerequisites

Before you create and configure a WanReplication resource, you must create the following:

- At least one Hazelcast custom resource for the source Hazelcast cluster.
- At least one Map resource for the source Hazelcast cluster.
- A target Hazelcast cluster that is accessible from the source cluster.      

== Configure the WanReplication Resource

The WanReplication resource is configured using the following fields: 

[cols="25%m,75%a"]
|===
|Field|Description

|`resources`
|The list of custom `Map` or `Hazelcast` resources to which WAN replication applies. This is defined in the following attributes:

- `name`. The name of the custom resource to which WAN replication applies.
- `kind`. The type of the custom resource to which WAN replication applies. The type can be either `Map`(default) or `Hazelcast`. Use `Hazelcast` when you want to apply WAN replication to all custom maps created under the configured `Hazelcast` custom resource. WAN Replication is started automatically for new Map resources. 

|`targetClusterName`
|The name of the Hazelcast cluster that is the target of the replication.

|`endpoints`
|A comma-separated list of the IP addresses of Hazelcast members in the target cluster.

|`queue`
|The behavior of the WAN events queue. This is defined in the following attributes:

- `capacity`. The total capacity of the WAN events queue. When the number of events exceeds the configured capacity, `fullBehavior` is triggered.
- `fullBehavior`. The policy applied after the `capacity` has been exceeded. Valid values are as follows:

** `DISCARD_AFTER_MUTATION`. Use this when you want to drop WAN events generated by the member when `capacity` is exceeded. The dropped WAN events are not replicated.
** `THROW_EXCEPTION`. Use this when you want to throw `WanReplicationQueueFullException` if `capacity` is exceed on a queue. This approach checks the size of the WAN events queue before a mutating operation, such as `IMap.put()` or `ICache.put()`. If an exception occurs, the operation is not allowed.
** `THROW_EXCEPTION_ONLY_IF_REPLICATION_ACTIVE`. Use this if you only want to throw an exception when WAN replication is active. New events are discarded if WAN replication stops.

|`batch`
|The behavior when batching WAN replication events. This is defined in the following attributes:

- `size`. The maximum size of a batch.
- `maximumDelay`. The maximum time in milliseconds for which events are added to a batch if the `size` has not been reached.

|`acknowledgement`
|The acknowledgement sent after a batch of replication events has been received by the target cluster.

- `type`. When to send an acknowledgement. Valid values are as follows:

** `ACK_ON_RECEIPT`. Use this when you want to send an acknowledgement when the batch is received. 
** `ACK_ON_OPERATION_COMPLETE`. Use this when you want to send an acknowledgement after each update has been applied to the target cluster.

- `timeout`. The length of time in milliseconds that the source cluster waits for an acknowledgement. If no acknowledgement is received before the timeout expires, the replication events are resent.

|===

For further information on the fields used to configure WAN replication, see xref:api-ref.adoc#wanreplicationspec[WANReplicationSpec] in the Hazelcast Operator API Reference.

== Example Configuration

In this example, we configure WAN replication for the Hazelcast and Map resources on the source Hazelcast cluster.

The configuration is as follows:

.Example configuration
[source,yaml,subs="attributes+"]
----
include::ROOT:example$/wan-replication-example.yaml[]
----

NOTE: If the endpoints do not specify a port number, the default Hazelcast port, '5710', is joined to the endpoints.

== Check the Status of a WAN Replication

Once created, you can use the following command to check the status of the WanReplication resource:

[source,shell]
----
kubectl get wanreplication wanreplication-sample -o wide
----

The result is similar to the following:

----
NAME                     STATUS    MESSAGE
wanreplication-sample    Success
----

NOTE: You can also use Management Center to monitor the status of WAN replications. For further information on deploying Management Center with Hazelcast Operator, see xref:deploy-management-center.adoc[].


== Delete the WanReplication Custom Resource

If you delete the `WanReplication` object, replication of all maps in the `.spec.resources` field stops and the queues are cleared.
