= What's New in Hazelcast Platform Operator
:description: Here are the highlights of what's new and improved in Hazelcast Platform Operator 5.13.0.

{description}

NOTE: For new and improved features in Hazelcast Platform 5.5, see xref:{page-latest-supported-hazelcast}@hazelcast:ROOT:whats-new.adoc[What's new in Hazelcast Platform 5.5].

== Community Edition and Repository Changes

In March 2024, we made some updates to the Community Edition of the Hazelcast Platform, including making the Platform Operator 5.13 closed-source and its cluster creation capabilities will no longer be available in the Community Edition. 

You can find more information here: https://hazelcast.com/blog/changes-to-community-edition/


== WAN Replication Performance and Usability Enhancements

For performant WAN Replication, all members should be connected directly by source clusters. To achieve this topology, we have intorudced `WithExposeExternally` parameter for Advanced WAN Network configuration at Hazelcast custom resource, see xref:advanced-networking.adoc#configuring-wan-protocol-sockets[Configuring WAN Protocol Sockets]

In the 5.13 release, improvements have been made to the WANReplication custom resource to provide more accurate and informative status and validations.


== Multi-member routing for Java clients

With the release of Hazelcast Platform 5.5, you can use multi-member routing to provide greater performance and stability for Java client applications connecting to geographically dispersed clusters. 

On the Platform Operator side, you can utilize this feature using 'High Availability Mode'. For more information, see xref:high-availability-mode.adoc##high-availability-mode-and-multi_member-routing[High Availability Mode and MULTI_MEMBER Routing] 


== Distribute your workload with Jet Job placement control

With the release of Hazelcast Platform 5.5, you can configure Jet processing jobs so that they run on lite members only, allowing you to split your computational and storage requirements without the need to configure each job separately. 

[NOTE]
====
Currently, lite member creation support has not been introduced on the Platform Operator, but it is planned to be released in upcoming versions.
====


== Additional Improvements

For detailed release notes that include new features and enhancements, breaking changes, deprecations and other fixes, see xref:release-notes.adoc[5.13 Release Notes].

To get started with Platform Operator, see xref:get-started.adoc[Deploy a Cluster with the Hazelcast Platform Operator for Kubernetes].

== API Reference

Please refer to the xref:api-ref.adoc[API Reference]. for a complete list of available parameters for custom resources.