name: Backport changes to maintenance branches
on:
 push:
  branches:
   - main

env:
  MAINTENANCE_BRANCHES: "['5.8', '5.9', '5.10', '5.11', '5.12', '5.13', '5.14']"

jobs:

  backport-to-all-branch:
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJSON(env.MAINTENANCE_BRANCHES) }}
    uses: hazelcast/hz-docs/.github/workflows/backport-workflow.yml@main
    with:
      label-to-check-for: '["backport to all versions"]'
      target-branch: v/${{ matrix.branch }}
    secrets: inherit

  backport-to-specified-branch:
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJSON(env.MAINTENANCE_BRANCHES) }}
    uses: hazelcast/hz-docs/.github/workflows/backport-workflow.yml@main
    with:
      label-to-check-for: '["backport to ${{ matrix.branch }}"]'
      target-branch: v/${{ matrix.branch }}
    secrets: inherit
